### ISSUE TITLE
Updates to our datepicker

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3712]
![Screenshot 2022-12-08 at 8.52.14 AM.png](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/a1940048-5277-4099-bfc8-6f545f94ace6/99a0163e-8ddf-4a47-acfc-ab819c2a1b68)

**Comment by Vadman97** [comment]
could we build this using a headless datepicker library like https://github.com/rehookify/datepicker?

**Comment by et** [comment]
There's one outstanding issue to make hours/seconds something one can set but it's low priority so it's broken out into a separate task (#4764).
