### ISSUE TITLE
canvas recording does not work in safari

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3789]
[https://app.highlight.run/1074/sessions/H3VODGLerDlbIwWc6QqsZadXCWKr](https://app.highlight.run/1074/sessions/H3VODGLerDlbIwWc6QqsZadXCWKr)

**Comment by soulwawa** [comment]
Hi.
Is this problem still there?
It's the same site, but the contents of Chrome and Safari are different

**Comment by Vadman97** [comment]
duplicate of #6775
