### ISSUE TITLE
logo cleanup

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3839]
![image.png](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/b6e78527-1ea0-485e-bbfd-22808f530373/215ba42d-22d2-4e9d-a27f-b4ad01bea58c)

can we get rid of writesonic and examedi? That'll give us a nice 6x3 grid

cc @vadim @haroon

**Comment by vadim** [comment]
You're mentioning the wrong Vadim.
