### ISSUE TITLE
Slack channels should not be removed when disconnecting the integration

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3920]
When a slack integration is removed, we also remove all the channels attached to an alert. The suspicion is that we did this because our slack calls aren't checking if an integration is configured correctly before sending a request. We should fix that problem and persist slack channels for alerts when a slack integration is disabled.

**Comment by meetwithyash** [comment]
@jay-khatri , I have tested this case in my local. It seems like it is not happening. Even after disabling the integration of Slack from highlight, the channel is not being removed.

Am I missing something here?
