### ISSUE TITLE
Get golang error stacktraces working

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3923]
Here's a sample golang stacktrace; doesn't look pretty. 

[https://app.highlight.io/1/errors/IWXv5fCoKjBRX2uEeMHNNeCoQi8t?page=1](https://app.highlight.io/1/errors/IWXv5fCoKjBRX2uEeMHNNeCoQi8t?page=1)

But at the same time, I don't think its too much work to:

* use a library that supports a proper stacktrace
* format it accordingly in the stacktrace UI
* write up some docs on how this can be done + add golang docs to highlight.io/docs/sdk…

**Comment by et** [comment]
These are looking good now. Closing out. We can create a new ticket if there's any new issues.
