### ISSUE TITLE
Implement the Comment Modal UI

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3924]
Apply existing comment designs to the comment UI.

**Comment by jay-khatri** [comment]
@aptlin to help out with making the issue digestable.

**Comment by alceil** [comment]
Can I work on this? @jay-khatri @Vadman97

**Comment by Vadman97** [comment]
hey @alceil, this might require a bit more back-and-forth and would be a pretty big project. happy to share the figma though if you're interested. we have a lot of more structured tasks under the label good-first-issues that would be a great starting point.

**Comment by alceil** [comment]
@Vadman97 Ok then I would check out other issues then thanks for the reply.

**Comment by wasimTQ** [comment]
Hey @Vadman97, I'd love to work on this. I've requested access to the figma file. 
Let me setup the app in my machine.
