### ISSUE TITLE
Changes to live session experience.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3925]
Make some changes to live sessions:
1) Linking to a live session should put you into "non-live" mode by default
2) Change the copy of the button from "Live" to "Switch to live mode"
3) Julianify the live loading modal

Customer feedback / background.
"- it took me a few minutes to figure out clicking on "Live" takes you to the session navigator view for live sessions"

How can we make the the Live indicator more obvious? For some reason it doesn't obviously look like a button, it just looks like an indicator. 

![image.png](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/31242368-2274-4b77-8e51-656c0e433f74/90343418-c1df-49f3-9e0e-3d0af1d2dfac)

cc @vadim

**Comment by vadim** [comment]
@jay-khatri please stop mentioning me. I'm not involved with this project.

**Comment by jay-khatri** [comment]
cc @julian-highlight to share a design for a julian-ified live loading modal.
