### ISSUE TITLE
New Setup page UI

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3930]
We currently have a Setup page and the bubble that's shown in the bottom right of the page. We want to redesign the Setup page and move the onboarding bubble info to something more prominent in the main nav, maybe a progress bar that you see until you're integrated.

this is part of "gamifying onboarding"

**Comment by ccschmitz** [comment]
Going to remove the onboarding bubble and just show the CTA to get to the `/setup` page with a light progress indicator (1/3).
