### ISSUE TITLE
support same-origin iframe network/console recording

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3934]
[https://discordapp.com/channels/1026884757667188757/1052857946318589993](https://discordapp.com/channels/1026884757667188757/1052857946318589993)

**Comment by weizman** [comment]
🎉 https://github.com/highlight/highlight/issues/3934#issuecomment-1446996567

**Comment by Vadman97** [comment]
Hey @weizman , thanks for your pointers thus far - I've started taking a look at this today. I understand that I should change the monkeypatching we do in our client to use `window` which SNOW will then propagate to iframes, but I'm also seeing that SNOW is restricting the normal behavior of iframes in our app. Is there a way to have SNOW help with monkeypatching in iframes without interfering with normal iframe functionality?

Here's a changeset for what I've done so far: https://github.com/highlight/highlight/pull/5562

![image](https://github.com/highlight/highlight/assets/1351531/818c1347-841f-4867-a871-3ad8342b9bd4)

**Comment by weizman** [comment]
Hi @Vadman97 , thanks for reaching out. I'll have a look asap. How would I locally reproduce this? Is it a demo app in #5562? Or a test?

**Comment by weizman** [comment]
To answer your question, snow most important rule is to not interfere with normal functionality of the program in general and iframes specifically whatsoever. If this had happened, it is an unknown bug to me and will be fixed immediately.

**Comment by weizman** [comment]
Hi @Vadman97, thanks for reaching out. 

I'd love to help out and have a look, this does seem weird. 

Can I get a detailed description of how to reproduce this? What is exactly the app that Snow messes up with? How do I build/find it?

I went on https://frontend-pr-5562.onrender.com/ , https://highlight-landing-fe33x8wf2-highlight-run.vercel.app/ and also cloned and built the frontend on branch `vadim/iframe-dev-tools-recording` but was not able to find a state where Snow is being called.

And to answer your question, snow most important rule is to not interfere with normal functionality of the program in general and iframes specifically whatsoever. If this had happened, it is an unknown bug to me and will be fixed immediately.
