### ISSUE TITLE
Documentation for troubleshooting sourcemap errors

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3951]
Provide some guidance about what the difference sourcemap errors mean so people can more effectively troubleshoot issues. This documentation should probably live in our [sourcemap docs](https://www.highlight.io/docs/error-monitoring/sourcemaps). We should also add a link to "learn more" and access the docs from the sourcemap error popup on stacktraces.

**Comment by Vadman97** [comment]
an example from intercom today - let's see if there is anything to document out of troubleshooting this one https://app.intercom.com/a/inbox/gm6369ty/inbox/shared/all/conversation/41249?view=List
