### ISSUE TITLE
Build Hex dashboard for analyzing channel performance

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3979]
Should include details on the following:

* How many new workspaces created?
* How many workspaces integrated (have at least 1 recorded session)?
* How many workspaces are active (someone viewed a session in the last X days)?
* How many workspaces are paying us?
  * How much MRR/ARR has it created?

**Comment by ccschmitz** [comment]
I think we have this now with the work @Vadman97 has been doing to build dashboards in Hex. @highlight/jay just let me know if there is anything else you'd like me to follow up on here!
