### ISSUE TITLE
Add details about app version mismatch on sourcemap errors

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3981]
Some customers are running into issues with sourcemaps being applied because they are uploading sourcemaps with an app version but it doesn't match the version they are passing in the client.

See this Slack thread for more context: [https://highlightcorp.slack.com/archives/C04E4LAE7AQ/p1673477054802739?thread_ts=1673470634.224099&cid=C04E4LAE7AQ](https://highlightcorp.slack.com/archives/C04E4LAE7AQ/p1673477054802739?thread_ts=1673470634.224099&cid=C04E4LAE7AQ)

**Comment by ccschmitz** [comment]
@deltaepsilon here is another one related to UI for showing issues applying sourcemaps on errors. Maybe not relevant anymore, but going to pass your way to triage and see if it makes sense to look at as part of the sourcemap work.
