### ISSUE TITLE
snooze should be a submenu

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3983]
It currently replaces the menu content to get to the snooze menu, but we want to make it a sub-menu.

**Comment by ccschmitz** [comment]
@jay-khatri I see you moved this to "cancelled" - did you actually want to close this?

**Comment by jay-khatri** [comment]
Sorry, i just didn't understand the issue when I was triaging; my bad. Is this already done?

**Comment by Vadman97** [comment]
converting cancelled status to closed issue
