### ISSUE TITLE
Support error / log reporting in Ruby via new Ruby SDK

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3999]
Issue to track adding a Ruby / Rails sdk for error monitoring & logging!

**Comment by et** [comment]
We should add support for Rails as well. It's unlikely anyone would use with just Ruby alone.

**Comment by sec0ndhand** [comment]
I’m super interested in this.  We are moving from sentry.  @et do you need any help?  Is there anything I can do to support the addition of ruby/rails?

**Comment by et** [comment]
Hey @sec0ndhand - @mayberryzane is taking this is on. He did an initial demo on this last week and it's looking really good! We should have this ready pretty soon.

**Comment by sec0ndhand** [comment]
That's great! You guys are awesome.  I'm happy to help out if needed.

**Comment by mayberryzane** [comment]
Hi @sec0ndhand, just confirming I'll have this ready this week, will keep you posted!
