### ISSUE TITLE
Create alerts for logs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4009]

**Comment by julian-highlight** [comment]
Current design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6105%3A318502&t=fEdWJspKqSHAFNTu-11

**Comment by julian-highlight** [comment]
I'll update you @aptlin as soon as this design enters a final stage. Probably will be done by tomorrow!
