### ISSUE TITLE
Snoozing an error + submitting an issue, should give me feedback

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4034]
Right now if I click the snooze option an select a time, there's no message/pop-p saying "you've snoozed this error for 10 days" or whatever. Can we do that?

![image.png](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/2020a8fa-163a-4fd8-bf29-eb47a224f47a/0c74edf6-766d-47fe-a418-db5ce7862a41)

**Comment by jay-khatri** [comment]
@ccschmitz also added "submitting an issue" here. The button for that modal also has no loading state.

**Comment by ccschmitz** [comment]
@jay-khatri there should be a message when an issue is created. We have logic in place for it.

https://github.com/highlight/highlight/blob/e64175b73bede6b71e43fb6d27f4a86bf13ee19e/frontend/src/components/NewIssueModal/NewIssueModal.tsx#L158

Just click tested and it seems to work.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/308182/216609030-665efb55-5b8d-4140-b092-1ef4776a91f9.png">

**Comment by jay-khatri** [comment]
I'm referring to a loading state. In prod, the updating of the state takes a few seconds, so I don't know what's going on for a while before that popup shows up.
