### ISSUE TITLE
scroll length on error tabs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4037]
the scroll length of the error UI (on any tab) should be the length of the tab's largest contents, plus some. cc @julian 

loom video:

[https://www.loom.com/share/b576b74c22cc4eac8e9e7135219d26bd](https://www.loom.com/share/b576b74c22cc4eac8e9e7135219d26bd)

**Comment by jay-khatri** [comment]
@ccschmitz is this done?

**Comment by ccschmitz** [comment]
@jay-khatri yeah, I think it's all set now!
