### ISSUE TITLE
Sourcemap styling isn't accurate

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4048]
- top padding isn't accurate:

![image.png](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/49164f04-46e7-4e95-b1a9-8ffe0c297339/d930f5ac-0242-432a-a1e0-26232e2e5f28)

- "Sourcemal" is a typo: 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/20292680/228747952-a4760b62-b937-4cab-9532-857537bcfd6d.png">

- Spacing between content and "metadata" button is not enough?
<img width="499" alt="image" src="https://user-images.githubusercontent.com/20292680/228747952-a4760b62-b937-4cab-9532-857537bcfd6d.png">

[Badge - Screen Designs (Figma)](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=3614%3A145849&t=hOMKADsClqBagxTf-11)

**Comment by Vadman97** [comment]
https://www.loom.com/share/02d1080b97c447a8874ced5421f93c96

error group with broken sourcemap settings modal:
https://app.highlight.io/898/errors/FKEDWUo1JddVw1JFAQF6hXbc2e0F?page=1

**Comment by et** [comment]
Fixed via #5096
