### ISSUE TITLE
Add GitHub authentication for Login

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4054]
Adding Github authentication can afford us:
- [x] linking source in a customer's repo from stack traces and showing additional code context for backend errors.
- [x] #5565 
- [x] #6004

**Comment by ccschmitz** [comment]
Didn't get to this in the q1 2023 work around auth/onboarding. Keeping in the backlog for future reference though.

**Comment by ccschmitz** [comment]
@et here is that issue we had for connecting a GitHub account to enhance stack traces. I'll move it to the Q2 errors epic, but feel free to move/revise/archive as you see fit!
