### ISSUE TITLE
New Project "Demo Experience"

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4062]
for a new project, we want to:

* throw in a session / error (or maybe multiple?) so that folks can click around on a session or error before even integrating. This happens in place of the demo workspace.
* convert the existing onboarding bubble into a progress bar in the navbar

**Comment by ccschmitz** [comment]
I think we're all set on this for now. We can revisit if the demo sessions/errors we are showing aren't working well for new customers.

**Comment by ccschmitz** [comment]
We want to allow users to go straight to demo account after creating an account (bypass onboarding screens). Should add a CTA on the marketing site to view the demo account.

**Comment by ccschmitz** [comment]
After talking through this more, we feel it would be best to come up with a script that can be run to reset the demo account to a fixed-ish state that will ensure the data is fresh and is a good representation of a real-world project that showcases usage of different SDKs. We also talked about creating a separate deployment of Highlight that can be run independently somewhere like demo.highlight.io.

@Vadman97 @jay-khatri I can start working on this script to populate our databases (Postgres, Clickhouse, OpenSearch, and Influx) but want to make sure we are aligned here. Do you think this is the approach we want to take?

**Comment by jay-khatri** [comment]
I think a good first version is to use our landing page project. I agree that it would be more valuable to have specific projects for each framework long term. 

I think a good first project is getting the demo project working for not authenticated users? That way we can link it in our landing page and throughout the app.

After that we can think about whitelisting multiple projects, setting up test data,etc..

What do you think?

**Comment by Vadman97** [comment]
Would we want to start with the ability to make a project public, or at least hard-code one project to be public (the landing page project)? That way we can start linking it throughout our docs.
