### ISSUE TITLE
Simple Integration Rate Perf

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4065]
What is the percent of customers that go from sign in → integration for:

* all accounts
* accounts w/ gmail addresses (or not company addresses)
* accounts w/ real company addresses
* for the web dev simplified customers

**Comment by ccschmitz** [comment]
@highlight/jay do you feel like you have visibility into this now, or is there still work to do on dashboards for you to see what you're looking for? I think the Mixpanel + Hex dashboards we have now give us a pretty good view of how people are getting through this. Might be worth adding more tracking on `/setup` to understand that flow a little better, but that's different than what we have here.

I'm going to close for now, but feel free to reopen if you want to revisit.
