### ISSUE TITLE
Fix display of backend stack traces

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4084]
We had a regression in how we display stack traces for backend code. I think we undid the work of [https://linear.app/highlight/issue/HIG-1397/prettify-backend-stack-traces](https://linear.app/highlight/issue/HIG-1397/prettify-backend-stack-traces) in the new error UI. We probably want to parse the data for an error like [https://app.highlight.io/1/errors/qL37XrxEb0fTxcpNu6ebFsa3uxHM](https://app.highlight.io/1/errors/qL37XrxEb0fTxcpNu6ebFsa3uxHM) and display each line in the trace separately.

**Comment by et** [comment]
Stacktraces look good now. Feel free to open a new ticket if there's still an issue.
