### ISSUE TITLE
Update logs schema to match OTEL spec

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4087]
Per chat w/ Zane + Vadim, let's update the logs schema to match [OTEL spec](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter#logs-1) with top level fields for project id and secure session id.

For things that we aren't using now (e.g. trace id), set a default of 0.

**Comment by Vadman97** [comment]
done in #3606
