### ISSUE TITLE
Filter usability is incredibly frustrating

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4093]
Two example of filtering being quite frustrating for our customers.

1) "Filter usability is incredibly frustrating. "

For example, when entering more than one parameter to filter by (ex: URL contains X, Y, ...), editing from already entered data (ex: editing an existing URL query that you want to change because you made a typo), etc. -> this also is annoying because you can't use the arrow keys to highlight the list and press space to select/unselect. But more importantly, when you enter a new item and press enter it just closes the filter and doesn't actually add the item.

Link to discord: https://discord.com/channels/1026884757667188757/1052834249868324895/1068966214682018023

2) Here is my other problem, I face, so when I select filter types, I hit this bug where I can't click on things like "is between" or "is not between", I have to type it then click my enter key

https://user-images.githubusercontent.com/20292680/217410335-8f66d040-5f54-4449-a567-7abd02526784.mov

Link to discord: https://discord.com/channels/1026884757667188757/1052834219522523178/1072698410106372136

**Comment by jay-khatri** [comment]
@julian-highlight do you mind taking a closer look at what's happening here?

**Comment by julian-highlight** [comment]
I think the issue here is that already created filters are hard to edit? That's most probably because the filter section isn't an input, and therefor you need to use the mouse to select the part you want to edit? 

@jay-khatri

**Comment by jay-khatri** [comment]
Sorta related, but there's a state where text doesn't wrap.

https://app.highlight.io/1/sessions/qcGa5W8BSIcSgE5fF1DTngmN5lez?query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C30+days&ts=16.216
