### ISSUE TITLE
Search URL params aren't consistent

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4095]
URL is very long / complicated and doesn't fully represent the session (ex: if I click on top users to view all their sessions, that is not a sharable URL, if I search for identifier = abc, and then click on that user's session, when I share the link the search is not there).

from discord: https://discord.com/channels/1026884757667188757/1052834249868324895/1068966443519049770

**Comment by jay-khatri** [comment]
Curious if this is specific to the home page, or if there's something broken beyond that. @ccschmitz if you don't mind taking a gander.

**Comment by ccschmitz** [comment]
@jay-khatri I don't think it's specific to homepage. It's happening anywhere we try to link to the session page and pass `user_properties`.
