### ISSUE TITLE
"Top Users" deep link doesn't work.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4098]
"When I click one of our top users in the dashboard, I'm sent to a list of everyone's completed sessions – not their's."

**Comment by jay-khatri** [comment]
Can confirm that this doesn't work.

**Comment by ccschmitz** [comment]
@jay-khatri this should be resolved by https://github.com/orgs/highlight/projects/2/views/20?pane=issue&itemId=19248036.
