### ISSUE TITLE
withHighlightConfig crashed on next.config.mjs

### ISSUE THREAD

**Issue by thibaultleouay** [highlight/highlight#4117]
When I upgrade to @highlight/next to the latest version it crashes 

Here's my setup

next.config.mjs
``` 
// eslint-disable-next-line @typescript-eslint/no-var-requires
import { withHighlightConfig } from "@highlight-run/next";
import { withAxiom } from 'next-axiom';

// @ts-check

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
  swcMinify: true,

  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.cloudfront.net',
      },
    ],
  },
};

export default withHighlightConfig(withAxiom(config));
```

Package.json
``` 
    "@highlight-run/next": "2.0.0",
```

Error 
```
ReferenceError: module is not defined in ES module scope
    at file:////..../node_modules/.pnpm/@highlight-run+sourcemap-uploader@0.4.1/node_modules/@highlight-run/sourcemap-uploader/dist/index.mjs:176:24
```

**Comment by Vadman97** [comment]
Hey @thibaultleouay , @mayberryzane is working on this and has some insight into what's causing this. It looks like the sourcemap-uploader index.ts [references `module`](https://github.com/highlight/highlight/blob/main/sourcemap-uploader/src/index.ts#L205-L207) which is not defined.

We should have a fix released for this shortly, likely tomorrow!

**Comment by Vadman97** [comment]
@thibaultleouay , new npm package version just published: https://www.npmjs.com/package/@highlight-run/next/v/2.0.1

please let us know if that resolves the issue for you!

**Comment by thibaultleouay** [comment]
@Vadman97  that was fast, it's working 🚀
