### ISSUE TITLE
Help w/ some design inspiration

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4122]
Yo @julian-highlight, do you mind helping w/ a few visuals for the home page? In particular, I need some for the following headings:

* A cohesive view of your entire stack. (Subtext: A natural pairing between your errors, session replay, logs and more. Understand the “what”, “why” and “how” of your full-stack web application)
    * For this one, maybe a few product screenshots? Errors, Logs and Sessions and some way to show that they're interwoven? Or some sort of nice visual showing cohesion?
* Integrations with your favorite tools. (Subtext: connect your favorite issue tracker, support tool, or even analytics software and we’ll give you a way to push and pull data in the right places.)
    * For this one, we just need a new variant similar to [this](https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=3862%3A27344&t=lr6wcndbvLV1qxrn-11) with a bunch of the integrations that we currently have. Namely:
        * Zapier, Mixpanel, Discord, Slack, Linear, Height, Intercom, Vercel, Clickup

https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=3862%3A27344&t=lr6wcndbvLV1qxrn-11

**Comment by julian-highlight** [comment]
This is done! @jay-khatri

**Comment by jay-khatri** [comment]
marking as done!
