### ISSUE TITLE
Add padding to scrolling containers

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#4138]
From @julian-highlight:

> Unsure where to put this, but we should defo add a margin to the bottom, so scrolling containers don't stop at the last item! In the designs I've used a 48px bottom margin!

**Comment by ccschmitz** [comment]
@julian-highlight what do you mean by "scrolling containers" here? Is it the search results list?

**Comment by julian-highlight** [comment]
No, the bigger container for all the error's content. It ends with the last item as seen in the screenshot below:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/114743131/216631347-5513fbb6-5cb8-45e2-a45d-3013ba99b3fb.png">
@ccschmitz

**Comment by julian-highlight** [comment]
@ccschmitz I've noticed it only works for empty stacktraces. As soon as it's showing multiple stacks it's not having any bottom padding 
Example: https://app.highlight.io/1/errors/j2EBmTHK0VD84SP8K0Jme0Z01I19?page=1

**Comment by ccschmitz** [comment]
@julian-highlight here is what I see when I load that page:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/308182/216686084-3b053e1f-f4a7-4546-919c-9f4970f1ae24.png">

I do see that if you toggle the bottom stack trace section open it drops down and touches the bottom of the window, but you can still scroll down further.

**Comment by julian-highlight** [comment]
@ccschmitz weird. I've checked if it's the cache for me, and reloaded. Now I can't scroll at all anymore. Maybe because I'm using a smaller window size?
![image](https://user-images.githubusercontent.com/114743131/216952488-5c73d988-d3de-4d58-bbc2-6d575b1d9615.png)

**Comment by ccschmitz** [comment]
@julian-highlight very weird... Mind screensharing and showing me what's happening on your end when we chat today?

**Comment by ccschmitz** [comment]
@julian-highlight I just put up a fix for the scrolling (#4153) because I saw a ticket filed for it. That's my bad.

**Comment by ccschmitz** [comment]
Reviewed with @julian-highlight this morning. I think we're all set here now.
