### ISSUE TITLE
can't scroll with new errors ui

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4150]
**Describe the bug**
with the new errors ui center panel, when the stacktrace is tall, i am not able to see the bottom of it as there is no scroll.

**To Reproduce**
[go error with long stacktrace](https://app.highlight.io/1/errors/xmoGkCCxZtXHQERwQ6XWKu83svrz?page=1)

**Screenshots**
![Screenshot 2023-02-04 at 4 39 53 PM](https://user-images.githubusercontent.com/1351531/216795596-48e4176b-0285-4d04-a199-c0b78430bc28.png)

**Comment by ccschmitz** [comment]
I think there's more to look at here as the scrollbar is not contained inside the elevated panel now.

**Comment by ccschmitz** [comment]
This should be resolved now.
