### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by et** [highlight/highlight#4159]
We need to validate that we can query with any log attribute. We suspect that we'll have to use a materialized view/column when the dataset is large enough.

With the follow data:

```sql
INSERT INTO logs (Timestamp, ProjectId, Body, LogAttributes) VALUES (now(), 1, 'body', {'user_id':'3'});
INSERT INTO logs (Timestamp, ProjectId, Body, LogAttributes) VALUES (now(), 2, 'body', {'user_id':'1'});
INSERT INTO logs (Timestamp, ProjectId, Body, LogAttributes) VALUES (now(), 1, 'body', {'workspace_id':'3'});
INSERT INTO logs (Timestamp, ProjectId, Body, LogAttributes) VALUES (now(), 2, 'body', {'workspace_id':'1'});
```

Notice how `user_id` and `workspace_id` are used by two different projects.

We can query like this just fine:

```sql
SELECT * FROM logs WHERE ProjectId = 1 AND LogAttributes['user_id'] = '3'
````

but it's unclear if this is scalable when the data is very large. 

We should:

* Create a test db on prod
* Write a script that massively inserts many different key/value pairs for multiple projects (some of the keys should be the same)
* Ensure that our query is still fast

**Comment by Vadman97** [comment]
since addressing the performance should be as easy as creating a [map keys/values index](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#available-types-of-indices), i think it makes sense to wait for this to become a problem with real data, rather than spending time scripting to fill the database now.

my impression was that [materialized views](https://clickhouse.com/docs/en/sql-reference/statements/create/view/) are useful for bulk aggregating data. do you think we will need them for querying logs?

**Comment by et** [comment]
@Vadman97 - we do have an [index](https://github.com/highlight/highlight/blame/main/backend/clickhouse/migrations/000001_create_logs_table.up.sql#L19-L20) on the map already. 

I wrote up an analysis in #4173. Feel free to run any queries on the `benchmarks` database in prod! Would love an extra set of eyes!

It'll take some time for us to hit scaling issues before we gain adoption and some of this is dependent on how we bill (#4166) i.e. is my benchmarking data too big for a given project.

Long term though, I do think we should invest time into generating materialized columns as it'll make queries a lot faster.

**Comment by Vadman97** [comment]
sweet, thanks for the detailed analysis @et, it will certainly come in handy (probably really soon given we're going to be writing a lot to clickhouse :) )! cool that adding the materialized view is easy and comes with a convenient optimize command to fill it.
