### ISSUE TITLE
Improve client recording options (whitelist GraphQL requests and support cookie recording)

### ISSUE THREAD

**Issue by aptlin** [highlight/highlight#4169]
From https://feedback.highlight.run/feature-requests/p/whitelist-graphql-requests:

"bodyKeysToRecord isn't sufficient for GraphQL requests since everything is under one field or an array of responses. Maybe we'd be able to supply a function. If keys work recursively, please ignore this!"

cc @Vadman97

**Comment by Vadman97** [comment]
> by default we do not record the cookie header for security reasons, but you could change this by editing the H.init options to include a networkRecording.networkHeadersToRedact list and omit cookie.

we should also provide an option to set specific cookies from headers to be included in the recording
