### ISSUE TITLE
add "greater than" for the filter type for length

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4189]
**Is your feature request related to a problem? Please describe.**
I like to view sessions after an X time vs in between with the max length going up to 60min 🙂 

**Describe the solution you'd like**
Especially for projects with really long sessions, having a `greater than` filter on length makes a lot of sense

**Comment by wwzeng1** [comment]
Hey! Sorry about the spam from Sweep. Your repository maxed out the token limit for our app. Sorry about that, we're looking into a fix and appreciate you trying out Sweep.

**Comment by Vadman97** [comment]
no worries @wwzeng1 :) let me know if we can help with additional testing! unfortunately all meaningful work happens in the monorepo, so we don't have any smaller repos to test with.
