### ISSUE TITLE
Player / timeline stuttering and UX issues [janky]

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4208]
**Describe the bug**
- sometimes during playback, the player will skip backwards a substantial amount of time.
- other times, the player will stutter during playback where the time indicator freezes/jumps.
- we should limit the absolute speed of the timeline bar regardless of the speed of the player; meaning that even if I set the speed to 8x, if its a very short session, the bar should only go across at some max pixel/second rate.

**Potential cause**
- Inactivity period on chunk boundary (common case) collision with the seeking logic.

**To Reproduce**
playback a long session, especially notable around inactivity periods.

**Related**
- #3768

**Comment by jay-khatri** [comment]
@Vadman97 added another bullet point and edited the title

**Comment by aptlin** [comment]
Another example of this (from [this discussion](https://highlightcorp.slack.com/archives/C01FF1KK3UG/p1676990825301539)):
https://app.highlight.io/51/sessions/KTyOIy9x106ZK64uerpeUfTKTNXq

**Comment by Vadman97** [comment]
long and buggy https://app.highlight.io/1/sessions/JLRlitSEsKVin0gvpUHRDyfWxnKh?query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C30%20days
