### ISSUE TITLE
Load more results for logs page

### ISSUE THREAD

**Issue by et** [highlight/highlight#4211]
When we hit N number of logs, load the next N number of logs.

**Comment by et** [comment]
We'll need to add cursor pagination. In order to do this, we need to add a new UUID column to ensure [stable pagination](https://morningcoffee.io/stable-pagination.html). 

I did a spike on this and confirmed that cursor pagination does indeed work correctly with clickhouse with this strategy:

![image](https://user-images.githubusercontent.com/58678/220434697-a668fb31-ae92-4818-91b8-af351bcc3741.png)

**Comment by laojianzi** [comment]
@et Thank you for sharing, this looks great :+1:
