### ISSUE TITLE
UpdateAdminAboutYouDetails overrides referral

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4270]
the about you page should not override referral from other places. since we first set `referral` thru the workspace setup flow, and then also collect it from the about you flow, the about you could change between the two.

**Comment by Vadman97** [comment]
another question @ccschmitz : how could a user have a free-form value for the `admin.referral` field? i see a non-url value for at least one person

**Comment by Vadman97** [comment]
should we tackle this by removing the about you `referral` update code path?

**Comment by ccschmitz** [comment]
@Vadman97 do you think we are good to remove this now? I'm actually not up to speed anymore on how all the tracking logic works these days. Happy to handle the cleanup if you're sure it won't mess up reporting.

**Comment by ccschmitz** [comment]
Reviewed these code paths with @Vadman97. Believe we are good to go here 👍
