### ISSUE TITLE
get rid of yellow tag on all pages

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4311]
Can we remove the yellow tag on the top of all pages, but also make sure the top padding is the same across all pages as well (once we remove it).
<img width="591" alt="image" src="https://user-images.githubusercontent.com/20292680/219518997-1a539cd3-0b87-4ca1-99fc-a2bc3eee3131.png">

**Comment by triki97** [comment]
https://user-images.githubusercontent.com/14045533/220821675-e2709e47-3f1a-42d5-8200-1bf58b1e0202.mov

Ive made changes in a branch for this but dont have write permissions. Removing these and running locally looks good but the pattern still exists in other places not sure if that matters to you guys
