### ISSUE TITLE
Better UX of switching between the `Inspect element` and commenting modes

### ISSUE THREAD

**Issue by aptlin** [highlight/highlight#4339]
At the moment our UI does not show the option to switch between `Inspect element` and commenting modes in session view. Some customers press the `D` shortcut that turns on the `Inspect element` mode by accident.

**DoD**

We want to have the corresponding option in session settings

---

There are 3 modes a user can be in:

* normal
* comment
* inspect

```[tasklist]
### Requirements
- [ ] Opening comments panel switches you to comment mode
- [ ] Hotkeys for switching between modes
- [ ] Make it obvious in the UI what mode someone is in
- [ ] Make sure CTA to connect Slack is present in empty state
```

**Comment by ccschmitz** [comment]
@julian-highlight maybe we can think about hiding the comment icons that are overlayed on the replay canvas as part of this 🤔

**Comment by ccschmitz** [comment]
@julian-highlight love it! I think something with a cursor icon would be good for inspect mode since that is what we see in the devtools.

<img width="308" alt="Screenshot 2023-05-17 at 11 15 02 AM" src="https://github.com/highlight/highlight/assets/308182/a1fcac3b-b91f-44a2-891b-30ff859a2972">

Comment icon LGTM. Not sure what to use for default mode 🤔 - maybe a video icon or something?

**Comment by julian-highlight** [comment]
Created the dev-tool icon! @ccschmitz 
For default I'm also uncertain, but most apps are just using a regular cursor. A video icon could be misleading from my point of view! 
![image](https://github.com/highlight/highlight/assets/114743131/f160df1f-aca5-41e7-a4df-d9eca2162876)

**Comment by ccschmitz** [comment]
@jay-khatri what should happen when someone has the comments panel open with inspect mode enabled?

**Comment by julian-highlight** [comment]
Yo @ccschmitz , can we make inspect mode be the default here? If the comment mode were the default we would need to show threads on the right panel.
