### ISSUE TITLE
Run benchmarking on production clickhouse service

### ISSUE THREAD

**Issue by et** [highlight/highlight#4340]
We did this in #4173 and there were some important queries that got sluggish. But that was for a development service. Clickhouse said that a lot of these slow queries will be fixed with production service that we now have.

**Comment by laojianzi** [comment]
I suggest adding some OFFSET testing. I had a bad experience with large OFFSETs (e.g. OFFSET 1 million) in ClickHouse.

**Comment by et** [comment]
Hey @laojianzi 👋 

The only use case I can see for `OFFSET` is for pagination. We plan to use cursor pagination (see https://github.com/highlight/highlight/issues/4211#issuecomment-1438956206) which should avoid the performance hit incurred using `OFFSET`.

**Comment by et** [comment]
Our prod db is at the point that we can use that for benchmarking new read queries.
