### ISSUE TITLE
ignore error groups by regex

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4389]
Can you provide a way to ignore errors by regex? For example: I want to ignore all errors that contain `Error: Route did not complete loading and not have to worry about each individual path (Error: Route did not complete loading: /home)`

would be useful to have the same behavior as the error ignoring button but matching on regex

**Comment by jay-khatri** [comment]
@Vadman97 mind linking the discord discussion so we can follow up when this is done?

**Comment by jay-khatri** [comment]
closing in favor of #4457
