### ISSUE TITLE
network requests are delayed in live mode, leading to confused network request recording onboarding

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4402]
live mode network request data is delayed in live mode until someone refreshes tab

**Comment by jay-khatri** [comment]
I think the solution here is to not allow the user to open the devtools panel in live mode. and when hovering over the toggle for the devtools, saying something like "devtools are disabled in live mode". 

wdyt

cc @aptlin @julian-highlight

**Comment by julian-highlight** [comment]
@jay-khatri I've created this view once, which doesn't allow devtools in live mode. 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=5407%3A242453&t=fEdWJspKqSHAFNTu-11
