### ISSUE TITLE
Clean up invite email

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#4442]
Existing email could use some love.

![Image](https://user-images.githubusercontent.com/308182/222226571-8d84e9d6-336a-44da-8470-fc6695ef2c04.png)

**Comment by ccschmitz** [comment]
@julian-highlight @jay-khatri just created this one. Thought we might want to clean this up to improve first impressions for invited users.

**Comment by julian-highlight** [comment]
Could we use this template here? 
https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=2904%3A9323&t=SmfwAy4XWiZnHkKg-11

@ccschmitz

**Comment by ccschmitz** [comment]
@julian-highlight yeah, I think the only difference would be that we would say "[user] invited you to join [workspace]" and update the CTA to "Join Workspace" or something. Thanks for pointing out this template!

**Comment by SpennyNDaJets** [comment]
Added a new email template in SendGrid here: [admin_invite_dark](https://mc.sendgrid.com/dynamic-templates/d-bca4f9a932ef418a923cbd2d90d2790b/version/9aaf01bf-4cf0-480d-8caa-70ee940611ca/editor)

<img width="1364" alt="Screenshot 2023-05-24 at 1 13 07 PM" src="https://github.com/highlight/highlight/assets/17744174/a72bc1ce-f123-4f77-9541-8aa1ba730352">
