### ISSUE TITLE
Add new filters/fields to network requests

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4456]
- filtering based on request status and type. 
- show request latency in network request panel

```
Add a section to the network request details that gives the user "latency" or how long the network request took to resolve.
discord convo to follow up w/: https://discord.com/channels/1026884757667188757/1076574340939788420/1076579008969441400

```
Please react to show interest and comment w/ any thoughts/questions/suggestions.

**Comment by aaronmaxcarver** [comment]
Hey @julian-highlight - @jay-khatri and I have a couple design questions for you. Here's a loom - https://www.loom.com/share/5ae5f95776a14900bc7f7279baa1281a

- how can we allow users to clear filters for multi-select?

- with 2 different filters and multi-select, what to show on the button's face?
e.g. here
![Screenshot 2023-03-15 at 6 10 28 PM](https://user-images.githubusercontent.com/59704103/225463890-da7e2889-3539-445b-8c6a-12aeaa74f04a.png)

**Comment by julian-highlight** [comment]
Thanks @aaronmaxcarver for collecting these thoughts! 
We can easily add a button inside the menu to delete filters! Will serve you with designs for that asap! 

To combat the other issue we have 2 options: 
1. Have a filters dropdown that acts as a hub for filters. The button itself could use 'X filters' as its copy whenever filters are applied. This will probably the easiest fix to the problem.
2. Commit to a full line of space for filters, where individual filters are visualized. This might be relevant if we plan to extend the list of filters soon! 
e.g. stripe: 
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/114743131/225642125-fa7d45c7-c568-4cf9-862a-785df5687ddf.png">
