### ISSUE TITLE
Ignore error groups by regex

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4457]
Currently, errors sent to highlight cannot be excluded.
For example, we may want to exclude all errors containing `admin not found` as expected.
<img width="1115" alt="Screenshot 2023-03-15 at 11 58 33 AM" src="https://user-images.githubusercontent.com/1351531/225414838-1c6b3d28-4505-4658-9242-85894a4c2cc9.png">

We have a [project error settings page](https://app.highlight.io/1/settings/errors) that allows configuring error changes, but we should allow a regex exclusion here to filter them out.
<img width="716" alt="Screenshot 2023-03-15 at 11 59 04 AM" src="https://user-images.githubusercontent.com/1351531/225414970-b265c51c-a35c-4e76-b10d-d449d1855724.png">

1. Add a postgres `project` table `error_filter` regex column, which can be nil.
2. Add a private-graph operations to get and set the `error_filter` value.
3. Update `PublicResolver.ProcessBackendPayloadImpl` to use the `error_filter` to decide if errors should be ignored. Frontend errors go thru a different codepath in `PublicResolver.ProcessPayload`.
5. Build the frontend `/<project>/settings/errors` UI to edit / update the error pattern

**Comment by Vadman97** [comment]
cc @deltaepsilon

**Comment by Vadman97** [comment]
fixed in #4389
