### ISSUE TITLE
Support for searching issues when creating them

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4460]
Support for searching over a list of issues before creating one in the UI. This allows the user to associate existing issues with an error. As part of this, we'll have to support a `search` operation on issues, but also some way to update an existing issue with the highlight error URL (add a comment, etc..)

Please react to show interest and comment w/ any thoughts/questions/suggestions.

**Comment by Vadman97** [comment]
Support searching existing issues within our issue integrations to link a highlight error with an existing issue.
https://www.loom.com/share/f44ef1f4f85e4c91abf135630d56baed

**Comment by jemiluv8** [comment]
@Vadman97, can I get assigned?

**Comment by jemiluv8** [comment]
This has been my take on the issue so far. Open to comments and suggestions

### Introduced a switch for issue "mode"
<img width="407" alt="Screenshot 2024-02-09 at 4 07 55 PM" src="https://github.com/highlight/highlight/assets/119384208/12fc48be-271c-4c15-947d-0a1db1edcbdc">

### View for linking issue
<img width="381" alt="Screenshot 2024-02-09 at 4 08 05 PM" src="https://github.com/highlight/highlight/assets/119384208/6701ddbe-b566-474a-89ed-0465fe1552da">

<img width="411" alt="Screenshot 2024-02-09 at 4 22 18 PM" src="https://github.com/highlight/highlight/assets/119384208/deb00825-69cd-43c8-9e8f-b8959eb797a9">

**Comment by Rutik7066** [comment]
Hi @jemiluv8 is your work completed. If not I would like work on this issue.

**Comment by jemiluv8** [comment]
@Rutik7066, I am still working on it. 
Check the draft Pr for any updates.

**Comment by jemiluv8** [comment]
Ok @Rutik7066.
