### ISSUE TITLE
Privacy SDK Improvements

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4461]
## Add a way to obfuscate all text, but "opt-in" to not obfuscating specific elements
Strict privacy mode should support the option to "not obfuscate" specific parts of the dom. This approach is better than requiring a customer maintain all the places they want to obfuscate, and its much more safer PII-wise.

## Only obfuscate Input, not Text

A user wants to be able to obfuscate all input, but not all text on the dom.
https://discord.com/channels/1026884757667188757/1068307010979889262/1068322987901726841

## Add an auto-obfuscate mode

From @GerryWilko (have heard this from other users as well):

> Are there any plans to add an auto privacy filter? Similar to SmartLook and HotJar where they try to determine which information is sensitive? Its not perfect those systems but we can patch the areas which are incorrectly not obfuscated. Highlight’s approach of adding classes to every element is very heavy on our side to patch and means that mistakes in PII data are not auto obfuscated at all.

> To be clear here what it appears HotJar (and the like) does here is try to detect PII (looks for things that look like names, emails, credits cards etc.) and auto obfuscates these items. Could Highlight look at this as part of this issue?

Please react (👍, 👎) to show interest and comment w/ any thoughts/questions/suggestions.

Things to consider:

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/5948
- [ ] https://github.com/highlight/highlight/issues/6188
- [ ] https://github.com/highlight/highlight/issues/6189
```

**Comment by GerryWilko** [comment]
Are there any plans to add an auto privacy filter? Similar to SmartLook and HotJar where they try to determine which information is sensitive? Its not perfect those systems but we can patch the areas which are incorrectly not obfuscated. Highlight’s approach of adding classes to every element is very heavy on our side to patch and means that mistakes in PII data are not auto obfuscated at all.

To be clear here what it appears HotJar (and the like) does here is try to detect PII (looks for things that look like names, emails, credits cards etc.) and auto obfuscates these items. Could Highlight look at this as part of this issue?

**Comment by jay-khatri** [comment]
@GerryWilko , updated the description to include your comment. Will keep updates on the scope of this here. @et assigned you for sometime this quarter.

**Comment by jay-khatri** [comment]
More feedback from customers (taken from [here](https://www.notion.so/runhighlight/rando-things-for-q3-eccb4b875ea04e4689dc3b5f9521769a?pvs=4)): 
<img width="801" alt="image" src="https://github.com/highlight/highlight/assets/20292680/4083597b-db53-42b2-a758-4a96efc8a766">
