### ISSUE TITLE
User Management Improvements

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4477]
- [x] #4706
- [x] #4707
- [x] https://github.com/highlight/highlight/issues/4442
- [x] https://github.com/highlight/highlight/issues/5113
- [x] #5395
- [x] #5481

**Comment by Vadman97** [comment]
![Kapture 2023-03-02 at 16 32 29](https://user-images.githubusercontent.com/1351531/222601332-65a694c8-6e72-40db-8a62-b1a1d17af77a.gif)

**Comment by ccschmitz** [comment]
@jay-khatri sure thing!

**Comment by ccschmitz** [comment]
@deltaepsilon talked w/ @jay-khatri and agree this would be a good one to pass your way! Let me know what questions you have or feel free to setup time for us to dig into it together.

**Comment by deltaepsilon** [comment]
I'll take a crack at it and let you know @ccschmitz

**Comment by Vadman97** [comment]
feedback from #4238 - would be nice to show pending invites when we invite someone
