### ISSUE TITLE
Session feed search results bleed over to error feed results.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4493]
If I switch between the session and error feed on a brand new account, the search results from sessions bleeds over to errors. For some reason, this seems to only happen for newer accounts? But overall, we shouldn't share search filters across the two feeds.

https://www.notion.so/runhighlight/search-feed-bug-2680b58e02874bc488d3ef6b5777e924?pvs=4

**Comment by jay-khatri** [comment]
@aptlin i figure you're familar with this given the router changes. Mind taking a look this upcoming week?

**Comment by Vadman97** [comment]
fixed in #5018
