### ISSUE TITLE
Attribute hubspot contacts with ads

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4553]
Right now, we don't have any lead / ad attribution in hubspot, although we do have it pulling in basic ad data:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/20292680/224188925-3b7c03f1-004f-48db-ba8c-429d2e8af8cb.png">

We should:
- install the hubspot snippet on the main app.highlight.io site
- somehow identify users so that attribution works

From [this](https://knowledge.hubspot.com/reports/data-in-hubspot-ads-doesnt-match-external-ad-networks) it seems like this isn't too easy given that we create contacts in our backend. 

Open questions: 
- should we be creating contacts on the frontend?
- if so, how does that affect all of our other hubspot logic?
- if not, can we pass the attribution data to our backend logic?

**Comment by Vadman97** [comment]
resolved in #5079
