### ISSUE TITLE
"Goto" button should only navigate to the correct timestamp, not open the right panel.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4556]
"Goto" button should only navigate to the correct timestamp, not open the right panel.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/20292680/224411611-46d3da3d-8b54-4de4-b6e7-33192ca712c2.png">

**Comment by aaronmaxcarver** [comment]
Is this opened or closed?
