### ISSUE TITLE
[ui bug] Alignment issues in the error state switch

### ISSUE THREAD

**Issue by aptlin** [highlight/highlight#4557]
![Screenshot 2023-03-10 at 4 20 31 PM](https://user-images.githubusercontent.com/17913919/224430575-4af763c1-15f8-413a-a5f6-1f07240019e9.jpg)
![Screenshot 2023-03-10 at 4 21 20 PM](https://user-images.githubusercontent.com/17913919/224430725-b16f1dd9-cbea-4d86-8996-a60ae6689a65.jpg)

**Comment by d29107d** [comment]
@aptlin 
Hi, I am new here, can I take this issue?

**Comment by et** [comment]
This was fixed in #4696.
