### ISSUE TITLE
Linking from log -> error doesn't work

### ISSUE THREAD

**Issue by et** [highlight/highlight#4572]
![Kapture 2023-03-13 at 12 26 44](https://user-images.githubusercontent.com/58678/224795818-52e2d288-df78-4e60-b0cf-51f0b42722f2.gif)

Not sure what's going on. On some rare occurrences, I can get it to work, but most times it doesn't.

`GetErrorObjectForLog` is returning `null` so that's definitely the root of the issue ([example](https://app.highlight.io/1/errors/logs/MjAyMy0wMy0xM1QxODoyODowNy4zNTI5NDYyMzhaLGI5NWQxODliLWQyNDgtNGZhNC1hNTI3LWQ1MTIwYTc2OWJmMg==)). 

AFAIK - every error should have a log, correct? If that's the case, can we add some type of check to confirm that?

**Comment by jay-khatri** [comment]
@Vadman97, as an addition to this, if I click "related error" on an error that actually works, there's a random screen flash before I"m actually directed to the error (we should also not render the left panel for the error feed when the redirect happens)
