### ISSUE TITLE
Replace session/error datepicker with relative time picker

### ISSUE THREAD

**Issue by et** [highlight/highlight#4582]
We added a relative datetime picker in #4245 to our ui library. It's being used in the logs page (#4274) and on the new command bar (#4371).

We should add it to the session and error pages (which can be found at https://app.highlight.io/sessions and https://app.highlight.io/errors).

To run the ui library:
* `cd packages/ui`
* `yarn dev`
* Visit http://localhost:6006
* Click DatePicker -> PreviousDateRangePicker

The above DatePicker should replace the datepicker rendered when clicking on "30 days" below:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20292680/236875926-53fb39db-1b43-422a-8351-ddb7b888f071.png">

Feature request submitted via [discord](https://github.com/highlight/highlight/issues/4582)

**Comment by manogna7** [comment]
Hello, can I work on this issue if it's still open?

**Comment by et** [comment]
Hey @manogna7 👋 
By all means, go for it!

**Comment by et** [comment]
@manogna7 - if you pick this up, you can ignore the part about recognizing the retention period. That would make this work entirely frontend which should be easier to work on. Feel free to hop into [discord](https://discord.gg/yxaXEAqgwN) if you get stuck.

**Comment by manogna7** [comment]
Hey @et,
Got it, and I just joined the channel. I started getting familiar with the environment and I'll let you know if something pops up. Thank you for assigning it to me.

**Comment by jay-khatri** [comment]
@betty-alagwu assigning you!

**Comment by betty-alagwu** [comment]
Thank you @jay-khatri , I'll be raising a first PR for feedback before EOD.

**Comment by Vadman97** [comment]
done in #5285
