### ISSUE TITLE
Changes to Billing

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4584]
- [x] put "current plan" and "upgrade plan" on the same page
- [x] add logging to billing
- [x] separate retention for each product (logs, errors, sessions)
- [x] make changes to highlight.io/pricing to reflect the above - ticketed in https://github.com/highlight/highlight/issues/5274
- [x] add card to sessions / errors / logs feeds when results are omitted due to overage - ticketed in https://github.com/highlight/highlight/issues/5195

**Comment by Vadman97** [comment]
is this tracked by something else @mayberryzane ?

**Comment by mayberryzane** [comment]
@Vadman97 there were one or two other tickets tracking other parts of the billing changes, but I think the task items here are unique to this ticket
