### ISSUE TITLE
"apply as filter" works w/ `level:info`, but not `level:error`

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4600]
Not sure why, but `level:error` seems to be broken, but `level:info` isn't. 
https://www.loom.com/share/b4735b3f830443b292c37585644430e2

Not sure who to assign to, but cc @ccschmitz @et .

**Comment by et** [comment]
This is likely because of 

https://github.com/highlight/highlight/issues/4464

You can assign this to me.

**Comment by jay-khatri** [comment]
sounds good, thanks.
