### ISSUE TITLE
Tooltip Discrepencies

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4601]
https://www.loom.com/share/fe54864cd79147e88bc1fc5f62e99c7b

**Comment by ccschmitz** [comment]
@SpennyNDaJets here is another one that might be an easy starter task. Would you mind taking a look sometime?

**Comment by jay-khatri** [comment]
@SpennyNDaJets , what component is this? Should it be our default tooltip instead (with a white background)?
<img width="482" alt="image" src="https://github.com/highlight/highlight/assets/20292680/5da70057-9210-4abc-a072-76aa87de5dc0">


cc @julian-highlight
