### ISSUE TITLE
Logs Design Polish

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#4606]
Here's a list of tasks regarding general polish for logs we want to get done for the upcoming launch.

**All Designs are visible here**: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6105%3A259822
**Loom here**: https://www.loom.com/share/09beb4bca38045c98183d03ef9e4d79e

- [x] Add divider underneath the histogram
- [x] put log count + exact timeframe above the histogram
- [x] use low emphasis button style for time picker
- [x] use dropdown style for histogram data (https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6505%3A275888&t=9EwHp5YRzd6RW8ec-11)
- [x] push related error/session buttons to the left (+ add divider)
- [x] update loading states to use styles from 'Loading #1' & 'Loading #2' https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6517%3A472385&t=9EwHp5YRzd6RW8ec-11
- [x] Center align callouts for empty states/errors
- [x] Update empty state callout

CC @jay-khatri @ccschmitz @et 

edits (by @jay-khatri):
- deleted gray scale histogram

**Comment by jay-khatri** [comment]
Just talked to @julian-highlight. Some notes here. 

>  Greyscale histogram on default
Hold off on this for now.

**Comment by jay-khatri** [comment]
Hover state of this button should be `cursor: pointer`:
<img width="120" alt="image" src="https://user-images.githubusercontent.com/20292680/226053374-dc55f9dd-d564-4881-8bef-b3479a8829fa.png">
