### ISSUE TITLE
Design support on Competitor pages

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4619]
Hey @julian-highlight , would appreciate some support on cleaning this up. Here's the figma;
https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=4812-38292&t=YW6yL0A5Wak1fmTX-11

As a V1, we can use the content from here:
https://www.notion.so/runhighlight/Fullstory-vs-Highlight-782d12cafca54cebbe7fdf4e98eae8f9?pvs=4

**Comment by julian-highlight** [comment]
Created a proper table here: https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=4812-38292&t=r2YwaUFcHitrYaP9-11

Let me know what you think @jay-khatri

**Comment by julian-highlight** [comment]
Another iteration here: https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=4812-38292&t=r2YwaUFcHitrYaP9-11 @jay-khatri

**Comment by jay-khatri** [comment]
marking as done! thanks @julian-highlight
