### ISSUE TITLE
with discord set up, visiting `/alerts` shows slack must be integrated

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4620]
https://discord.com/channels/1026884757667188757/1085987396497178754

i believe our `/alerts` page shows a `You should set up slack` message if slack is not set up, even if discord is.
we should show a prompt only if neither is set up, and we should update the prompt to be more generic to include both discord and slack as possible integrations.

cc @jay-khatri

**Comment by Vadman97** [comment]
> maybe it should be better to select the integration type and then try to request for linking

from nils

**Comment by jay-khatri** [comment]
> I just tried to create a new Track Events and didn't select a Tack Properties so it just loading without any error response

Should also add an error state to the track events alerts if no track property is selected ^

**Comment by jay-khatri** [comment]
Removing the prompt completely makes sense to me.
