### ISSUE TITLE
Hubspot Changes

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4627]
- add number of session/error views for each contact
- add number of session/error views for each company
- call `hubspot.identify` in the frontend whenever someone visits app.highlight.io; that way the #pricing-views and #logs-views channels work.
- confirm that contact <> company associations are working: I'm seeing that for most companies, contacts and are associated, but I don't see companies with multiple contacts; are we appending contacts for n>1 correctly?

**Comment by Vadman97** [comment]
done in #5079 
will follow up EOW about the state (we can decide if we want to create admin after a delay, in case hubspot never does)
