### ISSUE TITLE
[Logs link] Hostname looks incorrect + missing cursor in URL

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4633]
https://app.highlight.io/1/errors/1bX1y5STkHvSNuLeXPvEPY9W4mvV?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C30%20days

show logs button should also add a time range

**Comment by et** [comment]
In the case that we don't have a cursor, we should prefill the time range (based off the error instance) so the logs page doesn't default to Last 15 minutes
