### ISSUE TITLE
Import highlight.io docs into monorepo

### ISSUE THREAD

**Issue by et** [highlight/highlight#4634]
Per our chatting today, it would be better to import [highlight.io](https://github.com/highlight/highlight.io) docs into this repositiory so everything is in our one monorepo.

**Comment by ccschmitz** [comment]
Yeah, I know we've talked about this. Would definitely be nice to import instead of pulling from the API!

**Comment by ccschmitz** [comment]
This is resolved now with https://github.com/highlight/highlight/pull/4789.
