### ISSUE TITLE
Add an "all session logs" button to the devtools logs area @julian-highlight @et

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4635]
@julian-highlight in this view, we want to add a button called "All Session Logs" which links to the log viewer and queries all logs for that given session.

Given that this is a button not related to filters, I think it makes sense to have a new row underneath the console tab for filters (on the left) and the log button on the right?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/20292680/225972360-902f65af-d877-4aa6-9398-deb7d621cabf.png">

**Comment by julian-highlight** [comment]
Here's an option for it! https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6701-622550&t=ULnx2m8g7WYSrewo-11

Unsure if it's better to do this now though, as filters on console level are still pretty simplistic
