### ISSUE TITLE
Pagination loading state isn't clear

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4637]
Small design critique.

Coming across this loading state, it isn't clear that this is loading a new page below by current scroll position. It almost seems like the log that's below this is loading in some way or another. Can we insert the loading state below all the logs? And add a spinner that gives the user some realtime feedback?

<img width="487" alt="image" src="https://user-images.githubusercontent.com/20292680/225984059-a67c5fcb-bbf9-4cc3-ba38-74103367033b.png">

**Comment by julian-highlight** [comment]
Here's the design reference for how it's intended to be: 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=6517%3A473101&t=0jLkz48G9XFCSLUe-11

@jay-khatri
