### ISSUE TITLE
Fix broken link on dashboards list

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4642]
~~Clean up calls to `upsertDashboardMutation` and make sure alerts aren't created for metrics.~~

We decided there isn't anything to update here except fixing a bug we noticed when clicking around the dashboards page mentioned in https://github.com/highlight/highlight/issues/4642#issuecomment-1583265615.

**Comment by ccschmitz** [comment]
@jay-khatri @Vadman97 looks like the only two auto created dashboards left are Web Vitals, Request Metrics, and Home. Home is hidden and used as the "Analytics" page. Do you guys feel strongly about removing the two default dashboard + the analytics page? Is there anything you want to keep?

I think we already did a pass at cleaning up a number of the default dashboards. This isn't as bad as I think it might have been when we initially created this ticket.

**Comment by ccschmitz** [comment]
One other issue here is when you click on the "View" button on the dashboard list it seems to be broken. Took me to `https://localhost:3000/1/dashboards/dashboards/2`. Maybe an issue with the router upgrade.
