### ISSUE TITLE
Updates to the trial banner

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4643]
Proposing that we:
- remove the "Fill this out" banner to extend your trial (this makes our onboarding funnel unnecessarily complicated)
- instead, just report on how many sessions (and add errors) the user has used up

![Image](https://user-images.githubusercontent.com/20292680/226211645-e9d69949-5f3c-40dd-b829-fd81ea300943.png)

**Comment by ccschmitz** [comment]
@highlight/jay I'm going to close this since I don't think it's relevant anymore since we revamped this banner recently. Feel free to reopen and let me know if you think otherwise. Thanks!
