### ISSUE TITLE
UI changes for live mode

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4644]
Right now, it isn't clear what a user should be experiencing in "live mode" and I suspect this affects the onboarding experience. Proposing two things:

- When a session is ongoing, we should update the copy here to denote that the session is live and may be missing some data. Maybe something like:
    - Title: Live session might be missing {resource} data
    - Subtitle: This session is ongoing and may be missing some data until it successfully completes.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/20292680/226248910-88e154d3-e80f-4b67-ac59-61484048a904.png">
(Also, I'm not sure why there is a a new line between the two sentences in the above image; can we get rid of that?)

- When the user clicks "enter live mode", they shouldn't be allowed to open the devtools.

**Comment by ccschmitz** [comment]
@Vadman97 is this still something you're thinking about, or should I just tackle this as part of the q2 session work?

**Comment by Vadman97** [comment]
completed in @ccschmitz 's q2 live mode improvements
