### ISSUE TITLE
Render a list of error instances to give the user a "peak" of the instances related to an error.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4656]
View error instances on a group with a table list and search.

**Comment by jay-khatri** [comment]
Initial thoughts here: 
https://www.loom.com/share/98b70c89f14b46c687b0136171d30313

**Comment by julian-highlight** [comment]
@jay-khatri Good call! I also feel like having a list is the ideal solution here. Is there a need for filtering instances? This way we could actually add functionality here. I can also think of a split view for instances that shows you
1. a list of instances (like described in your loom), and
2. a preview of a selected instance to quickly find the instance of your needs, without having to jump back and forth! 

For that idea I'll need to do some design exercises to see if it actually works though!

**Comment by julian-highlight** [comment]
We can probably close this one don't we? @et @jay-khatri
