### ISSUE TITLE
Fetching log keys/values is too slow in the 30 day view

### ISSUE THREAD

**Issue by et** [highlight/highlight#4662]
We have to attach a time frame when fetching log keys/values (see #4661 and #4507). It would be great if we didn't have to do this.

Clickhouse has a table engine called `SummingMergeTree` which looks like it's meant for aggregations:
https://altinity.com/blog/clickhouse-materialized-views-illuminated-part-1

**Comment by jay-khatri** [comment]
@et should we close this?

**Comment by et** [comment]
No. It's still broken.

**Comment by Vadman97** [comment]
completed as part of @mayberryzane 's log perf improvements
