### ISSUE TITLE
Codespaces improvements

### ISSUE THREAD

**Issue by aaronmaxcarver** [highlight/highlight#4671]
**Is your feature request related to a problem? Please describe.**

-The monorepo will run in codespaces, but the setup could be improved

**Describe the solution you'd like**

*Contributors*
- How to share (a link to) the highlight codespaces setup?
- Onboarding contributors with Highlight billing

*Docker*
- How to automatically build docker containers and cache them
  - run docker command(s) in 'onCreateCommand'? 
- prevent the need for running a Full Rebuild after entering codespaces the first time to get the docker daemon running 
- Build a dockerfile for dev container that runs ‘yarn’

**Describe alternatives you've considered**
-n/a

**Additional context**
-n/a

**Comment by aaronmaxcarver** [comment]
Onboarding / billing
- Discount or free plan for OSS projects? 
- Is there a way to give credit to individuals, e.g. $50 vs. adding each contributor as a member?

**Comment by aaronmaxcarver** [comment]
- Set the default setting to run Prettier on save
  - By default a user's VS Code settings, such as 'run prettier on save', don't apply within the codespace
- Probably some other useful settings to set up as defaults

**Comment by Vadman97** [comment]
closing this as we've optimized the dev workflow in #4820 and the prod workflow in #4993
