### ISSUE TITLE
Remove misc/NoOp directory called `ee` 

### ISSUE THREAD

**Issue by benmorehouse** [highlight/highlight#4687]
**Describe the bug**
Seems like this is an empty No-operation directory: https://github.com/highlight/highlight/tree/main/ee

**To Reproduce**

1. Go to '~/highlight/ee'
2. See empty dir and singular text file

**Expected behavior**
This just seems like some clean-up! :)

**Screenshots**

**Additional context**

**Comment by jay-khatri** [comment]
This was intentional for internal purposes. Closing this issue.
