### ISSUE TITLE
support development with node.js 18

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4695]

**Comment by manogna7** [comment]
I encountered openssl error while setting up package ui locally. I have tried running `export NODE_OPTIONS=--openssl-legacy-provider` but that did not fix the issue. 

![image](https://user-images.githubusercontent.com/44017221/227777011-1819e56b-7ad2-48a3-b03e-8fb9360464d6.png)

**Comment by Vadman97** [comment]
fixed in #4888
