### ISSUE TITLE
support webcam video element recording

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4704]
A `<video autoplay="" playsinline=""></video>` element does not get serialized because rrweb does not actually include the inline stream that is browser-side.

To support this, we would need to hook in to the video stream, bundle the video client or server side into a file, and update the DOM to be a `<video src=.../>` element.

This likely is related to #4517 as it would use a similar approach to efficiently serializing canvas elements.

cc @jay-khatri

**Comment by jay-khatri** [comment]
Is there a linked discord convo?
