### ISSUE TITLE
Pricing UI Updates

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4705]
Proposing some changes we want to make to the in-app pricing page. 
- [x] add "reach out to sales" CTA (in the case that a customer does a lot of traffic and wants to talk to us `mailto:sales@highlight.io`)
- [x] add logging to the pricing scheme
- [x] billing warning emails:
    - if 80% usage on any plan, show a banner + send email
    - if 100% usage on any plan, show a banner + send email
- [x] banner updates
    - banner should include sessions, logs, and error overage.
    - banner should link to the pricing page

stretch:
- only one plan that lets you set an upper bound for the amount you want to pay (for each product)
- consolidate all pricing info on a single page (no `upgrade-plan` and `current-plan`)
- consolidate this all on a new settings page? 😄 
- collect CC in onboarding flow

**Comment by jay-khatri** [comment]
@Vadman97 am I missing anything?

**Comment by Vadman97** [comment]
@jay-khatri should we consider optionally collecting a CC as part of the onboarding flow as well? that or making it a step for the free trial extension.

**Comment by jay-khatri** [comment]
> @jay-khatri should we consider optionally collecting a CC as part of the onboarding flow as well? that or making it a step for the free trial extension.

Sounds good. Will add to "stretch"

**Comment by jay-khatri** [comment]
Also, what are all the possible states someone can view here:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/20292680/228712706-54c4df16-831e-44f0-8651-79c840bcb195.png">

**Comment by jay-khatri** [comment]
Feedback from a recent conversion:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/20292680/228736480-e3f67029-3576-415d-89a3-42f350e75f81.png">

**Comment by jay-khatri** [comment]
This shoul dhave a link to the billing page:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/20292680/229251725-d2e98431-d67b-4329-8515-eff1972e6f9e.png">
