### ISSUE TITLE
Error and session UI share links are broken

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4710]
In short, publicly sharing sessions and errors don't work right now. Examples below:

- [x] #4726
- [x] #4727

**Comment by jay-khatri** [comment]
@ccschmitz , I think this is pretty related to #4062, given all the auth work. Maybe you can grab this first? (imo its pretty high priority and I see sessions quite often where a user can't view a public one).

**Comment by Vadman97** [comment]
fixed. outstanding UX issue tracked by https://github.com/highlight/highlight/issues/4522
