### ISSUE TITLE
Body searches can overmatch

### ISSUE THREAD

**Issue by et** [highlight/highlight#4713]
`message:"sessions that will be processed: [{193931244 1703} {193954172 1703} {193837800 238}]"`
![Screenshot 2023-03-27 at 2 51 15 PM](https://user-images.githubusercontent.com/58678/228063701-93ff1614-60a4-4a8d-8562-f2356787f7b9.png)

**Comment by et** [comment]
I believe there's also broken behavior when we have a `:` in the value (e.g. `code.filepath:"http://localhost:8080/dist/index.js"`) because we don't tokenize correctly.

**Comment by ccschmitz** [comment]
@et I can take this one. I think this logic is incorrect:

https://github.com/highlight/highlight/blob/1c62781756dbaff3a6317c374d9e82df2f06c2d8/frontend/src/pages/LogsPage/LogsTable/LogsTable.tsx#L368

**Comment by et** [comment]
@ccschmitz - I think there are issues with both the frontend and the backend. Let's leave this as a backend only issue.

**Comment by ccschmitz** [comment]
Not relevant with new SQL building logic introduced in #7309.
