### ISSUE TITLE
For links without a project, they link to the first project by default

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4735]
Something we noticed in James Quick stream.

For links without a project, (e.g. app.highlight.io/setup & app.highlight.io/alerts), we default to going to the first project that the user is in. Instead, can we default to the most recent project? We could do this by storing the most recent project in the Project Router, and reading from that variable when going to that link.

**Comment by ccschmitz** [comment]
@jay-khatri do you happen to recall which links weren't working? Wondering if https://github.com/highlight/highlight/commit/420975ec7442aa87b7423ca5d35f79c35c080488 resolves this.

**Comment by jay-khatri** [comment]
Yes. It was just the "Finish Setup" Cta in the center of the empty state for sessions and errors.
