### ISSUE TITLE
Verify that source and service_name have correct values

### ISSUE THREAD

**Issue by et** [highlight/highlight#4743]
Hey @Vadman97 - can we check to ensure these have correct values? 

<img width="615" alt="Screenshot 2023-03-28 at 8 39 02 PM" src="https://user-images.githubusercontent.com/58678/228412847-8f54a22a-7c7e-4baa-80e9-4caaddd05c75.png">

<img width="609" alt="Screenshot 2023-03-28 at 8 39 40 PM" src="https://user-images.githubusercontent.com/58678/228412849-67b65709-84f2-4cbc-9835-48ddfc96b340.png">

`frontend` for `source` is the only thing that makes sense to me. I'm not sure about the others.

For context: @jay-khatri wanted to add it to the [docs](https://www.highlight.io/docs/general/product-features/logging/log-search#Autoinjected-attributes) but unsure of what to put here.

```[tasklist]
### Tasks
- [ ] #5160
```

**Comment by Vadman97** [comment]
![Screenshot 2023-03-28 at 10 18 55 PM](https://user-images.githubusercontent.com/1351531/228433821-422a65f1-ffee-48cc-95e8-e2d7c6ed9936.png)

weird that we have logs with a `vercel` attribute even though the logs that have it set are from a totally different place (the /v1/vercel/logs route).

![Screenshot 2023-03-28 at 10 21 05 PM](https://user-images.githubusercontent.com/1351531/228434122-1aa1168f-894a-4162-83e9-fe0401090737.png)

looking into this

**Comment by et** [comment]
Hey @Vadman97 - looks like your changes covered source. What about service_name. Are the values correct?

**Comment by Vadman97** [comment]
Hey @et , `ServiceName` is using opentelemetry SDK values defaults. We should point to something like https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_service_name in the docs.

![Screenshot 2023-03-29 at 12 48 33 PM](https://user-images.githubusercontent.com/1351531/228651229-7b223c69-97c5-4b0f-a2d3-8af4ac491fff.png)

**Comment by et** [comment]
Re-opening per a discussion with @Vadman97 - `unknown_service` isn't a great user experience and we don't really want to reveal the notion of OTEL through our docs. The SDKs should be setting something here. At the very least, we should configure the backend to not write service name if it's coming in as `unknown_service`.

**Comment by jay-khatri** [comment]
A related thread about confusion around service name. I think its worth supporting these fields as first party SDK parameters at some point.

https://app.intercom.com/a/inbox/gm6369ty/inbox/conversation/41277

**Comment by jay-khatri** [comment]
@et this might be related to your service name work. Closing, assuming this isn't relevant given new tickets.
