### ISSUE TITLE
Add opt-in filtering for chrome-extension errors

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4744]
Frontend errors with stacktraces that have chrome extensions in the path should be filtered out, with a simple toggle on the project settings page (can use #4631 as a reference on where to make this change). 

By default, all projects should have this off and we should also add a doc that documents this as a project setting (over here: https://www.highlight.io/docs/general/product-features/error-monitoring/overview)

**Comment by d29107d** [comment]
@Vadman97 
I will take it.

**Comment by Vadman97** [comment]
Hey @d29107d , answering your questions from discord: 

- how to migrate the db field?
  - Schema changes to [model.go](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/model/model.go#L1) will be automigrated. New tables should be added to [Models](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/model/model.go#L133-L187). [Migrations happen automatically](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/model/model.go#L1268) in dev and in github action as part of our production deploy. I would also recommend a postgres cli (or using `docker compose exec postgres`) to validate schema in your local database.

- how to generate the graph?
  -  per the [Makefile](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/Makefile), `cd backend; make private-gen` for changes to [private schema.graphqls](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/private-graph/graph/schema.graphqls) and `cd backend; make public-gen` for changes to [public schema.graphqls](https://github.com/highlight/highlight/blob/83c412a0f3f28a13d6781593935dcee2f0e77403/backend/public-graph/graph/schema.graphqls#L4). 

![image](https://user-images.githubusercontent.com/1351531/228711390-131671fe-91e4-49a3-890d-0872c8468fd5.png)

- Is there a way to execute the script to finish the above?
That should be all you need!

**Comment by d29107d** [comment]
@Vadman97 
The highlight.io is public archive, what should I add a doc?
<img width="291" alt="image" src="https://user-images.githubusercontent.com/82889377/231104518-89643a9f-9784-4541-82c3-e9e92b1423c1.png">
