### ISSUE TITLE
Add 'End of list' and new 'Loading' callout, whenever users reach the end of the log list.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4754]
As discussed, with Julian, make some changes to the 'End of List' and 'Loading' states for the end of the log list.

**Comment by jay-khatri** [comment]
@julian-highlight , if you don't mind sharing designs when you have them.

**Comment by julian-highlight** [comment]
Yo @et, the designs are done! I don't see a reason to add any button here as clearing a query is always accessible on top! Therefor I kept it rather simple. 

The 'End of list' design is [here](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7024-283869&t=lJQepFu5xUH5GQbm-11). The loading state on the left of it! 
These callouts should not cover content, and rather act like a placeholder for loading/nonexistent content.

CC @jay-khatri
