### ISSUE TITLE
disable indexeddb for canvas enabled sessions

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4769]
in particular as with #4758, could it be that projects with large sessions cause an OOM?
we should audit the browser-memory implications of using the indexeddb preloading (when data is fetched before it is put into indexeddb, it is in memory)

**Comment by StephenHaney** [comment]
So far so good using the "no indexeddb" setting with my canvas recording. I don't notice any degradation in performance or extra loading time. Things like switching videos and scrubbing are actually much faster and more reliable.
