### ISSUE TITLE
Render backend logs in session viewer

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4779]
Now that we're piping the "source" of a log, a good next step is to actually render backend logs in the session viewer. I do think there's lots more cool things we can do to allow for fine-grained rendering of logs (put some ideas [here](https://github.com/highlight/highlight/issues/4692)), but a good first step is showing a new tab in the devtools.

- [x] #4786
- [ ] Rename the "Console" tab "Console Logs"
- [ ] Instead of "Related Logs" (see image below), call it "Show in Log Viewer", which should populate a search for the correct `source` and `session_secure_id`.

![Image](https://user-images.githubusercontent.com/20292680/228734001-82564eb6-e966-425b-a167-21a084806c2a.png)

**Comment by et** [comment]
I can handle the second two bullet points. I created an issue for the first one (#4786) as it requires more product/design requirements (cc @julian-highlight).

**Comment by jay-khatri** [comment]
Just commented there 👌 .
