### ISSUE TITLE
Fetching permalinked log is slow

### ISSUE THREAD

**Issue by et** [highlight/highlight#4858]
Loading a permalinked log took ~20s

https://app.datadoghq.com/apm/trace/345995380199087473?colorBy=service&env=none&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=9185997433895012019&spanViewType=metadata&timeHint=1680795903994.6238

**Comment by Vadman97** [comment]
completed as part of @mayberryzane 's log perf improvements
