### ISSUE TITLE
errors feed is populated with session queries

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4860]
in a production build of the app, visit the sessions feed, then visit the errors feed.
session filters will get carried over to the errors feed resulting in a broken search.
<img width="269" alt="Screenshot 2023-04-06 at 9 17 00 AM" src="https://user-images.githubusercontent.com/1351531/230437772-479a0df0-302f-424d-a345-2f9eee00cf66.png">

**Comment by jay-khatri** [comment]
i noticed this recently too. thanks @Vadman97.
