### ISSUE TITLE
"Console log" touchups / polish

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4870]
- [x] #4871
- [ ] #4872

**Comment by jay-khatri** [comment]
@julian-highlight , we'll need some support on #1 if you don't mind!

**Comment by julian-highlight** [comment]
Design [here](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=4451-205639&t=dnCWY9epGQJQ8INj-11) @et
