### ISSUE TITLE
Add position indicator in session logs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4872]
https://github.com/highlight/highlight/pull/6303 added a visual indicator for errors and network resources, and we'd like to add a similar indicator for console logs.

**Comment by ccschmitz** [comment]
Just updated the details of this issue. We actually want to implement a visual position indicator similar to what we did in https://github.com/highlight/highlight/pull/6303 for errors and network requests.

@julian-highlight I only see mocks for network requests and errors. Do we have anything for logs? Here's where I was looking: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9938-229817&mode=design&t=es9nkbs2QqAUw82P-11

**Comment by julian-highlight** [comment]
We decided to switch comment and inspect mode for now, just to simplify navigating into the threads-panel. @ccschmitz

**Comment by julian-highlight** [comment]
We should do the exact same thing for all tabs. Just a simple purple divider + lower the opacity of non-reached items!

**Comment by Min2who** [comment]
@jay-khatri @Vadman97 May i take this issue as the PR is inactivce for a month or so?

**Comment by rishi-raj-jain** [comment]
I'm not able to work on this, @Vadman97 please take a look at comments from @Min2who & @Rutik7066?

**Comment by Vadman97** [comment]
@Min2who or @Rutik7066 , feel free to work on this!

**Comment by Min2who** [comment]
@Vadman97 can yu assigned me this

**Comment by Bhavyajain21** [comment]
Is this still open? @Vadman97

**Comment by Bhavyajain21** [comment]
Can I be assigned?
