### ISSUE TITLE
Add a “goto” button on the console log viewer in the session player

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4877]
Like the network tab, we should also add a "goto" icon on the right part of every console log, and disable the existing clicking functionality of the logs.

**Comment by jay-khatri** [comment]
@julian-highlight advise on how this should look is appreciated. @et mentioned that given that console logs can span multiple lines, it might be weird to render the goto icon in the same way we do for network resources. Should we add another "column" of sorts so that there's some delineation?

**Comment by julian-highlight** [comment]
@et Let's do it like presented in the video! I've added another column to the design, as I didn't want to add a button to the log line component we use here. Also I've added dividers to make it easier to distinguish individual logs. 
https://user-images.githubusercontent.com/114743131/230899731-4162c948-81ea-4a1c-be36-df71066af83f.mov

[Design here
](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=4451-205639&t=dnCWY9epGQJQ8INj-11)
[Prototype here](https://www.figma.com/proto/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?page-id=40%3A3089&node-id=4451-205639&viewport=-2627%2C-3517%2C2.02&scaling=min-zoom&starting-point-node-id=4989%3A213411&show-proto-sidebar=1)
