### ISSUE TITLE
improve chrome extension filter name

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4890]
Hey @d29107d  it's not super clear here what the name of the setting means.

Could you please update the setting title from `Filter Browser Extension` to  `Filter out errors thrown by chrome extensions` and completely remove the "Chrome extension stackframes" label and tooltip (i.e. only show the toggle)?

![image](https://user-images.githubusercontent.com/1351531/230687265-deb0aa08-5933-49d8-8b55-d0041165d332.png)

**Comment by d29107d** [comment]
@Vadman97 ok

**Comment by jay-khatri** [comment]
@d29107d I've just update the description slightly. fyi.

**Comment by d29107d** [comment]
@Vadman97 @jay-khatri 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/82889377/230713105-8b497697-78e9-4b39-ae7f-e36a8ae35b6f.png">
My idea is that there may be other filters(i.e. Firefox or Safari) here in the future.

**Comment by jay-khatri** [comment]
That is true. Good point. For now, let's be more explicit, though.

**Comment by d29107d** [comment]
> That is true. Good point. For now, let's be more explicit, though.

👌

**Comment by d29107d** [comment]
@Vadman97 @jay-khatri 
<img width="872" alt="image" src="https://user-images.githubusercontent.com/82889377/231046212-f3dc289e-6ca3-415d-8038-3315249cd83d.png">
Does it like the above? If so, I will open a pr.
