### ISSUE TITLE
Support filtering errors and sessions that are ingested

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4892]
We should build a robust and generic way to filter sessions, errors, and logs from being recorded and counting against a customer's billing quota.

This will require thinking through a few parts:
* How can SDKs avoid sending information about sessions/errors/logs that will be dropped?
* What kinds of filters can be applied? ie. can errors be dropped by location, user identifier, event body, stacktrace?
* How can a customer diagnose when data is being filtered out?

**Comment by kengreeff** [comment]
Yes please! We only care about sessions where the user is logged in

**Comment by Vadman97** [comment]
now supported for paying customers!
