### ISSUE TITLE
Timeline cursor jumps forward and back

### ISSUE THREAD

**Issue by wvffle** [highlight/highlight#4916]
**Describe the bug**
When I try to play any of the recorded sessions, the timeline cursor jumps furiously forward and then goes back after some milliseconds.

**To Reproduce**

1. Go to a recorded session
2. Play the session

**Expected behavior**
The cursor should move smoothly

**Screenshots**

https://user-images.githubusercontent.com/13330620/231016474-bcbb341b-ffc2-4ccd-a264-619afd9e35c6.mp4

**Additional context**
- The affected browser is LibreWolf 111.0 which is based on Firefox 111.0 
- On chromium browser, it has simillar effect but only when skipping inactive part. Over there it seems more like a 'desired' spring animation than a bug but either way, it's not something I fancy.

**Comment by wvffle** [comment]
Dear github-actions bot,

The bug still remains. Please don't close it.

Thanks in advance!

**Comment by wvffle** [comment]
@Vadman97 could you reopen it? I was on vacation and I didn't have time to bump it.

**Comment by jay-khatri** [comment]
Related to https://github.com/highlight/highlight/issues/6178
