### ISSUE TITLE
Redesign Settings Page(s)

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4917]
Consolidate the user, project, and workspace settings pages per new figma designs.
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=2737%3A99360&t=1O7dgx4sCuXQPrUv-1

things to address: 
- [ ] fix the white flash when we redirect to the settings page. 
- [ ] support multiple projects in the left side bar
- [ ] don't render the top right nav items for the settings page (github, discord, settings icon, etc..)

**Comment by julian-highlight** [comment]
Updates on the Settings front @eightants 
https://www.loom.com/share/71dc85764d664a1bbc6cc9139961d7c5
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=2737-99360&t=50vTe5mzHuqEKfIX-11
