### ISSUE TITLE
Support downloading highlight sessions as videos

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4919]
Customers have asked for ways to download highlight sessions matching a filter to be able to edit these videos together (eg onboarding sessions of users) and share them.

**Comment by Vadman97** [comment]
@julian-highlight - we'd want a `download` button that is grayed out (with a tooltip explaining) for folks not on an annual commitment plan. 

<img width="1143" alt="Screenshot 2023-08-14 at 12 25 27 PM" src="https://github.com/highlight/highlight/assets/1351531/e5ec8925-ddec-4851-b498-7954bb34bc9e">

**Comment by julian-highlight** [comment]
Added a design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=208-10536&mode=design&t=rUlxOYHwRuttTCHc-11

To save space on top, this functionality is hidden behind the player-settings, especially bc it's just valid to use for annual plan users.
