### ISSUE TITLE
Using setup docs within app can be confusing

### ISSUE THREAD

**Issue by et** [highlight/highlight#4924]
`Grab your project ID from [app.highlight.io/setup](https://app.highlight.io/setup) and insert it in place of <YOUR_PROJECT_ID>.`

<img width="1507" alt="Screenshot 2023-04-11 at 9 33 36 AM" src="https://user-images.githubusercontent.com/58678/231214249-33b21d71-c505-413d-8d17-9981146ae94f.png">

I'm already on setup page so this feels confusing.

Furthermore, what is the point of saying `we recommend setting tracingOrigins and networkRecording` if the suggested script already has that set?

**Comment by Housi** [comment]
ok so whre I can find this effin ID
