### ISSUE TITLE
Next.js - Identifying users code snippet crashes the page

### ISSUE THREAD

**Issue by et** [highlight/highlight#4927]
Per the setup docs, I've added this code snippet:

```tsx

H.identify('jay@highlight.io', {
  id: 'very-secure-id',
  phone: '867-5309',
  bestFriend: 'jenny'
});
```

results in this error:

<img width="1157" alt="Screenshot 2023-04-11 at 9 55 01 AM" src="https://user-images.githubusercontent.com/58678/231219764-0c623b83-3bbd-46f5-abe5-8049e5feb7d0.png">

**Comment by et** [comment]
I think the issue is this: https://blog.sethcorker.com/question/how-to-solve-referenceerror-next-js-window-is-not-defined/

Not really sure of a good fix here.

**Comment by jay-khatri** [comment]
This is a very common Next.js issue, as by default, most of the logic in a component happens server side. There's an implication that a developer knows to put the `H.identify` call in a useEffect, but can't hurt to be clearer. Going to update the docs.
