### ISSUE TITLE
next.js sdk should export `H` object from `highlight.run`

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4933]
highlight-run/next already depends on highlight.run
in our next.js docs, we tell folks to import `H` in their next.js frontend from `highlight.run`, meaning that they need to depend on two highlight SDKs.
https://github.com/highlight/highlight/blob/main/highlight.io/pages/_app.tsx

the highlight-run/next sdk already depends on highlight.run so we should just reexport the object

**Comment by eightants** [comment]
After diving a little deeper with Vadim, it seems that exporting H from highlight/next is more difficult than expected. Since that means now we're importing highlight/next on the browser, the other dependencies (highlight/node) is throwing errors since OpenTelemetry uses node only functionality.

**Comment by vasco3** [comment]
I just ran into this issue when I updated to ` "@highlight-run/next": "^7.2.1",` 

doesn't work with either 
`import { H } from "@highlight-run/next/client";`  
or `import { H } from "highlight-run";`

**Comment by bloomfieldj** [comment]
> I just ran into this issue when I updated to ` "@highlight-run/next": "^7.2.1",` and "next": "^14.0.2"
> 
> doesn't work with either `import { H } from "@highlight-run/next/client";` or `import { H } from "highlight-run";`
> 
> Even removing the import causes the same error.

For now, I've found reverting to next@14.0.1 solves this for me.
