### ISSUE TITLE
Line between navbar + page content is too thick

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4955]
Small bug, but on the session/error feed, the line between the navbar and page content is very thick. I don't think this is the intention (cc @julian-highlight ).
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/20292680/231597463-35380709-71a2-453f-9297-955a4df85357.png">

**Comment by julian-highlight** [comment]
Yep, it should be as thick as all the other dividers!

**Comment by ccschmitz** [comment]
This was fixed recently!
