### ISSUE TITLE
Adjust log body tokenbf_v1 index

### ISSUE THREAD

**Issue by et** [highlight/highlight#4976]
See [docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#functions-support) on `hasTokenCaseInsensitive ` that insists that if we do case insensitive searches (which we do), we should be calling `lower` on our index, e.g.

```sql
INDEX idx_body lower(Body) TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 1
```

**Comment by Vadman97** [comment]
completed as part of @mayberryzane 's log perf improvements
