### ISSUE TITLE
Chris's DX Check

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#4989]
I set up Highlight w/ a CRA client and tRPC on the server. Here are some thoughts on how we could improve the setup process.

Here is a repo for the code I was using during the process: https://github.com/highlight/dx-check-trpc-react-chris

```[tasklist]
### Suggestions
- [ ] Copy suggests to replace `<YOUR_PROJECT_ID>`, but project ID is already set in the snippet
- [ ] Got the "STOP RIGHT THERE!" screen when trying to view a session in my new project
- [ ] "`tracingOrigins`" not highlighted as code in the heading of the backend monitoring docs
- [ ] We are inconsistent showing instructions for installing deps with npm, yarn, and pnpm - may want to always show all options
- [ ] Consider showing dependency installation instructions as separate code blocks so the copy buttons can be used
- [ ] "Initialize the Highlight JS SDK" section not that helpful - could we be more specific about which file to edit?
- [ ] "Initialize the Highlight JS SDK" has a code snippet where we don't inject the project ID for `YOUR_PROJECT_ID`
- [ ] "Add the tRPC Highlight integration." section assumes you are using Next.js - is there something more generic for error handling? I ended up needing to follow the Express.js docs.
- [ ] We make people call `init` and pass their project ID, do we need to pass it again to methods like `Handlers.errorHandler`, or could we somehow infer it?
- [ ] What is the `module.exports` example for Node logging? Doesn't seem like real-world code.
- [ ] Was able to get an error to Highlight, but only by calling `H.consumeError`. Was not able to get the middleware to intercept them (I tried setting it up in different places).
- [x] ~Wasn't able to get logs to work 😢~
- [ ] There is no Next.js backend setup guide (we should show https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js/overview as a `Next.js` option for backend integration docs)
- [ ] https://github.com/highlight/highlight/issues/5344
```

**Comment by jay-khatri** [comment]
> Got the "STOP RIGHT THERE!" screen when trying to view a session in my new project
What was this from?

**Comment by ccschmitz** [comment]
> What was this from?

@jay-khatri that was when I tried to view a session in the new project I created in the Highlight project. I think the problem is this logic:

https://github.com/highlight/highlight/blob/6d3f811eb6d3e627a28d8293f7a6cf20da85c2f5/frontend/src/pages/Player/PlayerHook/PlayerState.ts#L391

Instead of checking if `projectId !== 1` it should be weather the project is in the Highlight workspace. Not a big deal as it's just an internal issue.

**Comment by Vadman97** [comment]
> Wasn't able to get logs to work 😢

@ccschmitz were logs not working? i believe i can see logs for the project you routed the backend sdk to 

https://app.highlight.io/4868/logs?end_date=2023-04-20T22%3A54%3A55.301Z&query=%22Server%20running%22&start_date=2023-03-21T22%3A54%3A55.566Z

<img width="1784" alt="Screenshot 2023-04-20 at 3 55 22 PM" src="https://user-images.githubusercontent.com/1351531/233503675-e757508e-fd25-44bc-be81-506b7c0914c7.png">

**Comment by ccschmitz** [comment]
@Vadman97 I guess the did end up working 🤔 - for some reason I wasn't seeing them and the integration status checks were saying I wasn't fully integrated yet. Looking at the project again everything seems to be working. Maybe just a delay in processing logs or something?
