### ISSUE TITLE
Don't hide docs sub-menus in a dropdown

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5013]
Rather than hiding docs submenus in a dropdown (like below), we should put these in the actual left panel of the docs. Maybe we can do it in a similar way to supabase? (Click "getting started" on supabase.com/docs) 

<img width="340" alt="image" src="https://user-images.githubusercontent.com/20292680/232973848-4364f349-6270-4524-8464-596720ce92f9.png">

Tasks:

- [ ] Restructure the docs so that there is no "/general"
- [ ] Remove Top level nav UI
- [ ] Add Doc Title ("Home", "SDKs", "Getting Started") and add "Back" buttons on the sub menus ("Getting Started", "SDKs")

**Comment by jay-khatri** [comment]
@julian-highlight to play with a few ideas here.

**Comment by deltaepsilon** [comment]
I did some quick research, and most docs sites will do accordions. Only one stays open at a time, but you can click through them pretty easily.

The other option is to expose everything, all the time. You have to scroll more, but nothing is hidden.

**Comment by julian-highlight** [comment]
Thanks @deltaepsilon ! 

Yea I've seen both as well, and I personally always prefer more static designs, as they feel way more reliant in their usage. Stripe for example found a good compromise of having the functionality to collapse items, but by default shows them expanded. Generally I feel like our left panel is super cluttered still, which draws away a lot of attention of the user. 

Currently I'm prioritizing some product work, but this should defo be tackled!

**Comment by jay-khatri** [comment]
@julian-highlight , just a bump here on the design. No worries if you haven't worked on it yet.

**Comment by julian-highlight** [comment]
Yo just found some time to work on this! @jay-khatri @Crawron 
https://www.loom.com/share/cfb831f86ac4430ba3f93d768b1e7e6a
https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?type=design&node-id=5407-46678&t=RbUSUujpKO5vHBhW-11

**Comment by jay-khatri** [comment]
@julian-highlight looks great. This is a pretty goo starting point for @Crawron. We had some questions/thoughts which we added to the figma.

**Comment by jay-khatri** [comment]
Only reason is to make this change incrementally. I'm on the same page that they probably shouldn't be accordins long term.
