### ISSUE TITLE
Frontend rendering of errorboundary form data on errorInstance page

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5051]
instead of sending the error boundary `submit` feedback as a 'notification', we should attach it to the error boundary error object and add the feedback to the error slack alert

replace
<img width="373" alt="Screenshot 2023-04-20 at 1 40 00 PM" src="https://user-images.githubusercontent.com/1351531/233482705-94031e39-57f7-4a94-91da-49280cbcc48d.png">

with
<img width="996" alt="image" src="https://user-images.githubusercontent.com/1351531/233487938-7d317627-5bed-47f8-8c8c-eeb6db63f1b8.png">

**Comment by julian-highlight** [comment]
Updated the error designs! Feedback now lives on the user card! 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7649-293387&t=50vTe5mzHuqEKfIX-11

**Comment by julian-highlight** [comment]
Here's some more thoughts about how to implement this! https://www.loom.com/share/b7b377736c9a4bd5a43e5e83539ab8d6

CC @et @Vadman97

**Comment by julian-highlight** [comment]
Designs are done! 

https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7899-545926&t=8t8dkRTWYPH5z2gG-11

@et

**Comment by et** [comment]
Thanks @julian-highlight. Will close this ticket out and we can track in the parent ticket.
