### ISSUE TITLE
Design component docs

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5053]
Some inspiration:

* https://seek-oss.github.io/braid-design-system/
* https://mui.com/material-ui/getting-started/overview/
* https://chakra-ui.com/getting-started

**Comment by CatherineKiiru** [comment]
Hi @ccschmitz i'd like to work on this issue. Is it available?

**Comment by julian-highlight** [comment]
Lovely idea! Thanks @ccschmitz. This will most probably live in on our existing docs and therefor just needs content (+ a way to display components) right? 

Here's a few more inspirations: 
https://carbondesignsystem.com/components/accordion/usage/#live-demo
https://m3.material.io/components/bottom-sheets/overview

Github has it's own library on github: 
https://primer.style/view-components/components/beta/avatar
