### ISSUE TITLE
Any spotlight/highlight comparing with Sentry?

### ISSUE THREAD

**Issue by Kwangmy** [highlight/highlight#5090]
~

**Comment by Vadman97** [comment]
Hi @Kwangmy , apologies for the delay!

There's a few reasons why someone would use us over Sentry. First is that our session replay product is much more robust imo, though they are working quickly in that space: https://www.highlight.io/docs/general/product-features/session-replay/overview

Secondly, we have a logging product: https://www.highlight.io/docs/general/product-features/logging/overview

And lastly, we prefer to keep our product simple and very opinionated. Most of our customers are using common frameworks and we're specifically focused on web. Long term, we see ourselves going in the direction of Datadog, building out a metrics and tracing product over the next 6 months or so.
