### ISSUE TITLE
Update error/description callouts

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5100]
These need a design update: 

From chatting with @vadman97, this seems to be called the `ErrorState` component. cc @julian-highlight to work on designs.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/20292680/234050747-2aab708d-4964-478b-afea-b255f8a28b10.png">

_Originally posted by @jay-khatri in https://github.com/highlight/highlight/issues/4522#issuecomment-1520432975_

**Comment by jay-khatri** [comment]
Julian, once we're finished here, maybe @deltaepsilon can work on this?

**Comment by julian-highlight** [comment]
Created something that uses our callout component here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7506-286829&t=XTQJ90eGEdcqmEV5-11 @deltaepsilon 

Unsure if we want to show any navigation here or just hide it. Let me know what you think @jay-khatri 
![image](https://user-images.githubusercontent.com/114743131/234069860-0ef24907-3491-4490-944d-4ea8f6da1396.png)

**Comment by jay-khatri** [comment]
Sounds great. I think we just want to update the callout, not the navigation (there is already a lot of context around that). Fyi @julian-highlight @deltaepsilon
