### ISSUE TITLE
`urlBlocklist` not working as expected

### ISSUE THREAD

**Issue by deltaepsilon** [highlight/highlight#5104]
We need to confirm that `urlBlocklist` string matching supports subdomains.

![image](https://user-images.githubusercontent.com/878947/234086885-a695ec37-5649-4239-96f9-a5beb5187c18.png)

**Comment by deltaepsilon** [comment]
I'm failing to reproduce this bug. It worked as expected in my tests.

I'll follow up with Ulf.



![Image](https://github.com/highlight/highlight/assets/878947/88a4ca33-063b-4010-af6d-85c164158fa7)

**Comment by Vadman97** [comment]
Closing as stale. I believe we've confirmed that the block list is a substring match.
