### ISSUE TITLE
Association of ErrorBoundary "feedback" with its Error Instance in `client/` and infra

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5115]
- [x] Remove the `feedbackWidget` option from client. Note: this is different from the `<ErrorBoundary />` component.
- [ ] Remove the Session Feedback alert
- [ ] For the flow that handles session feedback alerts right now, look for an error instance that matches this session. If one exists, see if there's an Error Alert set up for the project. If one exists, notify the session feedback to that Error Alert's channel

**Comment by Vadman97** [comment]
Some context:
Currently, the `ErrorBoundary` renders a modal when an exception is raised. By the time this happens, the highlight `client` has already caught and reported the error to highlight. The modal then shows a 'feedback' dialog that a customer can fill out and 'submit'. Currently, the 'submit' will send 
```H.addSessionFeedback({
  verbatim,
  userName: name,
  userEmail: email,
  timestampOverride: reportDialogOpenTime.current,
})```
as a graphql request to `addSessionFeedback`, which in turn saves a feedback item (shown in notifications). Instead, we want to move this 'feedback' flow altogether, and associate the name, email, and text with the error instance that is processed as additional error instance metadata.

To do this, we need the [Error Boundary code](https://github.com/highlight/highlight/blob/ea4e17d85700e16813de4fc419292757b895b759/sdk/highlight-react/src/components/ErrorBoundary.tsx#L188-L212) to save the id of the error instance sent over, and then send the 'feedback' with that same error object ID so they can be associated together.

**Comment by jay-khatri** [comment]
As discussed w/ @et , we should also do a quick search to see if "session feedback" alerts are used, and remove it if they aren't.
