### ISSUE TITLE
Visualize Error Group Distributions

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5132]
We should do a bit more digging into what exactly is causing error noiseness. Creating a hex dashboard with some queries might be a good first step. Some ideas:

- Distribution of error groups with useful stacktraces, stacktraces somewhere, no stacktraces
- Distribution of error groups with:
    -  [more than x other error group(s) that has body similarity > y] where y = some sort of similarity score
- another idea: can we compare a few text. based matching algorithms on bodies to see if they have large differences in the number of errors generated? In particular, if there are algorithms that have very easy ways to fine-tune the sentitivity, this might be something we could add to the product long term.

**Comment by et** [comment]
Per #5312, I think we should advise folks to just make their source maps public. I don't think we'll get any additional signal from doing additional analysis.
