### ISSUE TITLE
add getting started docs for the java SDK

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5134]
something like https://www.highlight.io/docs/getting-started/backend-sdk/ruby/rails

1. start by replicating [the ruby directory](https://github.com/highlight/highlight/tree/main/docs-content/getting-started/4_backend-sdk/ruby) to a java one
2. update the [quickstart content](https://github.com/highlight/highlight/blob/e34fce885855820ff5b2ead2ea170d938d74166d/highlight.io/components/QuickstartContent/QuickstartContent.tsx#L42) tsx file
3. implement the quickstart content by replicating the [ruby directory](https://github.com/highlight/highlight/tree/e34fce885855820ff5b2ead2ea170d938d74166d/highlight.io/components/QuickstartContent/backend/ruby) to a java one

@NgLoader , do you think you could help with this please?

**Comment by NgLoader** [comment]
Yea

**Comment by NgLoader** [comment]
WIP
