### ISSUE TITLE
SR: Add draggable handle to session viewer (can't drag right now)

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5142]
It's not obvious that you can drag the devtools to be larger or smaller which is causing some confusion. We should make this more obvious.

**Comment by ccschmitz** [comment]
@julian-highlight do we have this in the mocks anywhere?

**Comment by julian-highlight** [comment]
Yep! We have it [here](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=5094-220779&t=8akAxlMeks6PHat2-11).

@ccschmitz
