### ISSUE TITLE
Add logging + error monitoring data to internal tool 

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5157]
On the `accounts/` page, it would be nice to have a graph of logging+error monitoring counts over time, similar to what we have for sessions: 
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/20292680/234969867-d654e332-1020-48da-84f7-3f60b6d20b23.png">

That way, we can also use this once hubspot is fully set up to track usage/engagement.

**Comment by Vadman97** [comment]
replaced with workspace-search.highlight.io
