### ISSUE TITLE
Default filter selected on session page does not work

### ISSUE THREAD

**Issue by eightants** [highlight/highlight#5164]
**Describe the bug**
When loading in a saved filter (likely from the last selected filter on a previous session, the filter name is populated, but the filters in the actual filter field are not applied. (As you can see, only Status is Completed is selected. ). 

Clicking on the list of filters and selecting the same saved filter again, or another saved filter, applies the filters properly. 

<img width="903" alt="Screenshot 2023-04-27 at 4 51 00 PM" src="https://user-images.githubusercontent.com/29858539/234987945-90df7713-697b-475e-87b9-41dc3b3fe3ae.png">

When switching between workspaces or projects, the name of the last set filter is applied as a default. However, this filter might not exist in the project itself, as seen below. 

<img width="903" alt="Screenshot 2023-04-27 at 4 51 16 PM" src="https://user-images.githubusercontent.com/29858539/234987996-b3a62106-2d3b-4207-8e6f-3b23111b952a.png">

**To Reproduce**

1. Go to Sessions
2. Select a saved filter
3. Close the page
4. Open a new tab and visit Sessions again

For the second part of the bug
1. Go to Sessions
2. Select a saved filter
3. Switch to a different project or workspace
4. Filter is selected, but doesn't exist in project

**Expected behavior**
Filter is applied as expected on load if a filter was saved from last session, with all the filters from the saved filter. Cached filters in localstorage should be tied to a project, so that filters that don't exist aren't loaded.

**Comment by jay-khatri** [comment]
Thanks @eightants. @mayberryzane to do you mind bucketing w/ your search filter changes?
