### ISSUE TITLE
Build a `winston` transport for our Node.js integration

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5185]
We should support `winston`, a common logging library for node. They have a concept of a `transport` which we can use for logs. (and possibly [errors](https://github.com/winstonjs/winston/blob/master/docs/transports.md#newrelic-transport), though we could also recommend that folks explicitly turn on or error monitoing).

A good starting point is here: 
https://github.com/winstonjs/winston/blob/f8320c1e3bb7cc3544b1385da92cc625e2b3b0ac/examples/custom-transport.js

**Comment by arda-bulut** [comment]
Building a separate package might not even be necessary for an MVP. Winston supports HTTP transporters as well. Here's an example of how it would be implemented with Datadog:

`const datadogTransport = new winston.transports.Http({
  host: 'http-intake.logs.datadoghq.eu',
  path: '/api/v2/logs?dd-api-key=${DATADOG_API_KEY}&ddsource=nodejs&service=${SERVICE_NAME}',
  ssl: false
});`

One concern with this would be reliability. Need to make sure that no requests are lost along the way. It occasionally happened with Datadog
