### ISSUE TITLE
add card to sessions / errors / logs feeds when results are omitted due to overage

### ISSUE THREAD

**Issue by mayberryzane** [highlight/highlight#5195]
If there's overage and sessions/errors/logs aren't recorded, we should notify the user by adding a card to the search results

**Comment by mayberryzane** [comment]
@julian-highlight would you be able to create a design for this? Thanks!

**Comment by julian-highlight** [comment]
Just for clarity... We need a design for:
- Logs (Banner in the log-search results)
- Errors (Banner in left panel search results)
- Sessions (Banner in left panel search results)
right?

**Comment by mayberryzane** [comment]
@julian-highlight 
Yes exactly, those 3 places. Thanks!

**Comment by julian-highlight** [comment]
Added all the designs to their specific page. Search panels for errors and session received a little component updated to show 'Content: Overage'. 

Designs here:
- [Error Overage](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7895-297484&t=8t8dkRTWYPH5z2gG-11)
- [Session Overage](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7896-380070&t=8t8dkRTWYPH5z2gG-11)
- [Log overage](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7896-381897&t=8t8dkRTWYPH5z2gG-11)

@mayberryzane
