### ISSUE TITLE
use new datepicker component in the error instance metrics

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5196]
@betty-alagwu , this would be a great next issue to tackle.

our error instances (ie https://app.highlight.io/1/errors/q4DA50IdRWsF6MfXJhd3tSvtfLJp/metrics) currently have a metrics page that has a date picker. this is currently using the old antd style of date picker.

we should upgrade this to the new [DatePicker](https://github.com/highlight/highlight/tree/main/packages/ui/src/components/DatePicker) component, allowing for date and time selection

<img width="1254" alt="Screenshot 2023-05-01 at 11 40 22 AM" src="https://user-images.githubusercontent.com/1351531/235508536-127d843e-4dff-4aa9-b350-9e92dbdc5934.png">

**Comment by betty-alagwu** [comment]
Hey @Vadman97 Thank you very much. On it
i'll ping you if i have any issue.

**Comment by Abhishek-90** [comment]
Is this available to work on?

**Comment by mayberryzane** [comment]
closed as fixed by #5213
