### ISSUE TITLE
Adjust the error grouping logic

### ISSUE THREAD

**Issue by et** [highlight/highlight#5229]
## Summary

We want to adjust our [error grouping logic](https://www.highlight.io/docs/general/product-features/error-monitoring/grouping-errors) to only consider the stacktrace when deciding whether to group. The reason for this is because errors are less likely to be grouped when considering the error message (aka error body, error event).

## Motivation

When viewing the errors page, it is overwhelming seeing so many error groups that it's very easy to drop off. This change should produce less error groups and make the errors page more usable.

### Variable injected error messages
https://github.com/highlight/highlight/blob/1432a782217a8f7426b4717260fd6db6d01e3a7d/backend/clickhouse/log_row.go#L31

![Screenshot 2023-05-04 at 11 43 52 AM](https://user-images.githubusercontent.com/58678/236285994-42e34c3c-b9e7-4fa6-af04-5f5294ca6ded.png)

These should all be grouped into one error group and the message should be the latest error instances's message (in this case `invalid project id fake-project-id`). 

### Go error wrapping

![Screenshot 2023-05-04 at 12 05 21 PM](https://user-images.githubusercontent.com/58678/236290721-a50dace1-9b2f-4ecd-b365-e3b44c4c9fc2.png)

In Go, it's fairly ubiquitous to use error wrapping. This is somewhat of a workaround for Go apps that don't have stacktraces. And while this doesn't apply to us (since our SDK produces one), it'll be hard to onboard new Go users that use error wrapping in their codebase if we don't group these better.

## What we will not do

We will not allow the user to change error grouping logic. This is tedious, prone to error, and requires manual updating on the user's part. 

### Add fingerprint column
* Add new indexed, nullable `fingerprint` column to `error_groups`
* Add new function called `Fingerprint(errorGroup ErrorGroup)` and `Fingerprint(errorObject ErrorObject)` that uses the existing logic of consider stacktrace + error message to produce as hash. The value should be written to the new `fingerprint` column.
* Backfill the existing `error_group.fingerprint` values with the `Fingerprint(errorGroup ErrorGroup)` function.
* At this point, all `error_group` records should have `fingerprint` populated and we can remove the nullable constraint.
* Remove `Fingerprint(errorGroup ErrorGroup)` function

### Adjust lookup for finding or creating an error group

When a new error comes in, we try to see if there's an existing error group that matches:

https://github.com/highlight/highlight/blob/2a37af87a94bc2402ce50d6f62b17b2aa408e1e6/backend/public-graph/graph/resolver.go#L664-L778

The giant SQL query in there is a known bottleneck for consuming errors and one of the reasons we have all these guards in place:

https://github.com/highlight/highlight/blob/2a37af87a94bc2402ce50d6f62b17b2aa408e1e6/backend/public-graph/graph/resolver.go#L791C1-L838

Instead of using `GetTopErrorGroupMatch`, we should run `Fingerprint(errorObject errorObject)` and see if it matches an existing fingerprint in the `error_groups` table

### Changing the error grouping logic

At this point, we can adjust the logic of `Fingerprint(errorObject errorObject)` to only consider the stacktrace. 

* Adjust logic of `Fingerprint(errorObject errorObject)`
* Have error groups side bar load the latest error instance's message (instead of error group message)
* When paging through error instances, we should use the current error instance's message
* Update the [docs](https://www.highlight.io/docs/general/product-features/error-monitoring/grouping-errors).
* **We will not backfill the logic to old error groups.** This is intentional as we only want this logic to apply going forward. Having #5228 will help clean up the old data for users with large amounts of errors.

## Open questions

* We should do some analysis to see how much [Grouping Rules](https://www.highlight.io/docs/general/product-features/error-monitoring/grouping-errors#grouping-rules) gets used and see if we can remove the feature.

**Comment by mayberryzane** [comment]
Def onboard with removing or deprioritizing the event in error group matching and removing grouping rules if they don’t get any use. For replacing the fingerprints table with a single column, can we handle cases where the fingerprints are not exact matches? One of the motivations for using multiple fingerprints is we can find the closest match even if it isn’t exact, e.g. if a function name or line number on which an error is thrown changes, we can still match some of the stack frames to determine if it’s “close enough”

**Comment by et** [comment]
> One of the motivations for using multiple fingerprints is we can find the closest match even if it isn’t exact, e.g. if a function name or line number on which an error is thrown changes, we can still match some of the stack frames to determine if it’s “close enough”

Is for when new code has been deployed and you want to use the existing error group? Can you show an example in prod of this?

I'm also curious about the scenario of:

* I have a noisy error group and I mark it as ignored
* code changes that makes the problem worse
* because the code changes are small, it matches the existing error group instead of creating a new one 
* do I ever get notified?

I like to think that most folks would want a new error group and with the #5228 feature, it makes it easier to clear out old noise.

**Comment by et** [comment]
Actually, after thinking about it a bit more, I think multiple fingerprints makes sense when the change in the stacktrace would be unrelated to the actual code change (eg six layers deep, the line number changes).
Just not totally sure how would link this stuff together to the same error group without having to do an expensive operation.

**Comment by et** [comment]
Blocked by #5240
