### ISSUE TITLE
Support sharing types between private and public graph

### ISSUE THREAD

**Issue by et** [highlight/highlight#5260]
When @ccschmitz and I were pairing, we noticed that `Source` is an enum in the private graph but not the public graph:

https://github.com/highlight/highlight/blob/717f3f7c7ef521568ad6ee80eba2d04528d454ff/backend/public-graph/graph/schema.graphqls#L46

https://github.com/highlight/highlight/blob/717f3f7c7ef521568ad6ee80eba2d04528d454ff/backend/private-graph/graph/schema.graphqls#L575-L578

Having the enum shared across both schemas would greatly help uncover bugs for us.

From searching around, there does seem to be a prescribed solution for this but it would require research as to how this would work with gqlgen

https://www.apollographql.com/docs/federation/federated-types/sharing-types/

**Comment by Vadman97** [comment]
do we have any pointers on whether this would be possible with gqlgen?
