### ISSUE TITLE
Suggested Blog Posts sometimes do not have images

### ISSUE THREAD

**Issue by Abhishek-More** [highlight/highlight#5265]
**Describe the bug**
Some suggested blog posts display no image, due to some blog posts not having images associated to them.

**To Reproduce**

1. Go to any blog post
2. Scroll down to the suggested post section
3. There are randomly generated suggested posts. It's likely that one of these posts will not have an image.

**Expected behavior**
All suggested posts should have an image, or atleast a placeholder.

**Screenshots**
![image](https://github.com/highlight/highlight/assets/25088104/38a71b3f-3958-4074-9fae-8039ec34ab2c)

**Comment by betty-alagwu** [comment]
Hello @jay-khatri @Abhishek-More i'll like to work on this.
