### ISSUE TITLE
Requirements for OSS Design System

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5277]
@ccschmitz , creating this to take some notes on what we want to do for open sourcing our design system. Feel free to add items below; we can discuss w/ @Abhishek-More next week on Wednesday.

**Comment by ccschmitz** [comment]
@jay-khatri https://github.com/highlight/highlight/issues/5052 is another ticket we already had that laid out the large tasks for this. Let me know if you want me to port that over here or if you want to archive this one.

**Comment by jay-khatri** [comment]
i'll archive. my mistake!
