### ISSUE TITLE
CORS error when initializing highlighting for non-CORS specified images.

### ISSUE THREAD

**Issue by Wundero** [highlight/highlight#5293]
**Describe the bug**
I am trying to use a profile image loaded from an external resource, and the resource does NOT have any CORS headers (e.g. `Access-Control-Allow-Origin`). Normally, this works just fine and the browser will load it but not allow it in a canvas. However, when adding Highlight's React SDK, it fails.

**To Reproduce**

1. Setup highlight on a NextJS application
2. Add an `img` tag with the following source: `https://s4.anilist.co/file/anilistcdn/user/avatar/large/b142051-igOisbZoXrWS.jpg`.
3. See that it fails to load.

**Expected behavior**
The image should load as normal, irrespective of the CORS headers, since images are considered a safe resource.

<details>

<summary>

#### Screenshots

</summary>

With highlight:
![image](https://github.com/highlight/highlight/assets/6076081/76eaa4f5-8cb9-4a52-a910-283b37923c81)
![image](https://github.com/highlight/highlight/assets/6076081/bd8f77b1-4ea1-437b-abf4-de88341e813e)
Without highlight:
![image](https://github.com/highlight/highlight/assets/6076081/53310d30-ff98-4f2e-ab55-b244c8342f3a)

Source image:
![image](https://s4.anilist.co/file/anilistcdn/user/avatar/large/b142051-igOisbZoXrWS.jpg)
Response headers for the image:
![image](https://github.com/highlight/highlight/assets/6076081/13bc5f00-c236-4882-b6dd-e1379b42bb2a)

</details>

**Additional context**
This happens whether `networkRecording` is enabled or disabled, and the only way to prevent the issue is to disable the client SDK outright by not calling `H.init`.

**Comment by Vadman97** [comment]
Hey, thanks for the report. Seems like something within the highlight SDK JS would be accessing the image source requiring the CORS headers. However, for normal recording, this shouldn't be necessary. Mind sharing your `H.init()` settings (without the project ID)?

**Comment by Wundero** [comment]
Thanks for the reply - I tried a number of settings (including with recording off) but they all failed and I think the cause is due to some initialization code that always runs. I had a look through the source code previously but was unable to find the culprit.

Below are my settings:
```js
H.init(env.NEXT_PUBLIC_HIGHLIGHT_KEY, {
  environment: env.NEXT_PUBLIC_NODE_ENV,
  tracingOrigins: true,
  networkRecording: {
    enabled: true,
    recordHeadersAndBody: true,
    urlBlocklist: [],
  },
});
```

To this point I have mostly just been following the NextJS installation instructions, so this should be pretty similar to the source.

**Comment by Vadman97** [comment]
Hi @Wundero - apologies we've let this slip thru the cracks. Do you know if you were seeing CORS issues on recordings from localhost? We've seen that to be the case because we inline images to preserve them in the recording when recording on localhost. Some additional notes in our [docs here](https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js#configure-inlineimages). Mind trying with `inlineImages=false` to see if the issue is resolved? Feel free to reopen if it persists.

**Comment by Wundero** [comment]
Ah that works great, thanks!
