### ISSUE TITLE
Only show Intercom once in the product

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5294]
See Slack thread for context: https://highlightcorp.slack.com/archives/C0454PWLLLW/p1683682991086279?thread_ts=1683606088.806489&cid=C0454PWLLLW

**Comment by ccschmitz** [comment]
@jay-khatri what do you want to do with CTAs like this which currently open the Intercom modal? This is on the empty search results feed for sessions and errors.

![Image](https://github.com/highlight/highlight/assets/308182/454e8b11-764c-4abc-9b06-b746b6c7ba32)

**Comment by ccschmitz** [comment]
@jay-khatri also, what about pages like the sign up/setup pages where a user can't access the app yet? Should we still show the Intercom bubble in the bottom right in that context?

**Comment by jay-khatri** [comment]
> @jay-khatri what do you want to do with CTAs like this which currently open the Intercom modal? This is on the empty search results feed for sessions and errors.
> 
> ![Image](https://user-images.githubusercontent.com/308182/240023695-454e8b11-764c-4abc-9b06-b746b6c7ba32.png)

How about replace "Contact" with "Ask for help", and link to highlight.io/community?

**Comment by jay-khatri** [comment]
> @jay-khatri also, what about pages like the sign up/setup pages where a user can't access the app yet? Should we still show the Intercom bubble in the bottom right in that context?

In those cases, intercom should stay there. That's a good guardrail for any newly introduced bugs with the signup flow, etc..

**Comment by ccschmitz** [comment]
@jay-khatri sounds great - thanks for chiming in on this!
