### ISSUE TITLE
Styling of workspace joining callout is janky

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5299]
Checkout the comment [here](https://app.highlight.io/1/sessions/r3d6M5RjTzXPE8WOkwGIgujbIyTa?commentId=7507&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C30%20days&ts=3.905). 

A few things that we could improve:
- Replace subtext with "Based on your email, you can join this workspace. Would you like to do that?"
- "Join Aurora Lightbox Labeler" should probably just be "Join Workspace", that way the length is pr3edictable
- Update the styles to match @julian-highlight's design recs.

Here's a screenshot (ignore the comment icon):

<img width="607" alt="image" src="https://github.com/highlight/highlight/assets/20292680/ea11936c-50de-40ae-b499-3f4d2d5e1fcc">

**Comment by julian-highlight** [comment]
This is an old issue I know, but here's the design for it: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9079-219431&t=9Kh5VegR2jw9cwuT-11

@deltaepsilon feel free to un-assign yourself if you think that should be done by someone else! Feel free to re-assign people if you know who might be in charge to take it over.
