### ISSUE TITLE
Figure out why some errors are re-routing to a different project

### ISSUE THREAD

**Issue by et** [highlight/highlight#5324]
The behavior was added in #2269

When I took a glance at this, the first thing that stuck out to me was that the client config used `organizationID`:

![Screenshot 2023-05-15 at 8 52 29 AM](https://github.com/highlight/highlight/assets/58678/f0639678-e631-49c1-a4dd-edd3b6d81fda)

which should probably be `projectID`. 

We should look at who these belong to and see if we can get them to modify their source to use `projectID`

**Comment by Vadman97** [comment]
i believe https://github.com/highlight/highlight/pull/2269 was added so that our recording client's errors were routed to a place we could monitor to make sure our client was not breaking customers' webapps.

what error is that screenshot from?
