### ISSUE TITLE
trpc network request bodies are not recorded

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5344]
trpc request bodies and response bodies are not recorded
could be because trpc is not sent as a fetch / xhr request? could trpc use web sockets?

<img width="322" alt="Screenshot 2023-05-13 at 10 04 51 PM" src="https://github.com/highlight/highlight/assets/1351531/961e4c18-43d8-4445-b995-3cd75a5d8a8c">

<img width="1009" alt="Screenshot 2023-05-13 at 9 26 22 PM" src="https://github.com/highlight/highlight/assets/1351531/8fbf4fb9-b688-4b94-bd99-72764be4afb3">

![image (3)](https://github.com/highlight/highlight/assets/1351531/dd149331-7646-4123-97af-7791494f586a)

**Comment by Vadman97** [comment]
could this be because trpc requests are gzipped or chunked?

![image](https://github.com/highlight/highlight/assets/1351531/e27672a0-a1c9-4f93-9a2d-239e9afcfcf8)

**Comment by deltaepsilon** [comment]
It looks like it's using `window.fetch` after all!

![image](https://github.com/highlight/highlight/assets/878947/44e545f6-6205-4a5d-8044-b69c7553a37b)

**Comment by deltaepsilon** [comment]
I've done a ton of testing. tRPC appears to use fetch and hit our `fetch-listener.ts` just fine.

Something must be unique about the setup our customer is using. I sent an email to hopefully learn about his tRPC setup.
