### ISSUE TITLE
Support tagging sessions to search for

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5397]
I've heard from customers that it would be useful to tag sessions so that they could be searched for at a later point. We could do something similar to github's UI where you can add a label like so: 
<img width="326" alt="image" src="https://github.com/highlight/highlight/assets/20292680/4fcbf437-d6f0-462e-9e6c-4cb1ef4d9e63">

And alongside this, being able to search for these labels in our session search UI would be a requirement here too.

This ticket gauges interest for this future.

**Comment by Vadman97** [comment]
Is this different than bubbling up `H.track` calls? Perhaps there is a distinction in how those are shown compared to tags, but searching for an `event` is effectively the same as searching for a `tag`.
