### ISSUE TITLE
Clickup integration isn't working

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5419]
Creating a task from an error doesn't seem to be working on a customer's workspace. Details in this [private link](https://www.notion.so/runhighlight/clickup-integration-not-working-aca0ef139c8f400296c9d2739adfa8a3?pvs=4).

**Comment by jay-khatri** [comment]
Hey @et , mind taking a look at this sometime this week? I've also invited you to the private channel in discord.

**Comment by jay-khatri** [comment]
link to discord: https://discord.com/channels/1026884757667188757/1110023331350073354/1110028570300002335

**Comment by et** [comment]
This may be have been a transient error. 
Last week when I tried to auth, I received a `OAUTH_014` error. As of today, I can successfully auth without error. 
Will reach out to clickup to see what's up on that error but I will reach out to the customer asking them to trying re-authing clickup.
