### ISSUE TITLE
Support a overridable monthly usage amount for one-off customer situations

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5446]
There are some cases where we agree to a one-off usage/price for a customer. Right now, if we update the `*_max_cents` column for a customer this affects both price and usage; can we add a way to override the usage but keep the `*_max_cents` price? For example, if I want to give a customer 5,000,000 logs for $100 / month.

**Comment by jay-khatri** [comment]
@Vadman97 we can use `monthly_{resource}_limit` (e.g. `monthly_logs_limit`) for this. I think we're good here.

**Comment by Vadman97** [comment]
@jay-khatri @mayberryzane would that charge the customer for those 5M logs, (for ex. if i set `monthly_logs_limit=5000000`), or would it just give them 5M logs for free?
