### ISSUE TITLE
cannot subscribe to usagebased plan when on trial plan

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5458]
we should allow subscribing in that case too
seems like this got the customer into a weird situation where they added a CC but were still on free tier, and could never upgrade to the usage based plan even after i canceled their free trial by setting the trial_end_date in the past.
https://app.highlight.io/w/6520/current-plan

https://www.loom.com/share/b6704407879f4bb499b2547e902c2d52

**Comment by mayberryzane** [comment]
fixed in https://github.com/highlight/highlight/pull/5694
