### ISSUE TITLE
Make it obvious what the limitations are of live mode

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5477]
Make it obvious to users what the limitations of are live mode.

* No timeline indicator events
* No logs or network requests
* No errors

Really, the only thing you can do is view what the user is currently doing in real-ish-time. We currently collapse the timeline indicators, but we allow you to keep the dev tools open. Allowing users to keep the dev tools open without refreshing the data can cause confusion because you see a user taking an action but you wouldn't see the logs, errors, or network requests that happened while you were streaming the events to update the replay.

@julian-highlight curious what you think would be a good option here. Perhaps we could lock down dev tools entirely + add a hover state over disabled timeline & dev tools buttons to explain, or maybe we take over the dev tools with a callout explaining that you can't use that stuff while using live mode.

**Comment by julian-highlight** [comment]
Created this design a while back, what exactly is missing here? 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=5407-242453&t=Hmkaw7NSIzAK10wg-11
@ccschmitz

**Comment by julian-highlight** [comment]
I feel like we should remove everything that doesn't bring value to the user in live mode. I'm happy to add a callout to use the space of the dev-tools to explain why they can't see anything + maybe a CTA to turn off Live-Mode. @ccschmitz

**Comment by ccschmitz** [comment]
@julian-highlight that sounds great! Let me know if you have any questions on this, and feel free to play around in the prod UI to see what the current UX is.

Let me know if there's anything else I can do to help with designs!

**Comment by julian-highlight** [comment]
Created a simple design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=5407-242453&t=uAasbI3crVAkzmZC-11

What do you think of the copy? @ccschmitz
