### ISSUE TITLE
TypeError: Cannot read property 'Symbol(kResourceStore)' of undefined

### ISSUE THREAD

**Issue by acemtp** [highlight/highlight#5496]
I installed the node package on my [MeteorJS](https://www.meteor.com/) project

`import { H } from '@highlight-run/node';`

Use the default init

`H.init({ projectID: 'xxxxxxxx' });`

Everything is fine (it uses websocket for the most part of the app), but when a http request is received on the server, I get this error that completely crash the server.

   W20230531-18:41:01.026(2)? (STDERR) TypeError: Cannot read property 'Symbol(kResourceStore)' of undefined
   W20230531-18:41:01.027(2)? (STDERR)     at AsyncLocalStorage._propagate (async_hooks.js:288:34)
W20230531-18:41:01.027(2)? (STDERR)     at AsyncHook.init (async_hooks.js:255:22)
W20230531-18:41:01.027(2)? (STDERR)     at emitInitNative (internal/async_hooks.js:203:43)
W20230531-18:41:01.027(2)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20230531-18:41:01.027(2)? (STDERR)     at initAsyncResource (internal/timers.js:160:5)
W20230531-18:41:01.027(2)? (STDERR)     at new Timeout (internal/timers.js:194:3)
W20230531-18:41:01.027(2)? (STDERR)     at setUnrefTimeout (internal/timers.js:376:17)
W20230531-18:41:01.027(2)? (STDERR)     at Socket.setStreamTimeout [as setTimeout] (internal/stream_base_commons.js:263:22)
W20230531-18:41:01.027(2)? (STDERR)     at IncomingMessage.setTimeout (_http_incoming.js:99:15)
W20230531-18:41:01.027(2)? (STDERR)     at Server.WebApp._timeoutAdjustmentRequestCallback (packages/webapp/webapp_server.js:273:7)
W20230531-18:41:01.027(2)? (STDERR)     at packages/ddp-server/stream_server.js:184:23
W20230531-18:41:01.027(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230531-18:41:01.027(2)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
W20230531-18:41:01.027(2)? (STDERR)     at Server.newListener (packages/ddp-server/stream_server.js:183:11)
W20230531-18:41:01.028(2)? (STDERR)     at Server.emit (events.js:400:28)
W20230531-18:41:01.028(2)? (STDERR)     at Server.emit (domain.js:475:12)
W20230531-18:41:01.028(2)? (STDERR)     at parserOnIncoming (_http_server.js:900:12)
W20230531-18:41:01.028(2)? (STDERR)     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
W20230531-18:41:01.028(2)? (STDERR) TypeError: Cannot read property 'Symbol(kResourceStore)' of undefined
W20230531-18:41:01.028(2)? (STDERR)     at AsyncLocalStorage._propagate (async_hooks.js:288:34)
W20230531-18:41:01.028(2)? (STDERR)     at AsyncHook.init (async_hooks.js:255:22)
W20230531-18:41:01.028(2)? (STDERR)     at emitInitNative (internal/async_hooks.js:203:43)
W20230531-18:41:01.028(2)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20230531-18:41:01.028(2)? (STDERR)     at promiseInitHook (internal/async_hooks.js:323:3)
W20230531-18:41:01.028(2)? (STDERR)     at Function.reject (<anonymous>)
W20230531-18:41:01.028(2)? (STDERR)     at process.<anonymous> (packages/inter-process-messaging.js:227:47)
W20230531-18:41:01.028(2)? (STDERR)     at process.emit (events.js:400:28)
W20230531-18:41:01.028(2)? (STDERR)     at process.emit (domain.js:475:12)
W20230531-18:41:01.028(2)? (STDERR)     at process.exit (internal/process/per_thread.js:179:15)
W20230531-18:41:01.028(2)? (STDERR)     at fatalError (internal/async_hooks.js:176:11)
W20230531-18:41:01.028(2)? (STDERR)     at emitInitNative (internal/async_hooks.js:210:5)
W20230531-18:41:01.028(2)? (STDERR)     at emitInitScript (internal/async_hooks.js:493:3)
W20230531-18:41:01.028(2)? (STDERR)     at initAsyncResource (internal/timers.js:160:5)
W20230531-18:41:01.028(2)? (STDERR)     at new Timeout (internal/timers.js:194:3)
W20230531-18:41:01.028(2)? (STDERR)     at setUnrefTimeout (internal/timers.js:376:17)
W20230531-18:41:01.028(2)? (STDERR)     at Socket.setStreamTimeout [as setTimeout] (internal/stream_base_commons.js:263:22)
W20230531-18:41:01.028(2)? (STDERR)     at IncomingMessage.setTimeout (_http_incoming.js:99:15)
W20230531-18:41:01.028(2)? (STDERR)     at Server.WebApp._timeoutAdjustmentRequestCallback (packages/webapp/webapp_server.js:273:7)
W20230531-18:41:01.028(2)? (STDERR)     at packages/ddp-server/stream_server.js:184:23
W20230531-18:41:01.028(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230531-18:41:01.028(2)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

I found nothing on internet or here about this error.

I imagine that highlight wrap some method to automatically detect things, is there a way to disable that to see if it's the source of the problem ?

**Comment by Vadman97** [comment]
hey @acemtp , thanks for the report. as we haven't worked with MeteorJS before, mind sharing a bit of your setup for highlight there? what file are you adding the highlight node `H.init({ projectID: 'xxxxxxxx' });` call in? also, do you have any other instrumentation libraries installed? if you could share your `package.json` contents, that would be great.
