### ISSUE TITLE
Not recording ThreeJS Canvas , possibly tainted Canvas?

### ISSUE THREAD

**Issue by YanivKnoll** [highlight/highlight#5581]
**Describe the bug**
When recording our app that uses ThreeJS and rendering via canvas, we cannot see the canvas recording with 3d objects.

**To Reproduce**
This is our Init code:
```
H.init('---', {
  environment: 'production',
  version: '---',
  enableCanvasRecording: true,        // enable canvas recording
  inlineImages: true,
  recordCrossOriginIframe: true,
  samplingStrategy: {
    canvas: 2,                        // snapshot at 2 fps
    canvasMaxSnapshotDimension: 480,  // snapshot at a max 480p resolution
  },
  networkRecording: {
    enabled: true,
    recordHeadersAndBody: true,
    urlBlocklist: [
      // insert full or partial urls that you don't want to record here
      // Out of the box, Highlight will not record these URLs (they can be safely removed):
      "https://www.googleapis.com/identitytoolkit",
      "https://securetoken.googleapis.com",
    ],
  },
});
```

Everything else works perfectly.

We also made sure all the 3d models and textures are setting crossOrigin to anonymous.

**Expected behavior**
Record  the 3D objects rendered in the canvas.

**Screenshots**
It shows:
<img width="1055" alt="image" src="https://github.com/highlight/highlight/assets/113887174/b45a01c6-9ee3-4419-bd0e-1c0b2a34f5e7">
It should show:
<img width="1271" alt="image" src="https://github.com/highlight/highlight/assets/113887174/a4b337e0-469c-40dc-ba06-4f199a6c7be4">

**Additional context**
If we missed any logs we could have a look at to see what is the error, this would also be great.

**Comment by michaelapplydesign** [comment]
hi, any progress with this ?

**Comment by wnr** [comment]
I have the same problem, using threejs.

**Comment by Vadman97** [comment]
Hi @wnr @michaelapplydesign @YanivKnoll , this can be fixed by using the new manual snapshotting setup (see docs https://www.highlight.io/docs/getting-started/client-sdk/replay-configuration/canvas#manual-snapshotting). This happens because the canvas webgl contents are not in memory, so we need to manually snapshot from the render loop to be able to get the contents.
