### ISSUE TITLE
support non-us 2fa country codes

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5595]
Rather than hardcoding the +1 US country code, we should have a country code picker in our 2-fa settings UI.

![image](https://github.com/highlight/highlight/assets/1351531/7e6cb0ae-d19a-4d9b-972d-b3296cb5c2ca)

@julian-highlight , do we have a new design for the user authentication settings?

https://github.com/highlight/highlight/blob/4d2ff3c0320e27549528aa9add4bc03d1568c2b4/frontend/src/pages/UserSettings/Auth/Auth.tsx#L138

additional context in https://discord.com/channels/1026884757667188757/1115247282800042064

**Comment by ccschmitz** [comment]
Here's what I propose we do: https://www.loom.com/share/28d7c03ee397490a88033fa40249e388

@julian-highlight I don't think you need to mock anything up for this. We may as well take the time to convert the input + button to use our new components as well.

**Comment by julian-highlight** [comment]
Created all the designs here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=8682-349056&t=zr5JHkjMozNk64qE-11

@et

**Comment by Vadman97** [comment]
Hey @et @ccschmitz , IIRC you guys are pairing on this issue this week? Wanted to check in as another customer is asking for this [here](https://discord.com/channels/1026884757667188757/1123016923144274020/1123634876860596346).

**Comment by et** [comment]
> Hey @et @ccschmitz , IIRC you guys are pairing on this issue this week? Wanted to check in as another customer is asking for this [here](https://discord.com/channels/1026884757667188757/1123016923144274020/1123634876860596346).

We're syncing up next week actually.
