### ISSUE TITLE
enabling filtering sessions without errors should have a warning callout

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5596]
when checking the button in the `/settings` page, we should have an explicit warning modal that explains what this setting will do.

**Comment by betty-alagwu** [comment]
Hey @Vadman97 can i work on this?

**Comment by jay-khatri** [comment]
cc @julian-highlight regarding designs.

**Comment by julian-highlight** [comment]
Added a design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=7765-360301&mode=design&t=wpyUSW9q6L8qWF4E-11

Feel free to change the text to something that is a bit more precise! As this toggle could be turned back off easily, I don't think we need any barrier in terms of a pop-up modal. 

@Vadman97 @betty-alagwu

**Comment by betty-alagwu** [comment]
@jay-khatri @Vadman97 good to assign this to me ? 

Thanks.

**Comment by mayberryzane** [comment]
<img width="553" alt="Screen Shot 2023-08-18 at 6 36 42 AM" src="https://github.com/highlight/highlight/assets/86132398/65f23a32-3783-441c-9fe6-d764853fb476">

**Comment by rishi-raj-jain** [comment]
Hey @neo773 I see you attempting https://github.com/highlight/highlight/issues/6277 already, I'd want to get this one cc @mayberryzane 

/attempt #5596

**Comment by neo773** [comment]
@rishi-raj-jain Cancelled my attempt on this, feel free to work on it.

**Comment by rishi-raj-jain** [comment]
Thanks!

**Comment by rishi-raj-jain** [comment]
@mayberryzane I've sent a request for access to the figma file from rishi18304@iiitd.ac.in

**Comment by evonloch** [comment]
@rishi-raj-jain how did you set up the enviroment? codespace?

**Comment by rishi-raj-jain** [comment]
@evonloch 

On my desktop.

**Comment by rishi-raj-jain** [comment]
@mayberryzane I've sent a request for access to the figma file from [rishi18304@iiitd.ac.in](mailto:rishi18304@iiitd.ac.in)
