### ISSUE TITLE
Add a way track the "source" of a resource view

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5615]
As part of error triage improvements (and possible upcoming alerts work), it would be nice to instrument our app to be able to understand the "source" of a given resource view. I.e. if someone views an error, are they viewing this from an email, slack alert, or just from visiting the error page directly?

This will also help with some data analysis to do an initial pass on where views are coming from.

cc @Vadman97

**Comment by jay-khatri** [comment]
cc @ccschmitz

**Comment by jay-khatri** [comment]
- where do people come from when they view something (sessions, errors)
- how do people engage with an error (snooze/ignore/resolve) and the source of that action

**Comment by et** [comment]
Reopening until data is gathered in mixpanel.

**Comment by et** [comment]
Tracked in a `referrer` property
https://mixpanel.com/project/2504464/view/3045720/app/events#vxvo1Kp8DUDe
