### ISSUE TITLE
Incorrect Aggregation of Logs in Highlight from Multiple Vercel Projects

### ISSUE THREAD

**Issue by ryanburns23** [highlight/highlight#5616]
**Describe the bug**
The integration of multiple projects from Vercel into Highlight results in the merging of all logs from the connected Vercel projects into a single Highlight project. This occurs irrespective of the distinct Highlight project links that have been established for each Vercel project.

**To Reproduce**
1. Generate two new projects in Vercel.
2. Implement the Highlight integration and provide access permissions for both Vercel projects.
3. Establish links between each Vercel project and an individual Highlight project.
4. Execute your Vercel projects, triggering them to generate logs.
5. Navigate to the Highlight platform and observe how logs from both Vercel projects are combined and displayed, irrespective of the selected Highlight project.

**Expected behavior**
Each Vercel project's logs should be confined to its respective linked Highlight project, without any cross-merging of logs between projects.

**Additional context**
Upon connecting the projects within Vercel, it was observed that ENV vars were only created in one of the linked projects. Despite this, the project lacking the ENV vars still produced logs that flowed to Highlight. Although this discrepancy did not appear to directly influence the bug, it may be a related issue that warrants further investigation.

**Comment by mayberryzane** [comment]
Hi @ryanburns23 - this issue should be fixed now - you can fix it in your workspace by re-saving the Vercel integration settings by going to the Highlight integrations page (https://app.highlight.io/integrations), clicking the Vercel cog icon, and clicking "Link Projects" again.

Let me know if you're running into any other issues, and thanks for the detailed bug report!
