### ISSUE TITLE
using `HighlightInit` with `H.identify` will cause recursive network monkeypatch

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5619]
setting up `<HighlightInit/>` in next.js and `highlight.run` for `H.identify` will set up double network listeners that will collide and cause a recursive error. in `highlight.run`, we should only set up network listeners if they have not been set up.

![image](https://github.com/highlight/highlight/assets/1351531/9bf2052e-2cd4-4d90-a016-89d8da0885d5)

https://discord.com/channels/1026884757667188757/1116676770813464596

**Comment by mchl-hess** [comment]
Also running into this -- has anyone found a workaround?

**Comment by jay-khatri** [comment]
Current workaround is to use `H.init` in a client component instead. Maybe a related to question for while we work on this (@Vadman97 @deltaepsilon): should we be consolidating the imports for NextJS so that its only from "@highlight/next"?
