### ISSUE TITLE
The contributing.md docs should be more comprehensive

### ISSUE THREAD

**Issue by giftade** [highlight/highlight#5644]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to contribute to a project and I can't really understand the process from the contributing.md docs

**Describe the solution you'd like**
A clear contribution guideline should be added to the contributing.md doc

**Comment by jay-khatri** [comment]
@giftade what do you wish was here? Do you mind sharing docs that you've liked from other projects?

**Comment by giftade** [comment]
@jay-khatri  I'll try to look for it
when I click on the link in the contributing.md file, it takes me to this
 [https://github.com/highlight/highlight/blob/main/docs-content/general/4_company/open-source/contributing/1_getting-started.md](this) and it doesn't really help, what if there's just a link to the contributing page on the official website? [https://www.highlight.io/docs/general/company/open-source/contributing](this).

**Comment by jay-khatri** [comment]
Great idea. If you'd like to open a PR, feel free. Otherwise, I can ticket it.

**Comment by giftade** [comment]
@jay-khatri Ok, I'd do that
