### ISSUE TITLE
Filter out error groups w/o a useful stacktrace yet we know that the project has sourcemaps configured

### ISSUE THREAD

**Issue by et** [highlight/highlight#5655]
We've seen these come from extensions ([example](https://discord.com/channels/1026884757667188757/1116750815982534666/1118547673943904346)).

**Comment by et** [comment]
See example: https://app.highlight.io/1/errors/d7UB7d18l6SMQDGbKQbXoshAvU1U?page=1

**Comment by Vadman97** [comment]
@et , following up on the conversation today about errors with stack traces that are represented as an array:

![image](https://github.com/highlight/highlight/assets/1351531/3c2eb275-2617-4797-9bfd-643c22309469)

I actually no longer see any instances of the error that have an array as a stack trace in the example instance: https://app.highlight.io/735/errors/w0jEHzNeUDpufDRWMidagFtHZXV5

However, one hunch at where those might come from are `console.error` recorded errors. I wouldn't be surprised if they represent the stack trace in a different format than `window.onerror` recorded errors. alternatively, this could have to do with [different OS/browsers having a different format for the stack trace](https://github.com/highlight/highlight/issues/5739), in which case we should normalize them in our SDK
