### ISSUE TITLE
Fix scrolling container height

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#5671]
It seems like the right panel's scrolling container is not extending to the bottom and cuts of some content! This might be related to #5672 .

Link to session: https://app.highlight.io/1/sessions/US0XcNVvnpQ1lw7hf61GkAXAoYcl?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-05-17T23%3A09%3A33.988Z_2023-06-16T23%3A09%3A33.988Z

Screenshot for reference: 
<img width="390" alt="image" src="https://github.com/highlight/highlight/assets/114743131/0471609b-1a6f-4d26-963d-9801b639203f">

**Comment by SpennyNDaJets** [comment]
Seems fixed with new right panel
<img width="628" alt="Screenshot 2023-07-18 at 2 35 47 PM" src="https://github.com/highlight/highlight/assets/17744174/42643251-aa51-4e88-923a-edcbca65ff04">
