### ISSUE TITLE
Fix scrolling behavior to make the whole container scrollable

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#5672]
When I initially designed this I imagined the scrolling behave similiar to e.g. Figma's right panel. 

Here's a little video showcasing what I'm talking about:
https://github.com/highlight/highlight/assets/114743131/f47e948f-23c5-4011-9979-badc8304a476

**Comment by SpennyNDaJets** [comment]
Fixed with new right panel
![image](https://github.com/highlight/highlight/assets/17744174/aa1eda4b-60a9-4880-890f-3a6fa15c4e6c)

**Comment by julian-highlight** [comment]
@SpennyNDaJets can we also get the same thing done for session metadata? 
![image](https://github.com/highlight/highlight/assets/114743131/25472222-cfbb-40c9-814a-16cfe48d21a1)
