### ISSUE TITLE
Page freezing with `H.init` in NextJS

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5676]
**Describe the bug**
> Having an issue getting the H.identify() method to work on NextJS, despite following the directions in the user manual. Do you have any tips? The page just freezes when highlight makes the identify call.

**To Reproduce**
TBD

**Comment by mchl-hess** [comment]
One in the same with https://github.com/highlight/highlight/issues/5619

**Comment by deltaepsilon** [comment]
My first reproduction attempt failed. I'm using the new App Router, and I can use `H.identify` separately from `<HighlightInit />` without trouble.

Next step... attempt to do the same with the Page Router.

![image](https://github.com/highlight/highlight/assets/878947/8d26a613-f115-4450-bdfb-e1a89565879a)

**Comment by deltaepsilon** [comment]
Well reject my PR and call me Susy, I'm failing to reproduce in `_app.tsx` as well!

![image](https://github.com/highlight/highlight/assets/878947/4ec670fc-bc3b-4d03-ba59-bb4691616ef6)
