### ISSUE TITLE
live mode always have an active length of 0

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5681]
<img width="340" alt="Screenshot 2023-06-20 at 11 28 05 AM" src="https://github.com/highlight/highlight/assets/1351531/16845f16-e3ea-4519-808b-1737d7739254">

for live mode, could we show the totla session length here, or otherwise have some `live` indicator instead to not show the wrong time?

**Comment by julian-highlight** [comment]
Could we simply replace the time-stamp with the 'Live' Badge? I feel like that's also making the card look nicer! 

Wdyt @ccschmitz @Vadman97

**Comment by ccschmitz** [comment]
@julian-highlight are you thinking we would swap the time badge with a primary (purple) badge saying "Live" and remove "Live" from the top right?

**Comment by julian-highlight** [comment]
> @julian-highlight are you thinking we would swap the time badge with a primary (purple) badge saying "Live" and remove "Live" from the top right?

yep exactly. I mean it feels like the timestamp is not useful for live sessions 🤔

**Comment by julian-highlight** [comment]
@ccschmitz this is how it would look like: 
![image](https://github.com/highlight/highlight/assets/114743131/12e47976-e860-448e-a3bd-b1b9d81e9d6a)

Would add some emphasis to the badge to make it super obvious (as the layout now mixes it with other tags). Let me know if you got any thoughts, that are speaking against doing this :P

**Comment by julian-highlight** [comment]
Updated component here: https://www.figma.com/file/pAHlb8IFmVSewPJcphbjIH/Component-Library?type=design&node-id=414-13056&mode=design&t=DyqtgcOMIvjI3hsp-11

Maybe we could use this to re-align design & code to make sure these cards go to their full potential. I feel like we could do some polish here, without great effort! @ccschmitz

**Comment by ccschmitz** [comment]
This was resolved in #5477.
