### ISSUE TITLE
error grouping for instances without a stacktrace should perform a value similarity 

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5695]
first: figure out why some errors don't have a stacktrace. a simpler fix to this should be that all errors must have stacktraces.

error grouping for instances without a stacktrace should perform a value similarity check (90% of the text matches).
for example, https://app.highlight.io/1/errors/8JfiMblxeCZNXBNEUAxTAj0gwn4O and https://app.highlight.io/1/errors/jjrOKh3KgrpAdDRPpwEzec3EdX67 should be grouped together because most characters match

**Comment by Vadman97** [comment]
```
select project_id, secure_id
from error_groups
where created_at > now() - interval '1 week' and stack_trace = 'null'
-- and event not ilike 'ENOENT%'
group by project_id, secure_id;
```
the problem is that we have errors that do not get a stack trace, so we do not group them.
we should fix the root cause of the missing stacktraces first, and then double check that such errors (`ENOENT`) are grouped.
https://app.highlight.io/1103/errors/77Kmfth3JOMbddDpoVZStfHRqJsg might be another similar error

**Comment by ccschmitz** [comment]
The `ENOENT` issue might be something to do with Node's `fs` [not providing a stack trace](https://stackoverflow.com/questions/61155350/why-theres-no-stack-trace-in-node-fs-rmdir-error). Here's [another ticket](https://github.com/nodejs/node/issues/30944) about it in the node repo.

I think Datadog [has a workaround for this](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/?tab=containers#bundling).
