### ISSUE TITLE
Add an AI settings item for a workspace + digests

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5717]
- [ ] Add the ability to edit to AI features on the workspace level
    - sessions are off by default
    - errors are on by default
- [ ] Add the ability to turn on/off digests for sessions / regular digests for every project

From previous issue:
> - New tab for "AI insights" on workspace settings page with option to turn on/off "AI enhanced" session insights
    - when I turn it on, it gives me granular control of "session insights" and "error insights"
>  - on the "notifications" user settings page, when I turn on "digests", i get granular control of which digests to turn on/off. For now, these are "general digests" and "session digests". For the description of "session digests", include a link to edit AI on/off on the workspace settings page

**Comment by julian-highlight** [comment]
Yo thinking about this more carefully, I'm thinking we don't need granular control over turning on AI in some parts of the app. If someone is against using GPT they'll turn it off anyways. At the same time people need to press a button whenever they want to use any of those features, even when they're turned on. Therefor we don't have to worry about unintended over-usage. @jay-khatri

**Comment by julian-highlight** [comment]
Also the Notifications/Digest settings here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9193-279287&mode=design&t=Rfu7LnV8pWZMuirq-11

**Comment by eightants** [comment]
From the meeting, the main thing to focus on right now is the digest settings, so I'll get started on that.

**Comment by eightants** [comment]
I think with the addition of the new Harold settings page + description + links, this can be closed. Only remaining thing from here is the session/error AI limit tracking, but we're not tracking them yet.
