### ISSUE TITLE
Build a digest for "session insights" (with and w/o AI insights)

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5721]
Session Insights email w/o "AI enhanced" session insights
Sessions insights email w/ "AI enhanced" session insights

**Comment by julian-highlight** [comment]
Yo team! Created some designs for this today! 

Here's a little loom for you to listen while waking up from your Highlight dreams ✨ 
https://www.loom.com/share/0c45055cc529463a90c91c7b9d246379

Designs for the emails: https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?type=design&node-id=5794-82014&mode=design&t=mcLtXmoVzkh45W3g-11

fyi @mayberryzane @jay-khatri
