### ISSUE TITLE
Add a way to order by "interesting sessions" (+ make sort order more discoverable?)

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5722]
@julian-highlight , we need to make the "order by" option on the session page more discoverable. After that, zane adds the ability to order by interesting sessions (using his session score)

**Comment by julian-highlight** [comment]
I've adjusted the icon to be more bold about being able to sort when clicking it! I'd love to keep the action row here < 4, to make actions clear from the first glance. 

Maybe when we accomplish auto-refresh we can remove the refresh button here and open up more space for something like a sort action!

**Comment by julian-highlight** [comment]
Design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9187-566485&mode=design&t=wpyUSW9q6L8qWF4E-11

@mayberryzane
