### ISSUE TITLE
add the ability to search for a session by user input

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5757]
> One key feature I love about XXX is the ability to search for a session by what the user typed in. It sometimes is the only way to find a session (if, for example, we're trying to find the user that conducted a certain interview and all we have is the comments they typed in). 

we should think about recording user inputs as searchable events, while being mindful of `<input>` privacy settings.

**Comment by jay-khatri** [comment]
i saw we deprioritize this until we hear this again.
