### ISSUE TITLE
Add ability to customize webhooks

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5759]
People want to integrate Highlight with external services, but we aren't able to build out every integration people want. We added webhooks for alerts in #4550, but third-party services often require payloads in a certain format or custom headers for auth. We should add the ability for someone to customize the body of the payload and add custom headers on requests to make these more useful for users integrating Highlight with third-party services.

Note that #5732 adds the ability to send email alerts to custom email addresses, which services like Opsgenie support, but webhooks will be a better solution for this.

We will also look at building out true integrations for incident management tools like PagerDuty, Opsgenie, etc. in the future.

**Comment by jay-khatri** [comment]
Cancelling in favor of #4697
