### ISSUE TITLE
Lock error state window when updating

### ISSUE THREAD

**Issue by et** [highlight/highlight#5778]
When we update the error group state, we should lock the window until all the requests finish.

@julian-highlight - we'll need a design for this. Here's a [loom](https://www.loom.com/share/a7077c82b1e44d118c6f52c60cb34cff) to describe the issue.

**Comment by julian-highlight** [comment]
I think the easiest way to tackle this is by replacing the chevron of the button with the spinner! Like this: 
![image](https://github.com/highlight/highlight/assets/114743131/a324b213-b986-42b6-934b-fedcbdf37a0d)
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=4790-270177&mode=design&t=mPCNNbmXk2AD747g-11

**Comment by jay-khatri** [comment]
@SpennyNDaJets to bounty this.
