### ISSUE TITLE
Jira Integration

### ISSUE THREAD

**Issue by MichaelCGrant** [highlight/highlight#5787]
Add a Jira integration so that we can create issues straight from the Highlight UI.

Like our other issue tracker integrations, we want to be able to:
- add, configure, and remove the Jira integration from our integrations page https://github.com/highlight/highlight/blob/main/highlight.io/pages/integrations.tsx#L1 ; adding the integration will save an authorization token at the workspace level that can be used to make requests to the Jira API for creating issues
<img width="703" alt="Screen Shot 2023-09-18 at 9 46 04 AM" src="https://github.com/highlight/highlight/assets/86132398/4f655b0f-7b40-4b9b-848e-8cd3c4e88492">

- create a Jira issue from a session comment (a new comment on the session player or an existing comment in the right panel)
<img width="465" alt="Screen Shot 2023-09-18 at 9 45 00 AM" src="https://github.com/highlight/highlight/assets/86132398/8e9218fc-12e2-4e25-9bfc-28d9d61c5dd4">
<img width="302" alt="Screen Shot 2023-09-18 at 9 50 00 AM" src="https://github.com/highlight/highlight/assets/86132398/79041ede-b343-48b4-9859-c5dee2d46da9">

- create a Jira issue from an error
<img width="353" alt="Screen Shot 2023-09-18 at 9 45 21 AM" src="https://github.com/highlight/highlight/assets/86132398/fe434ef3-5cf4-45e2-bfd4-8784934916fd">

- all behavior should match with the other integrations (e.g. clickup, height, github) for linking out to issues from Highlight, removing issues, etc
- for local testing, you can create your own Jira Oauth app and use your own client id / secret https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/ ; before we deploy this integration in production, you can share your integration's settings with us and we will create a Highlight Oauth app with matching settings

**Comment by jay-khatri** [comment]
Thanks for the ticket @MichaelCGrant. We will incorporate this into our upcoming planning cycle and get back to you on a timeline.

**Comment by jay-khatri** [comment]
@MichaelCGrant, plan is to work on this middle of august.

**Comment by jay-khatri** [comment]
@mayberryzane, maybe we can work on this alongside? 
https://github.com/highlight/highlight/issues/5699

**Comment by mayberryzane** [comment]
@neo773 added some more details to the description - let me know if you have any questions! Thanks

**Comment by neo773** [comment]
Half way into the adding the integration for Jira I realised the backend is written in Go.
So if someone wants to use this PR as a base feel free to do it (It adds the frontend changes required).

https://github.com/highlight/highlight/pull/6643

**Comment by jemiluv8** [comment]
@Hitesh-sisara, I've been interested in working on this. 
I'm wondering if it's ok for me to make an attempt.

**Comment by Hg6f9** [comment]
https://console.algora.io/api/auth/callback/email?callbackUrl=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fbounties%2Fclmp28lbo0002lc0f7b13pb6a%2Fcancel-attempt&token=6b4ccbd51e19242bd77b71f7491efdd466a4bb042cf377b483c1e45f75ade3f6&email=brendacmtte%40gmail.com

**Comment by Hitesh-sisara** [comment]
@jemiluv8 you can

**Comment by jemiluv8** [comment]
@mayberryzane , @MichaelCGrant , @Vadman97 I just created a draft PR for the integration. 
Click [here](https://www.loom.com/share/21f7ba7f112f473fab00f8497948a1c4?sid=fb098cd0-6dd4-403e-b282-ca6658f69440) to checkout my loom video of the progress thus far.
