### ISSUE TITLE
Uncaught TypeError: window.HighlightIO is not a constructor

### ISSUE THREAD

**Issue by Syntaf** [highlight/highlight#5804]
**Describe the bug**
https://github.com/highlight/highlight/pull/5766 Seems to have introduced a regression, at least in my situation, which causes the initialization of highlight to fail on versions after *7.3.1*

**To Reproduce**
* Follows the documentation for a simple html head tag https://www.highlight.io/docs/getting-started/client-sdk/other
* Visit the page in your browser, note the error `Uncaught TypeError: window.HighlightIO is not a constructor`

I looks like after 7.1.1, `window.HighlightIO` is used instead of `window.Highlight`, reverting to `7.3.1` solves this issue:

```
<script src="https://unpkg.com/highlight.run@7.3.1" type="text/javascript"></script>
```

**Screenshots**

<img width="315" alt="Screenshot 2023-07-02 at 3 36 24 PM" src="https://github.com/highlight/highlight/assets/1827631/7fe55e1d-2a0b-4615-ba2a-727dce4a81e8">

**Comment by Syntaf** [comment]
Maybe it's due to this declare still using `Highlight`? I'm not actually sure if the TS interface here would play into the name of the window attribute once it's compiled into js.

https://github.com/highlight/highlight/blob/f45e6556d807d36c60609f050c32f485e90caaaf/sdk/client/src/index.tsx#L1394C22-L1394C22

It also looks like `'Highlight'` needs to be updated to `'HighlightIO'` here:

https://github.com/highlight/highlight/blob/f45e6556d807d36c60609f050c32f485e90caaaf/sdk/firstload/src/index.tsx#L139

Not able to verify what I said above as I'm having trouble finding docs on how to generate dists of the sdk files to verify. Any tips?

**Comment by jay-khatri** [comment]
Related discord thread: https://discord.com/channels/1026884757667188757/1026884757667188763/1124513431752556564

**Comment by deltaepsilon** [comment]
> Maybe it's due to this declare still using `Highlight`? I'm not actually sure if the TS interface here would play into the name of the window attribute once it's compiled into js.
> 
> https://github.com/highlight/highlight/blob/f45e6556d807d36c60609f050c32f485e90caaaf/sdk/client/src/index.tsx#L1384
> 
> It also looks like `'Highlight'` needs to be updated to `'HighlightIO'` here:
> 
> https://github.com/highlight/highlight/blob/f45e6556d807d36c60609f050c32f485e90caaaf/sdk/firstload/src/index.tsx#L139
> 
> Not able to verify what I said above as I'm having trouble finding docs on how to generate dists of the sdk files to verify. Any tips?

Great find!

The first item is internal code. We were only renaming `window.Highlight` to `window.HighlightIO`, so our internal naming shouldn't matter???

The second line is 100% an issue. 
The `startFunction` will never be called on browsers without `window.Highlight` defined. The check is always wrong, but in browsers that support native `window.Highlight` (see [support table](https://developer.mozilla.org/en-US/docs/Web/API/Highlight#browser_compatibility)), it would detect the native function and run `startFunction` anyway. Firefox does not support `window.Highlight`, and we probably tested in Chrome and Safari only.

I'll make the fix to `firstload/src/index.tsx`, bump the version, and let you know when to upgrade.

**Comment by deltaepsilon** [comment]
Looks like our deploy missed and deployed the previous version, v7.3.2 instead of v7.3.3:

https://github.com/highlight/highlight/actions/runs/5381288593/jobs/9765144881#step:13:54

I've got the `firstload` fix tested. It does solve the problem on Firefox/Safari.

I'm trying to figure out why the deploy failed.

**Comment by deltaepsilon** [comment]
@Syntaf I've tested locally and the issue is fixed for me. Let me know how it goes! Just upgrade to v7.3.4.

https://static.highlight.io/v7.3.4/index.js
