### ISSUE TITLE
highlight-py: Support more recent versions of fastapi

### ISSUE THREAD

**Issue by tobim** [highlight/highlight#5812]
**Is your feature request related to a problem? Please describe.**
When trying to use the python SDK in a fastapi based service:
```
Trying to add `highlight-io[FastAPI] as dependency:

Because no versions of highlight-io match >0.5.2,<0.6.0
 and highlight-io (0.5.2) depends on fastapi (>=0.92.0,<0.93.0), highlight-io (>=0.5.2,<0.6.0) requires fastapi (>=0.92.0,<0.93.0).
So, because tenant-manager depends on both fastapi (^0.95.1) and highlight-io (^0.5.2), version solving failed.
```

**Describe the solution you'd like**
Relax the version bounds in `pyproject.toml`, and verify that it works.

**Comment by Vadman97** [comment]
hey @tobim , thanks for the report! we'll take this on this week - appreciate your patience. what version of fastapi are you using currently? is it `0.95.1`?

**Comment by tobim** [comment]
Hi @Vadman97, it seems that the change you did is not enough.
https://github.com/highlight/highlight/blob/02f2bdbefc6e1d416b0f8d86e098464635a44271/sdk/highlight-py/pyproject.toml#L32 still only allows FastAPI between 0.92 and 0.93.
So `poetry add highlight-io[FastAPI]` fails.

Can you reopen?

**Comment by tobim** [comment]
Hi @et, thanks for taking a look!
I guess `version = ">=0.92"` should work, I'll report back if  we run into trouble due to breaking changes.

**Comment by et** [comment]
Hey @tobim - I relaxed the requirement and pushed a new release (`0.5.5`). Mind giving it another shot?

**Comment by tobim** [comment]
Turns out we also require a newer version of uvicorn:
```
> poetry add highlight-io[FastAPI] 
Using version ^0.5.5 for highlight-io

Updating dependencies
Resolving dependencies... (4.4s)

Because no versions of highlight-io match >0.5.5,<0.6.0
 and highlight-io (0.5.5) depends on uvicorn (>=0.20,<0.21), highlight-io (>=0.5.5,<0.6.0) requires uvicorn (>=0.20,<0.21).
Because uvicorn (0.20.0) depends on uvicorn (0.20.0)
 and no versions of uvicorn match >0.20,<0.21, uvicorn (>=0.20,<0.21) requires uvicorn (0.20.0).
Thus, highlight-io (>=0.5.5,<0.6.0) requires uvicorn (0.20.0).
So, because tenant-manager depends on both uvicorn (^0.21.1) and highlight-io (^0.5.5), version solving failed.
```
Getting closer though.

**Comment by et** [comment]
Hey @tobim  - I pushed another release (0.5.6) to relax the uvicorn requirement. Mind giving it another shot when you have a chance?

**Comment by et** [comment]
Hey @tobim - doing some housekeeping and assuming this issue is fixed. If it's still not broken, let me know and we can take another look. Thanks!
