### ISSUE TITLE
Julian's error and session polish items ✨

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5813]
```[tasklist]
### Errors
- [x] Remove divider between breadcrumbs and header
- [x] Move actions to the right of the top bar
- [ ] https://github.com/highlight/highlight/issues/6019
- [x] "Latest >" links are not using the correct component (should be a tag)
- [ ] https://github.com/highlight/highlight/issues/6020
- [x] Padding on icon for "Related session/logs" buttons seems off
- [x] Not using a two-column layout for metadata and user details
- [x] Metadata + user details tables should be using tags for values
- [x] Show more/less buttons are off (positioning + actual button/tag)
- [x] Remove bottom divider between stacktrace and title
- [x] User details callout looks off when there's no body (too much padding on bottom)
- [x] Next/previous error group/instance buttons have new styles (standalone buttons w/ divider)
- [ ] https://github.com/highlight/highlight/issues/6018
```

```[tasklist]
### Sessions
- [x] Cards in search results are not the same as errors
- [x] Tags and text styles should all be the same as error search result cards
- [x] If you're in threads (comment) mode and refresh the page it doesn't reopen the threads panel
- [ ] https://github.com/highlight/highlight/issues/6050
- [x] Network request filter menus are larger than the autoscroll button next to them
- [x] Remove +/- from timeline
- [x] Show more/less button is off (spacing + button styles)
- [ ] https://github.com/highlight/highlight/issues/6023
- [x] Monotype is too small across sessions and errors
```

```[tasklist]
### Misc.
- [x] Monotype is too small on sessions and errors
```

**Comment by ccschmitz** [comment]
@julian-highlight this is ready for click testing on a preview URL whenever you have time!

https://preview.highlight.io/1/sessions?page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-06-20T16%3A46%3A11.653Z_2023-07-20T16%3A46%3A11.653Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H5QS95R1SVTNK26BEW7QDKV2%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%225813-julians-error-and-session-polish-items%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D

**Comment by ccschmitz** [comment]
@jay-khatri @julian-highlight @Vadman97 I handled most of these but had to break out a few to separate tickets because they were going to take a little longer. Let me know if you'd like me to follow up on any of these or if you want me to just flesh out the ticket details a little more so we can have someone else pick them up.

**Comment by julian-highlight** [comment]
I'm open to let others work on these as well! If there's context needed in any of those remaining tickets, feel free to just @ me. 

Let's keep an eye on these tickets though to make sure they get fixed at some point 👍 
Great work on all of these solved ones though @ccschmitz !
