### ISSUE TITLE
Data loading + loading states on the instance view

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5820]
@et , in short, it would be nice if we served the data for the first instance of an error group in the high-level loading state. UX wold be much cleaner imo. cc @julian-highlight .

https://www.loom.com/share/41e83222610347e08c200519285b5dbd

**Comment by et** [comment]
Would suggest we try prefetching the data on mouse hover of the error group:
https://www.apollographql.com/docs/react/v2/performance/performance/#prefetching-data

**Comment by jay-khatri** [comment]
The loading of the error group data is already not too slow. The problem is that there's two requests happening in series. Would that solve this problem?

The hover over solution seems like it wouldn't really save much loading time; I don't really hover for long before clicking on something.

**Comment by jay-khatri** [comment]
In terms of a solution, I was thinking that we run the fetching of the error group/instance in parallel (and have them share a loading state).

As far as preloading error groups, I thought we were already doing this for all error groups on a given page 🤔; I believe @Vadman97 had done some work in this space (for sessions/errors) earlier.
