### ISSUE TITLE
Support for Vue 2 among our SDKs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5822]
It seems that Highlight only works on Vue 3, not Vue 2. Its worth us experimenting with Vue 2 to see how hard adding support for it would be. 

https://discord.com/channels/1026884757667188757/1121848546623225917/1121901984476303510

Steps to complete this:
- Confirm that Highlight.io doesn't work with Vue 2, and find a fix
- Document any sdk changes here: https://www.highlight.io/docs/getting-started/client-sdk/vuejs
- Bump SDK version and merge

**Comment by zcesur** [comment]
👋 hey @jay-khatri, zaf from algora here. currently only the [highlight members on algora](https://console.algora.io/org/highlight/members) are authorized to create bounties. you can sign up with a @highlight.io address to auto join the org

**Comment by neo773** [comment]
@jay-khatri Can I get assigned to this? Algora isn’t letting me attempt for some reason
I have 2 PR awaiting reviews so I’m not sure how it’s “open attempts”

![189ACD46-9E5B-4BFE-AD03-67F24D0C37B6](https://github.com/highlight/highlight/assets/62795688/e443837c-e05b-40e2-b2cf-ca82260ca799)

**Comment by zcesur** [comment]
hey @neo773 looks like something went wrong here, sorry about that. i'm taking care of it

**Comment by neo773** [comment]
@zcesur 

Thanks!

**Comment by Vadman97** [comment]
Feel free to work on this @neo773 !

**Comment by Vadman97** [comment]
hey @neo773, appreciate your looking into this! will circle back with the original report and see if we can get more detail. closing for now.
/tip $25 @neo773
