### ISSUE TITLE
Add visual element for devtools logs/network requests to track the position

### ISSUE THREAD

**Issue by et** [highlight/highlight#5845]
**Is your feature request related to a problem? Please describe.**
It can be difficult to track what is the current log in devtools at given a session play time. It would be nice to add some type of visual element here.

**Describe the solution you'd like**

Here's what replay.io does:
![image](https://github.com/highlight/highlight/assets/58678/92d58ada-4269-4d20-9347-a1b7fdb4841c)

Doesn't have to be exactly this but some type of UX would help here.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by julian-highlight** [comment]
Added designs here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9938-229817&mode=design&t=es9nkbs2QqAUw82P-11

Let me know if there's help needed with the actual implementation of it (Behavior, placement etc)
I think it makes sense to somehow absolutely place the divider, so it doesn't interfere with content. 

@et
