### ISSUE TITLE
show paywall on sessions outside billing quota when linked from an error

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5888]
a outside-of-billing-quota session can also be linked from a slack message.
in both cases, we should show a paywall on the session page rather than an infinite loading state.
https://www.loom.com/share/33449902ddd8481e919c1e6110ef4f5a

**Comment by ccschmitz** [comment]
@jay-khatri @julian-highlight do we have any UI built for a paywall like this anywhere else in the app? Wondering if there's something I can reuse or if we need to design something.

**Comment by julian-highlight** [comment]
@ccschmitz nah we don't have designs for something like this yet. I'd probably use something like we used for unauthenticated views: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=7506-286829&mode=design&t=IwckXB1hGlai32Ev-11

Let me know if I should create a design for it!

**Comment by jay-khatri** [comment]
Is there already a state for "outside billing quota" that you can take insipiration from? cc @mayberryzane

**Comment by jay-khatri** [comment]
Is there already a state for "outside billing quota" that you can take insipiration from? cc @mayberryzane

**Comment by jay-khatri** [comment]
For this callout, it would be nice if there were a CTA to hit the billing page.

**Comment by mayberryzane** [comment]
This is what we have rn:
<img width="384" alt="Screen Shot 2023-07-20 at 4 09 36 PM" src="https://github.com/highlight/highlight/assets/86132398/bd3c592f-e7bb-4d16-9d03-b302fdc768bd">
I think there are still some cases where there's an infinite loading state happening instead though

**Comment by julian-highlight** [comment]
Could we somehow put an callout when we have loading states > e.g. 2 minutes? That could help us giving feedback in all the cases right? @mayberryzane
