### ISSUE TITLE
Fix "View all sessions for user" button on error page

### ISSUE THREAD

**Issue by mayberryzane** [highlight/highlight#5938]

**Comment by jay-khatri** [comment]
@mayberryzane hearing about this more and more. definitely worth prioritizing next week.

**Comment by kalibetre** [comment]
Hey @jay-khatri, could you kindly assign me to this issue?

**Comment by kalibetre** [comment]
@jay-khatri With regard to this bug, I have looked into it and found that the "All sessions for this user" button navigates to the sessions page by setting the query string on the URL as expected with the user's identifier however there are two issues that are causing the unexpected behavior

1. The search query context was not updated before navigating to the sessions page and hence it was not picked up by the session query
2. Even if the search query was updated, the query builder is intentionally reset as shown in the below code segment in `QueryBuilder` component with the reason mentioned in the comment

```tsx
// When the query builder is unmounted, reset the state.
// Not sure if this is desired behavior in the long term, but
// this matches the current prod behavior.
useEffect(() => {
return () => {
	removeSelectedSegment()
}
}, [removeSelectedSegment])
```

If the above code is commented out and the search context is updated in `ErrorInstance` component, clicking the button would behave as expected as shown below.

[![all sessions for this user](https://s11.gifyu.com/images/ScaON.gif)](https://gifyu.com/image/ScaON)

Please advise for the next step.

**Comment by kalibetre** [comment]
@mayberryzane, you are right (1) was the main factor that caused the issue. However, it is not enough to address the issue.

As you correctly stated, the Session and Error query builders have separate states **and Context**. The `ErrorQueryBuilder` uses an Error Context via `useErrorSearchContext` while the `SearchQueryBuilder` use a context via `useSearchContext`. These contexts have different initial states.

The above code snippet (rest) was happening inside the `QueryBuilder` component, which is shared by both `ErrorQueryBuilder` and `SearchQueryBuilder`. The reset sets the contexts to a default state (which is different for the two) when re-render happens. Hence, any search context you set inside the errors page will be lost when a re-render happens on the sessions page after you navigate to it.

To demonstrate this, check out the gif below. Without removing the above code snippet and only applying a fix for (1). The `SearchQueryBuilder` correctly sets the search query, but when it re-renders it gets reset. (look closely at the quick flash)

[![ScYhN.gif](https://s11.gifyu.com/images/ScYhN.gif)](https://gifyu.com/image/ScYhN)
