### ISSUE TITLE
Add version to error instance view

### ISSUE THREAD

**Issue by et** [highlight/highlight#5970]
We need a way to see the version from the error instance view.
@julian-highlight - I suspect somewhere in this list is fine.
![Screenshot 2023-07-17 at 12 56 46 PM](https://github.com/highlight/highlight/assets/58678/0dcda7a4-2ea5-4039-a2d3-46d5beac6850)

It would be great to have a click to copy button as well.

**Comment by julian-highlight** [comment]
Easiest way is to just add a new row with that metadata? Copying functionality is already there, by clicking on the data itself :P Will add version to the designs anyways! 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9059-233396&mode=design&t=IwckXB1hGlai32Ev-11

**Comment by et** [comment]
Thanks. Just wanted to confirm that's where you wanted it.
