### ISSUE TITLE
Improve alert UI for slack, discord and email.

### ISSUE THREAD

**Issue by et** [highlight/highlight#5995]

**Comment by et** [comment]
Email alerts do not handle quotes correctly:
![Screenshot 2023-07-18 at 2 43 54 PM](https://github.com/highlight/highlight/assets/58678/6677e3f0-517d-43a5-98cf-feb7c0c2f00d)

![Screenshot 2023-07-18 at 2 43 01 PM](https://github.com/highlight/highlight/assets/58678/7854e10a-ba9c-4150-9fb0-532be1fbb5eb)

**Comment by SpennyNDaJets** [comment]
Some examples of what slack can handle

![Image](https://github.com/highlight/highlight/assets/17744174/408101b4-fac7-4c74-a1f0-31b4eb88eb26)


![Image](https://github.com/highlight/highlight/assets/17744174/e4c3fe2c-9684-4409-a27c-ecbfa9be2ebf)

**Comment by julian-highlight** [comment]
Design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=12167-59357&mode=design&t=qRn85LZxOxKkvlQ7-11

@SpennyNDaJets
