### ISSUE TITLE
Metadata tables should keep labels top-aligned (same for logs)

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6023]
<img width="453" alt="Screenshot 2023-07-21 at 3 48 42 PM" src="https://github.com/highlight/highlight/assets/308182/21306771-898d-43c3-a337-513615f2d61a">

<img width="293" alt="Screenshot 2023-07-21 at 3 50 02 PM" src="https://github.com/highlight/highlight/assets/308182/e1a7ee3f-3029-4398-8be7-f9835e38c73f">

We should also double-check the paddings on table items/values to ensure it's correct.

**Comment by Abhishek-90** [comment]
Hello @ccschmitz @jay-khatri , Just to understand the issue better with an example. In the first Image provided, the `error` key, is vertically, center aligned, as per it's value height, We want it to be at top irrespective of the height consumed by it's value? Correct? Same for `App version` in the 2nd screenshot.
