### ISSUE TITLE
Scrolling on individual collapsible metadata sections is weird - should make the whole session metadata tab view scrollable

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6049]
Once scrolling is fixed, allow all sections to be open and don't collapse when opening a new one.

**Comment by kalibetre** [comment]
I would kindly like to contribute to this, if no one is working / assigned to this issue. I have a rough working version and would like to polish it and contribute.

**Comment by et** [comment]
Looking good @kalibetre! Feel free to open a PR 🥂

**Comment by kalibetre** [comment]
Thank you for assigning me. I have created the PR

**Comment by jay-khatri** [comment]
#6238 closes this.
