### ISSUE TITLE
When transitioning from threads to inspect mode it shouldn't close the panel

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6050]

**Comment by julian-highlight** [comment]
Basically: 
If both, 'Thread panel' & 'Session panel' are true, you'll see the thread panel. Navigating out of comment mode will show you the 'Session Panel'. Basically we never show the session-panel in comment mode! 
![image](https://github.com/highlight/highlight/assets/114743131/363df5ad-3d34-448c-882f-ab040d98c6f6)

Long term, I want to get rid of the session-panel toggle completely, but more on that in the future :P 

@ccschmitz

**Comment by ccschmitz** [comment]
We also had some [discussion in Slack](https://highlightcorp.slack.com/archives/C055267SKRB/p1691551699885049) about ways to make it more obvious how commenting vs inspecting works and decoupling the modes from whether the comment panel is displayed.

**Comment by julian-highlight** [comment]
We decided to switch comment and inspect mode for now, just to simplify navigating into the threads-panel. @ccschmitz

**Comment by julian-highlight** [comment]
> @julian-highlight sorry, would you mind clarifying a bit on this? Happy to sync up for a quick chat as well, but would be good to spell out exactly how we want this to work.

In case we're not able to meet before I'm out for a week : https://www.loom.com/share/87dc1ded3d554fdb9764b6112240467e

**Comment by ccschmitz** [comment]
@julian-highlight I'm going to try and summarize the changes you went over in the Loom.

1. Swap the inspect and comment mode buttons so inspect mode is on the left.
2. Remember whether the right panel is open and when you go back to inspect mode restore the panel to the state it was in previous.

Does that sound right?

**Comment by julian-highlight** [comment]
> @julian-highlight I'm going to try and summarize the changes you went over in the Loom.
> 
> 1. Swap the inspect and comment mode buttons so inspect mode is on the left.
> 2. Remember whether the right panel is open and when you go back to inspect mode restore the panel to the state it was in previous.
> 
> Does that sound right?

sounds spot on!

**Comment by ccschmitz** [comment]
Started working on this and had some back and forth with @julian-highlight - going to finalize what we want to do here when we sync up tomorrow.
