### ISSUE TITLE
Add a new page/UI for "Services"

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6057]
Add a new page/UI for Services. Adding ths since @julian-highlight has started to think about this.

What info do we want to render here?

**Comment by julian-highlight** [comment]
MVP Designs here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=9984-241330&mode=design&t=cA1T5sqNzj170Nnn-11

**Comment by julian-highlight** [comment]
A new view based on the feedback of adding it to the settings: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=10467-379716&mode=design&t=qT4JkUV7grRvpEoW-11
fyi @SpennyNDaJets
