### ISSUE TITLE
Ability to admins to your workspace in setup flow

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6059]
also enable auto-join for company domains?

**Comment by julian-highlight** [comment]
We have this here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=6105-304242&mode=design&t=cA1T5sqNzj170Nnn-11

**Comment by julian-highlight** [comment]
Final design for this specific feature here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=10873-307479&mode=design&t=TXazbg26lUsCpf7a-11

cc @Vadman97
