### ISSUE TITLE
Alert form redesigns

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6075]
```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6077
- [ ] https://github.com/highlight/highlight/issues/6076
```

**Comment by julian-highlight** [comment]
I've created designs here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=10517-523518&mode=design&t=qT4JkUV7grRvpEoW-11 @eightants @SpennyNDaJets 

Unsure if there's missing functionality or not, or if we want to add functionality here. Let me know!
