### ISSUE TITLE
Error active state is incorrect

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6089]
https://www.loom.com/share/32f427454ff04015b7fb0fccca88138e

**Comment by Tooluloope** [comment]
Hi @jay-khatri, Could you assign this issue to me?

**Comment by Tooluloope** [comment]
Hi @jay-khatri 
I noticed the issue had been fixed, although there is a subtle issue with the error selection.

https://www.loom.com/share/32f427454ff04015b7fb0fccca88138e

**Comment by jay-khatri** [comment]
Thanks for looking into that. I'll update the description with your loom; if you don't mind working on what you proposed, that'd be awesome.

**Comment by Tooluloope** [comment]
@jay-khatri @SpennyNDaJets 
I have a PR ready for review https://github.com/highlight/highlight/pull/6246
