### ISSUE TITLE
Conflict with Sentry

### ISSUE THREAD

**Issue by jimmiebtlr** [highlight/highlight#6094]
**Describe the bug**
We have both sentry and highlight enabled in our project at the moment, and we're seeing some rare conditions lead to the tab becoming unresponsive.

**To Reproduce**

1. In our site, we're using material ui.  Editing a form, and closing a drawer sometimes triggers cpu lock of the tab.

**Expected behavior**
No CPU lock.

**Additional context**
Removing sentry or removing highlight makes it impossible to reproduce, not certain if it just removes the conditions or actually fixes the issue.

Based on a performance profile, if I'm understanding properly is material ui sets a timer to do some work, and add's a load event listener on a new stylesheet script getting added.  Somewhere in there it seems like things are duplicating and multiple timers/events getting fired to the point the CPU maxes out.

Any suggestions on things to try to resolve? I can potentially grant access to a staging environment, and walk through reproduction if that would be useful.  I know this isn't particularly easy to work with, so any ideas of something I should try, please let me know.

**Comment by jay-khatri** [comment]
Hey @jimmiebtlr, this is a bit out of scope given that a good amount of our product competes with Sentry. Are there any features we could help build to bridge the gap of using Sentry?

**Comment by jimmiebtlr** [comment]
Part of our reason for sentry at the moment is we have existing backend stuff using it.

Sentry has a little easier time integrating with next projects.  I've not been able to figure out how to add offline support for highlightio as well, though maybe I've missed that.  Also adding tunnel/proxy support for sentry in nextjs was incredibly simple.

We're still figuring out a bit of what we want to do, I agree using both highlight and sentry is not the best option.

Thanks for the response.

**Comment by jay-khatri** [comment]
Hey @jimmiebtlr, makes sense. If its ok, i'll close this. 

> I've not been able to figure out how to add offline support for highlightio as well, though maybe I've missed that. 

What do you mean by offline support?

**Comment by jimmiebtlr** [comment]
Support for collecting logs while offline, and re-sending when online.  Preferably with storage to local storage.

**Comment by jay-khatri** [comment]
Ok, understood. Created a feature above 👆. @jimmiebtlr thanks for the conversation! I hope you choose Highlight!
