### ISSUE TITLE
Add log level filtering as a project setting

### ISSUE THREAD

**Issue by et** [highlight/highlight#6129]
Customers would like to filter their logs by certain levels:
https://github.com/highlight/highlight/blob/8300b0b800ab07296516bf4efe375aea4b55c216/backend/private-graph/graph/schema.graphqls#L341-L348

For example, the `trace` level can be very noisy and will eat up their log limit very quickly.
Most people probably want `warn`, `error`, and `fatal` when running Highlight against their production app.

We should:
* Build out a new tab on the project settings for Logs (see screenshot below)
* Have a setting that allows checking one or many or all of the log levels listed above

![image](https://github.com/highlight/highlight/assets/58678/898a6cf9-a1fe-417b-b151-d3288024cb77)

**Comment by julian-highlight** [comment]
Done! 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=7765-360989&mode=design&t=i1WiasiU3MBCgqx4-11
@et

**Comment by et** [comment]
Thanks @julian-highlight!

**Comment by jay-khatri** [comment]
See https://discord.com/channels/1026884757667188757/1134544190987051086 as an example of a customer who wants to filter out specific log levels. 

I'm not sure how we can expose in the product, but it would be nice if I could get some numerical feedback about the logs that I'm about to ignore (i.e. some sort of graph or number). I believe sentry does this with their filtering features.

**Comment by Vadman97** [comment]
will be revisiting as part of @SpennyNDaJets 's broader work on filtering logs

**Comment by ccschmitz** [comment]
Handled as part of project filters.
