### ISSUE TITLE
keyword searches don't bubble up all the time

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6153]
Example:
<img width="1512" alt="image" src="https://github.com/highlight/highlight/assets/20292680/7de9f585-5996-49fd-b48f-f733218a579d">

**Comment by ccschmitz** [comment]
Investigating a bit... Seems to be an issue on matches of long strings on the `message` key.

**Comment by ccschmitz** [comment]
Example query where we can reproduce this: https://app.highlight.io/1/logs?end_date=2023-08-15T05%3A00%3A00.000Z&query=testing&start_date=2023-08-12T05%3A00%3A00.000Z
