### ISSUE TITLE
Replace service_name in error group view if provided

### ISSUE THREAD

**Issue by et** [highlight/highlight#6159]
![Screenshot_2023-07-31_at_11_06_16_AM](https://github.com/highlight/highlight/assets/58678/fa1a6d10-99f5-4269-b6a6-976318bf806b)

If service name is provided, replace the text at the error group level.

**Comment by et** [comment]
Hey @julian-highlight - let me know if you have any concerns of where I'd like to put service name at the error group level.

**Comment by julian-highlight** [comment]
No totally fine with that! I've put this tag in here just in case we have more contextual data here, so this is perfect 👍 @et
