### ISSUE TITLE
Update clicking functionality for "goto"

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6222]
![CleanShot 2023-08-03 at 11 40 25 (2)](https://github.com/highlight/highlight/assets/20292680/32817028-14ff-44b3-9d13-0b50291bd4be)

**Comment by julian-highlight** [comment]
The space for bar-charts is blocking any time interactions, as the clicking interaction is reserved for the distribution-graph. We could make the upper area with the time-stamps inside more prominent to make it more obvious! 

@ccschmitz 

cc @jay-khatri

**Comment by ccschmitz** [comment]
@julian-highlight that sounds good to me. Have any thoughts on how we would make that more prominent?

**Comment by julian-highlight** [comment]
> @julian-highlight that sounds good to me. Have any thoughts on how we would make that more prominent?

I think this could be part of a large session polish. I'm personally thinking we could do a great session polish in Q4, but that would need further discussion with @jay-khatri in terms of prioritization. But yea I have so many ideas on how to improve the session experience, but I'm holding off from it, as I want to spend a good amount of time to actually focus on the session product.

**Comment by ccschmitz** [comment]
Sounds great. In the meantime, what do you think about making it possible to click on empty space in the canvas to jump to that time in the session?

I actually implemented this in #6678. Check out [the PR preview](https://preview.highlight.io/?%7Er_preview=%7B%22action%22%3A%22start%22%2C%22variantId%22%3A%2201HATAAF8PDZ55PN2KT0YWH53F%22%2C%22region%22%3A%22ewr%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%226222-update-clicking-functionality-for-goto%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D) to play with it and let me know what you think of the UX.

**Comment by ccschmitz** [comment]
Chatted w/ Julian about this in Slack.

<img width="404" alt="Screenshot 2023-09-22 at 9 45 07 AM" src="https://github.com/highlight/highlight/assets/308182/57ef29f8-b7ac-4e8e-a167-175d6b8b2739">
