### ISSUE TITLE
Create Issue from errors page has unintended caching

### ISSUE THREAD

**Issue by et** [highlight/highlight#6234]
To reproduce
* Click an error and observe error body
* Select Create Issue and observe error body is filled in for Issue Title
* Close modal
* Select a different error
* Select Create Issue and observe it uses the previous error's body for the Issue Title

https://www.loom.com/share/719e79d41cf848419b23d63b0e6fae60

**Comment by jay-khatri** [comment]
Thanks @et, assigning to @mayberryzane alongside the some other UI enhancements in #5699.

**Comment by Tooluloope** [comment]
@jay-khatri @et, Can I work on this?

**Comment by mayberryzane** [comment]
Hi @Tooluloope - were you still interested in working on this? I'll work on the issue today if not. Thanks!

**Comment by Tooluloope** [comment]
Yeah, I'm debugging the UI/Form component. That's where the issue emanates from.

The right `defaultValues` is passed to `useFormState` in the `NewIssueModal` component, but the state is using stale values.
I should get back with a PR ASAP.

**Comment by mayberryzane** [comment]
Ok, thank you for taking a look! Let me know if there's anything I can help with

**Comment by Tooluloope** [comment]
@mayberryzane Tagged you to the PR
