### ISSUE TITLE
Add filter to errors page

### ISSUE THREAD

**Issue by et** [highlight/highlight#6237]
Need a CTA when there are no services set up.

**Comment by et** [comment]
@mayberryzane has a PR to write errors to clickhouse (#6445). We intend to cut over reading from opensearch -> clickhouse later this week. Hence, we can hold off on this until we are fully on clickhouse.

**Comment by julian-highlight** [comment]
Created a design here anyways, that simply adds a label to the filter item and functions as a CTA. Let me know if we want to exclude this functionality from the filter dropdown! 
https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=5020-222338&mode=design&t=Tgs9pS5JEYlZ140T-11
@et
