### ISSUE TITLE
Be more clear about billing implications of ignoring errors/sessions

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6245]
- add a note in the respective project settings pages that tells customers whether ignored sessions and errors count towards their billing quota
- link to to the error / session ignoring docs in their respective project settings page sections: [sessions](https://www.highlight.io/docs/general/product-features/session-replay/ignoring-sessions)/[errors](https://www.highlight.io/docs/general/product-features/error-monitoring/ignoring-errors)

**Comment by jay-khatri** [comment]
@et, this came from an email thread where a customer was asking about this. 

also, it is not clear to me what "ignoring" means because we do have a concept of setting the `status` of an error to ignored. should we change our naming of this?

**Comment by et** [comment]
Thanks for raising -- "filtering" is likely a better word here.
