### ISSUE TITLE
Bugs in payload responses on network resource panel

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6267]
There are a couple of bugs we noticed during Waterloo on the network resource panel. First, sometimes the response payload is an array and we break this up into multiple objects with the array index as a label rather than displaying the entire payload.

<img width="1512" alt="Screenshot 2023-08-08 at 11 51 23 AM" src="https://github.com/highlight/highlight/assets/308182/906a77e8-7914-4b41-b24c-361e367fe248">

Session URL: https://app.highlight.io/213/sessions/7xBCfetJmkg3ozVQcYSJQqiqW8LU?network-resource-id=110&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-07-09T16%3A18%3A21.978Z_2023-08-08T16%3A18%3A21.978Z

---

Another bug is the formatting of this code snippet.

![image](https://github.com/highlight/highlight/assets/308182/c68ef9a2-1709-45e2-931d-706422ad4e76)

Session URL: https://app.highlight.io/4856/sessions/v1FFyiF2C5lg2skFkmbfeA2hsjcN?network-resource-id=75&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-07-05T20%3A29%3A59.679Z_2023-08-04T20%3A29%3A59.679Z

**Comment by Abhishek-90** [comment]
I would like to take it up.

**Comment by Tooluloope** [comment]
@Abhishek-90 are you working on this issue?

**Comment by Vadman97** [comment]
hey @Tooluloope , feel free to take this on since we haven't heard from @Abhishek-90

**Comment by Vadman97** [comment]
hey @Tooluloope , feel free to take this on since we haven't heard from @Abhishek-90

**Comment by Tooluloope** [comment]
@ccschmitz I dont have access to the session links you sent above

**Comment by jemiluv8** [comment]
> Another bug is the formatting of this code snippet.

@ccschmitz can you help me access the [link](https://github.com/highlight/highlight/issues/6267#:~:text=https%3A//app.highlight.io/4856/sessions/v1FFyiF2C5lg2skFkmbfeA2hsjcN%3Fnetwork%2Dresource%2Did%3D75%26page%3D1%26query%3Dand%257C%257Ccustom_processed%252Cis%252Ctrue%257C%257Ccustom_created_at%252Cbetween_date%252C2023%2D07%2D05T20%253A29%253A59.679Z_2023%2D08%2D04T20%253A29%253A59.679Z) to the session for the improperly formatted code snippet.
I followed the link and "requested" access.
I've thus far not been able to get a mutation that is displayed that way and I'm not sure if that issue has already been fixed.
