### ISSUE TITLE
Error extracting fields from span

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6272]
<img width="1512" alt="Screenshot 2023-08-08 at 4 35 53 PM" src="https://github.com/highlight/highlight/assets/308182/e8569ef5-ab5f-46b0-b431-9bfef8151532">

https://app.highlight.io/1/logs?end_date=2023-08-08T21%3A22%3A24.927Z&query=extract&start_date=2023-08-08T21%3A17%3A58.662Z

**Comment by ccschmitz** [comment]
Should also consider adding a guard clause to prevent traces from being captured for logs. See Slack thread for context: https://highlightcorp.slack.com/archives/C02CJANPHQS/p1691692648934789

**Comment by ccschmitz** [comment]
Looks like the issue here is that the project ID isn't set on these spans. @Vadman97 do you have any thoughts off the top of your head on how this might be happening?

**Comment by Vadman97** [comment]
do we know anything else about what these spans look like? i would expect any auto-instrumented spans to still send the project ID because we define that as a resource attribute when setting up the OTEL sdk, but we could start with figuring out what these spans without a project ID are?

**Comment by ccschmitz** [comment]
Here is some JSON for spans that failed:

```json
{
  "http.flavor": "1.1",
  "http.host": "127.0.0.1: 45599",
  "http.method": "GET",
  "http.response_content_length_uncompressed": 14213,
  "http.status_code": 200,
  "http.status_text": "OK",
  "http.target": "/api/blog/article",
  "http.url": "http: //127.0.0.1:45599/api/blog/article",
  "net.peer.ip": "127.0.0.1",
  "net.peer.name": "127.0.0.1",
  "net.peer.port": 45599,
  "net.transport": "ip_tcp",
  "process.command": "/var/runtime/index.mjs",
  "process.command_line": "/var/lang/bin/node, /var/runtime/index.mjs",
  "process.executable.name": "/var/lang/bin/node",
  "process.pid": 15,
  "process.runtime.description": "Node.js",
  "process.runtime.name": "nodejs",
  "process.runtime.version": "18.16.1",
  "telemetry.sdk.language": "nodejs",
  "telemetry.sdk.name": "opentelemetry",
  "telemetry.sdk.version": "1.6.0"
}
```

```json
{
  "http.flavor": "1.1",
  "http.host": "20.0.2.188:3000",
  "http.method": "GET",
  "http.status_code": "200",
  "http.status_text": "OK",
  "http.target": "/",
  "http.url": "http://20.0.2.188:3000/",
  "http.user_agent": "ELB-HealthChecker/2.0",
  "net.host.ip": "::ffff:20.0.2.188",
  "net.host.name": "20.0.2.188",
  "net.host.port": "3000",
  "net.peer.ip": "::ffff:20.0.6.80",
  "net.peer.port": "32824",
  "net.transport": "ip_tcp",
  "process.command": "/opt/glyde/dist/app.js",
  "process.command_line": "/usr/local/bin/node, opt/glyde/dist/app.js",
  "process.executable.name": "node",
  "process.pid": "27",
  "process.runtime.description": "Node.js",
  "process.runtime.name": "nodejs",
  "process.runtime.version": "14.15.1",
  "telemetry.sdk.language": "nodejs",
  "telemetry.sdk.name": "opentelemetry",
  "telemetry.sdk.version": "1.6.0",
}
```

```json
{
  "telemetry.sdk.language": "nodejs",
  "telemetry.sdk.name": "opentelemetry",
  "telemetry.sdk.version": "1.12.0"
}
```

Thanks for adding logging so we can see these attributes now, @Vadman97! I see these are all coming from the Node SDK. Do you think there's something we need to address there?
