### ISSUE TITLE
When clicking into the detail of an event and going back, preserve scroll position

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6277]
"would be great if the scroll position was preserved when you went back to the events list since our sessions are quite long and have a lot of events, so it's hard to keep track of where you were looking at (also the ability to jump to the timestamp of an event without viewing the event's detail would work too)"

**Comment by neo773** [comment]
@mayberryzane yarn workspaces seems to be broken, I tried rm -rfing yarn.lock but it still failed

<img width="878" alt="image" src="https://github.com/highlight/highlight/assets/62795688/f041e10b-fbeb-4630-9625-271f50e811b8">

**Comment by Chigala** [comment]
I'm also finding it difficult setting up the repo locally

**Comment by jay-khatri** [comment]
Hey @Chigala @rishi-raj-jain , if you're having trouble with that, please send us a message in our discord: https://highlight.io/community!
