### ISSUE TITLE
Make the comment button more obvious

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6278]
"Would be great to show comments on the timeline"

Its not obvious enough that we have an easy way to view all of the comments in a session. How can we make this more obvious? See: https://highlightcorp.slack.com/archives/C05DXNT5L8L/p1690990805288349

**Comment by julian-highlight** [comment]
This is solved for now isn't it? @jay-khatri

**Comment by jay-khatri** [comment]
Yes. Closing.
