### ISSUE TITLE
older browsers don't have a .text function in the xhr response which throws an error in the highlight script.

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6282]
![image](https://github.com/highlight/highlight/assets/1351531/88f843d1-6fad-4317-beac-22392f5f6f37)

**Comment by TheUltDev** [comment]
Browsers seen so far without support:

<img width="733" alt="Screenshot 2023-08-09 at 2 00 35 PM" src="https://github.com/highlight/highlight/assets/2079305/c65daf2b-bd3d-4cd3-95c2-a3028820ee52">
