### ISSUE TITLE
Apply as filter throws error for some log values 

### ISSUE THREAD

**Issue by et** [highlight/highlight#6295]
* Click Apply as filter on `container.id` 
* Observe error

![Screenshot 2023-08-10 at 8 47 32 AM](https://github.com/highlight/highlight/assets/58678/24043973-ece7-46ec-b79f-6feeed981d08)

Not totally sure but the problem does seem to be isolated to log values that are numbers (i.e. `code.lineno` has the same issue).

**Comment by ccschmitz** [comment]
Sounds like the problem might be that some values are numbers and not strings, and we're trying to call `startsWith` which is only available on strings. I'll put up a quick fix in https://github.com/highlight/highlight/pull/6287.
