### ISSUE TITLE
Run ruby publish step only if the version file changed

### ISSUE THREAD

**Issue by et** [highlight/highlight#6296]
We added a rubygem publish step in #6269. We should only run the ruby publish step if the version file changed:
https://github.com/highlight/highlight/blob/main/sdk/highlight-ruby/highlight/lib/highlight/version.rb

To do this, we can either:

* use the [dorny/paths-filter](https://github.com/dorny/paths-filter) to determine if that file changed at a conditional level
* extract the publish step into a separate workflow

**Comment by Vadman97** [comment]
resolved by #6547
