### ISSUE TITLE
Ingesting a raw log is poorly formatted

### ISSUE THREAD

**Issue by et** [highlight/highlight#6304]
From our [docs](https://www.highlight.io/docs/getting-started/backend-logging/http), using the first curl example results in this log

![Screenshot 2023-08-10 at 2 00 06 PM](https://github.com/highlight/highlight/assets/58678/92f904c0-3ef4-4a68-b7d6-edb672385d98)

**Comment by Abhishek-90** [comment]
What is the expected format of the results? Can you share an example @et ?

**Comment by et** [comment]
> What is the expected format of the results? Can you share an example @et ?

Hey 👋 
We shouldn't have that `%2C%` stuff in there. Those should be spaces. 

If you'd like to give this a shot, the offending code is here:
https://github.com/highlight/highlight/blob/87edf1d13c3470203b9eddc712309e6afc8bd486/backend/http/logging.go#L260-L279

We have a test for that function:

https://github.com/highlight/highlight/blob/87edf1d13c3470203b9eddc712309e6afc8bd486/backend/http/logging_test.go#L38-L43

But it's somewhat flawed as that `strings.NewReader` part doesn't exhibit the same behavior as using the `-d` flag with curl ([docs](https://curl.se/docs/manpage.html#-d)).

**Comment by Abhishek-90** [comment]
Alright, thankyou for the code Snippet @et . From the overview I think, the main part to focus on would be on line 276 in `logging.go` as that part adds the message in the response. Please correct me if I am wrong.

**Comment by et** [comment]
> Alright, thankyou for the code Snippet @et . From the overview I think, the main part to focus on would be on line 276 in logging.go as that part adds the message in the response. Please correct me if I am wrong.

That seems right. Probably easier to just use a debugger and step through the code to see what needs fixing.
