### ISSUE TITLE
Log filters are not working as expected when multiple filters are applied

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6313]
![Image](https://github.com/highlight/highlight/assets/308182/6abd52fb-c00f-42c5-b5bc-8c0513b4c014)

Note how the `code.lineno` filter is not filtering out logs that don't explicitly match.

**Comment by ccschmitz** [comment]
@Vadman97 you mentioned I should tag you on this. Is it something you're planning to look into, or would you like me to?

**Comment by et** [comment]
@ccschmitz - I was curious if this was a backend issue but I wrote a [test](https://github.com/highlight/highlight/pull/6314) to simulate the behavior and it passes. So I think this is a frontend issue.

**Comment by Vadman97** [comment]
to add here, experienced this crash when querying for `code.lineno: *1` and updating the result
<img width="627" alt="Screenshot 2023-08-11 at 10 52 09 AM" src="https://github.com/highlight/highlight/assets/1351531/b6021a78-b41b-40bd-a0e7-7a8b5eaa169e">
<img width="647" alt="Screenshot 2023-08-11 at 10 52 03 AM" src="https://github.com/highlight/highlight/assets/1351531/22839281-3124-44bb-b57d-bc85b64dd1b1">

**Comment by ccschmitz** [comment]
The issue mentioned in https://github.com/highlight/highlight/issues/6313#issuecomment-1675164274 was resolved by #6287.

**Comment by ccschmitz** [comment]
# Logs SQL Debugging

Here is a query that consistently returns results that don't match all the filters:

```
level:warn code.lineno:*08 os.type:linux
```

This ended up producing the following SQL:

```sql
SELECT Timestamp, UUID, SeverityText, Body, LogAttributes, TraceId, SpanId, SecureSessionId, Source, ServiceName, ServiceVersion FROM (SELECT Timestamp, UUID, SeverityText, Body, LogAttributes, TraceId, SpanId, SecureSessionId, Source, ServiceName, ServiceVersion FROM logs WHERE ProjectId = 1 AND toUInt64(toDateTime(Timestamp)) <= ? AND toUInt64(toDateTime(Timestamp)) >= ? AND (SeverityText = ?) AND (LogAttributes[?] LIKE ? OR LogAttributes[?] = ?) ORDER BY Timestamp DESC, UUID DESC LIMIT 51) AS logs_window ORDER BY Timestamp DESC, UUID DESC
```

Here are the arguments for the SQL:

```
[%!s(int=1) %!s(uint64=1692796582) %!s(uint64=1692792982) warn code.lineno %08 os.type darwin]
```

It looks like this is actually producing an `OR` query for the attribute matches.

Another issue I'm noticing is that the queries polling to check if there are new logs don't seem to be cancelled as the query updates. If I run multiple queries I see multiple polling queries running regularly. I can look into making sure these are cancelled.

**Comment by ccschmitz** [comment]
Ended up making [a new ticket](https://github.com/highlight/highlight/issues/6414) to track the issue with polling queries I mentioned in https://github.com/highlight/highlight/issues/6313#issuecomment-1689867350.
