### ISSUE TITLE
Ability to track backend events

### ISSUE THREAD

**Issue by ReDev1L** [highlight/highlight#6318]
**Is your feature request related to a problem? Please describe.**
Analytics software allows to track events from backends, such as "User registered"(after user was created in database without errors). Highlight SDKs don't give such ability. 

**Describe the solution you'd like**
I want method ".track" and plug-ins(amplitude) in backend SDKs =) 

**Describe alternatives you've considered**
I use amplitude sdk at backend.

**Comment by Vadman97** [comment]
Hey @ReDev1L , in the short term, we're not supporting backend events. Would you be able to have your frontend call `H.track` to report those events?

**Comment by Vadman97** [comment]
Understood, this could be a nuance with Remix as a lot more happens server-side that would otherwise be logic on a react frontend.
