### ISSUE TITLE
Add API route instrumentation doc for nextjs app dir

### ISSUE THREAD

**Issue by louis030195** [highlight/highlight#6321]
**Is your feature request related to a problem? Please describe.**

i wont switch from sentry to highlights io because there is no complete doc for latest nextjs

**Describe the solution you'd like**

doc for api route last version of nextjs

**Describe alternatives you've considered**

keep using sentry

**Additional context**

https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js#api-route-instrumentation

eg /pages/api only (old version)

**Comment by deltaepsilon** [comment]
Thanks for the report @louis030195 

Would these two paragraphs make it clearer?

![image](https://github.com/highlight/highlight/assets/878947/2ac583fb-1d11-42a4-90c4-cabcaaaebb0b)

**Comment by deltaepsilon** [comment]
Zoom call feedback notes:

Add a "warning" that `withHighlight` applies to Page Router only.

Add another warning that `instrumentation.ts` applies to both App and Page Router

**Comment by deltaepsilon** [comment]
> Zoom call feedback notes:
> 
> Add a "warning" that `withHighlight` applies to Page Router only.
> 
> Add another warning that `instrumentation.ts` applies to both App and Page Router

@jay-khatri 

How does this look/read for you?

![image](https://github.com/highlight/highlight/assets/878947/80fb8f3f-df10-45a3-84c6-e54e1f68f623)
