### ISSUE TITLE
Starting the service with ./run-hobby.sh has this error, please how to solve it

### ISSUE THREAD

**Issue by wenjian022** [highlight/highlight#6322]
go: downloading github.com/sashabaranov/go-openai v1.10.1
# github.com/highlight-run/highlight/backend/alerts/integrations/discord
alerts/integrations/discord/discord.go:27:22: undefined: errors.Join
note: module requires Go 1.20
failed to build, error: exit status 2
running...
API server listening at: [::]:2345
2023-08-14T01:36:05-07:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
2023-08-14T01:36:05-07:00 info layer=debugger launching process with args: [./tmp/main]
could not launch process: open /usr/local/highlight/backend/tmp/main: no such file or directory

**Comment by Vadman97** [comment]
Hi @wenjian022 

```
alerts/integrations/discord/discord.go:27:22: undefined: errors.Join
note: module requires Go 1.20
failed to build, error: exit status 2
```

The build failed because you are missing the `errors` package because you are on an old Go version. Please upgrade to Go 1.20+
