### ISSUE TITLE
make the quota banner closable

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6336]
we should make the banner closable via a `sessionStorage` setting to make it possible to temporarily clear up the vertical real estate

**Comment by shivam-bit** [comment]
Hey @Vadman97  , could you please provide some clarification regarding the quota banner you mentioned? If you're referring to the one with the attached image, I'd like to inform you that it's already closable, and its state is saved in sessionStorage.
If you're referring to a different banner, I'd be interested in addressing this issue.
<img width="1199" alt="Screenshot 2023-08-15 at 4 47 54 PM" src="https://github.com/highlight/highlight/assets/60030881/e5f9a82b-e2f8-443b-9a81-3ddf62791d79">
