### ISSUE TITLE
Update Alert Designs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6353]
- Add "create alert" flow
 - Add dropdown or select for user alert "type"
 - Alert overview page

**Comment by julian-highlight** [comment]
All designs here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11260-320108&mode=design&t=ePfXNsMj4LBEYzT0-11

cc @eightants
