### ISSUE TITLE
Investigate `instrumentation.ts` vs `withHighlight`

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6361]
We should investigate whether instrumentation.ts throws the same errors as the `withHighlight` request wrapper. If so, we should get rid of any notion of `withHighlight` in our Next docs.

**Comment by jay-khatri** [comment]
We should also update the docs to make it clearer what each of these does:
<img width="194" alt="image" src="https://github.com/highlight/highlight/assets/20292680/e2a11f20-dd28-458b-a501-e5b7ef0132aa">

**Comment by Vadman97** [comment]
done in #6421
