### ISSUE TITLE
revamp embeddings grouping demo page UI

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6375]
Overview: 
- Single Input to  add the error (body)
- Introduction as a description + link to showhn/docs
- After input, List of Tags & similiar errors.
- Not part of app -> No Navigation etc.

Image as reference: 
![image](https://github.com/highlight/highlight/assets/114743131/4c55e778-fa96-4172-a22f-b51daf3fa7fc)

**Comment by julian-highlight** [comment]
Current design state: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11040-311548&mode=design&t=KTNoKYEmMo4l5KRt-11

**Comment by julian-highlight** [comment]
Updated state: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11040-311548&mode=design&t=ePfXNsMj4LBEYzT0-11

Let me know if you need further help here! @deltaepsilon
