### ISSUE TITLE
Investigate slow start times in `highlight-run/next/server`

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6383]
Got a report on [twitter](https://twitter.com/__morse/status/1692594659178999858) that cold starts slow down when we import Highlight. Not sure how much optimization would be required, but its worth taking a look at the very least.

```
import requireSoSlow from 'require-so-slow'

function profileRequire() {
require('@highlight-run/next/server')
requireSoSlow.write('require-trace.cpuprofile')
}

profileRequire()
```

**Comment by Vadman97** [comment]
interesting! our opentelemetry sdk sets up full node auto instrumentation by default; wonder if that could be the slow part
