### ISSUE TITLE
argo helm chart for kubernetes deployments

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6456]
Create a [helm](https://helm.sh/) chart that will deploy the current hobby application in a kubernetes enviornment.
Should deploy infrastructure in a clustered scalable way ([example](https://bitnami.com/stack/kafka/helm)) that would allow to scale out.
Should use shared volumes for backing data stores to allow persisting data.
Should handle some networking setup for routing to the backend / frontend containers.

**Comment by harshbisle** [comment]
Please allow me to give this a shot `/attempt #6456`

**Comment by harshbisle** [comment]
Unfortunately, I've encountered some hardware limitations on my current machine that prevent me from effectively working on this issue. After careful consideration, I've decided to drop this issue to allow someone with the appropriate resources to tackle it effectively. I apologize for any inconvenience this may cause. I'm still eager to contribute to the project in the future and will continue to follow its progress. Thank you!

**Comment by Vadman97** [comment]
Yup, feel free to take it @harishkadamudi. Follow the instructions in the description. First step would be to convert the [hobby docker compose](https://github.com/highlight/highlight/blob/e157c34cf139d87ba1fd221056e98de914fe2b17/docker/compose.hobby.yml#L4) to a helm chart.

**Comment by lksmrqrdt** [comment]
I have been working on a helmet chart as part of my evaluation, independent of the Issue (#6545).
Since I am already in an advanced stage, and there was no visible activity in these according to the bot three days time, I now also participate in this bounty.

**Comment by Vadman97** [comment]
/tip @lksmrqrdt $25
appreciate your work so far moving this forward!

**Comment by yrs147** [comment]
@Vadman97 is this issue still up for grabs ?

**Comment by nis130** [comment]
Hey, @Vadman97 would like to work on it, if it's not already assigned.

**Comment by wvffle** [comment]
Shouldn't this issue be open? Especially as #8221 is still an open draft.
