### ISSUE TITLE
Add ux to inform the user if the sort order on sessions is inversed

### ISSUE THREAD

**Issue by et** [highlight/highlight#6460]
When order is in ascending order
![Screenshot 2023-08-29 at 12 10 05 PM](https://github.com/highlight/highlight/assets/58678/7cb054ec-8e2a-47cb-85b4-b2f9232c9da7)

it's not obvious why there are no recent sessions in the closed state (related [thread](https://highlightcorp.slack.com/archives/C02N2AZS8BV/p1693323470915419)).

Alternatively, we could also consider removing the Order feature entirely. We don't have it for errors and it's hard to justify why someone would want to sort this way.

**Comment by jay-khatri** [comment]
Just talked to @julian-highlight about this. The order feature was added for customers that wanted to go through feature usage in time order. Imo, this might not be worth working on unless its a common problem (we can keep the issue open to see if other folks say anything)? I would think that the user would know they changed the sort order, but not sure.
