### ISSUE TITLE
support simple password authentication for the self-hosted deploy

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6483]
* Add another auth mode alongside [SimpleAuth](https://github.com/highlight/highlight/blob/3f2065161cc25fc1af0c0a342c4df783fe37de38/backend/private-graph/graph/middleware.go#L98-L116) to the private graph middleware that checks that the user is logged in with a password set in the docker compose stack
* If a password is not set in the docker compose environment, simple auth (no auth) should remain the default
* Otherwise, the frontend would ask for the password which will be validated on the backend and create a token that can be used to authenticate further private graph requests.
* The frontend needs to be [updated](https://github.com/highlight/highlight/blob/3f2065161cc25fc1af0c0a342c4df783fe37de38/frontend/src/util/auth.tsx#L38) as well to offer a password-auth mode.

**Comment by jemiluv8** [comment]
I'm working on this.  

/attempt #6483

**Comment by akhill10** [comment]
@Vadman97  I would like to attempt it. Couple of questions before starting:

1. The front end needs to communicate with the backend to validate the password and generate the token. So this query should be on the public graph, right?
2.  For generating the token, is it fine if I use JWT approach?

**Comment by akhill10** [comment]
@Vadman97  Can I go ahead with the above approach?
