### ISSUE TITLE
Twitter logo not updated

### ISSUE THREAD

**Issue by lalitkumawat1m** [highlight/highlight#6488]
## Request
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

## Screenshots
<img width="203" alt="Screenshot 2023-09-01 054046" src="https://github.com/highlight/highlight/assets/91591901/dc05e398-0f59-4552-9077-8c43a489781a">

## Additional Context
Won't change anything in the code as such would replace the twitter-logo.png with a new file. No code will be touched

@Vadman97,
I want to work on this issue please assign this to me.

**Comment by wyenelle** [comment]
I can work on this issue and deliver within a very short time. Please assign me

**Comment by lalitkumawat1m** [comment]
@Vadman97 I want to work on this issue please assign to me ?

**Comment by Vadman97** [comment]
@lalitkumawat1m sounds great, feel free to take this since you reported it.

**Comment by wyenelle** [comment]
Not fair

**Comment by lalitkumawat1m** [comment]
Thanks soon I will raise pr
