### ISSUE TITLE
@highlight-run/node should disable fs instrumentation

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6553]
* `fs` auto instrumentation creates a lot of noise
* we should provide an option to customize which [auto instrumentations are used](https://opentelemetry.io/docs/instrumentation/js/libraries/#registration)

see https://github.com/highlight/highlight/blob/4d5e658dc3094badb9e722d73f64e5b9adce61d9/sdk/highlight-node/src/client.ts#L65-L79
https://discord.com/channels/1026884757667188757/1149197575480680488

**Comment by neo773** [comment]
@Vadman97 Can you assign this to me?

**Comment by Vadman97** [comment]
As a reminder, only the solution of the first person to claim the issue will be considered (assuming their solution is completed within 3 days).

**Comment by ayusham001** [comment]
Hi @Vadman97, I want to remind you that I was the first to submit the PR, but it has not been reviewed yet.
