### ISSUE TITLE
Add callout/testing/configuration to error page to set up GitHub enhanced errors

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#6571]
Service page: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&mode=design&t=209lzjA05zYxpIDn-0

Error page: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11671-692763&mode=design

**Comment by jay-khatri** [comment]
Additionally, having watched your demo video, is there a way to "edit" a stacktrace's github configuration from the error page?
