### ISSUE TITLE
the trace API is not called on the fetch

### ISSUE THREAD

**Issue by Hg6f9** [highlight/highlight#6583]
the trace API is not called on the fetch
 ==> is not returning success or failure, and it seem like the fetch is not called at all.

      ==>     BTW, if make the same request via POSTMAN, it works.  (with the same body)

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/f9186404-d547-4b33-b065-af5391583e0c)

_Originally posted by @alexdoan102 in https://github.com/evanderkoogh/otel-cf-workers/issues/50_ https://goldenhillsventure.live/

**Comment by Hg6f9** [comment]
https://goldenhillsventure.live/[](https://goldenhillsventure.live/)

**Comment by Vadman97** [comment]
not related to highlight

**Comment by Hg6f9** [comment]
> the trace API is not called on the fetch
> 
>  ==> is not returning success or failure, and it seem like the fetch is not called at all.
> 
> 
> 
>       ==>     BTW, if make the same request via POSTMAN, it works.  (with the same body)
> 
> 
> 
> 
> 
> ![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/f9186404-d547-4b33-b065-af5391583e0c)
> 
> 
> 
> _Originally posted by @alexdoan102 in https://github.com/evanderkoogh/otel-cf-workers/issues/50_ https://goldenhillsventure.live/

content/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints.md
