### ISSUE TITLE
Add an "enterprise" tier to our pricing page

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6623]
As discussed in #landing-page-and-docs

**Comment by julian-highlight** [comment]
Yo @Abhishek-More ! I've created a design here: https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?type=design&node-id=5300-44058&mode=design&t=T9plu0nJF85oGcXe-11

cc @jay-khatri
