### ISSUE TITLE
show error boundary feedback on error instances

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6642]
we currently associate error boundary feedback with a session.
we should surface it on the error instance view via that association per [the following design.](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11613%3A575399&mode=dev)

**Comment by SSHari** [comment]
@Vadman97 Is this something that I could work on?

/attempt #6642

**Comment by rishi-raj-jain** [comment]
/attempt #6642

@Vadman97

Can you share a session link that I can view in incognito where it shall be visible when implemented?

Per the design the missing piece is only the part below, correct?

<img width="428" alt="Screenshot 2023-09-22 at 12 12 38 AM" src="https://github.com/highlight/highlight/assets/46300090/389b6f50-3395-42e0-b002-bbf8c29038d2">

**Comment by Vadman97** [comment]
@rishi-raj-jain correct, though may require some backend changes to return information about the session's other errors to find relevant feedback. you'll likely need to spin up the stack locally to test this

here's an example session with an error boundary error. you can see the [feedback in the comments panel](https://app.highlight.io/1/sessions/hUnCGx783Ko4ri7j9UyhIPA5SfNY?page=1&query=and%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-22T20%3A58%3A13.368Z_2023-09-21T20%3A58%3A13.368Z&ts=15.92&commentId=15063) of the session

**Comment by rishi-raj-jain** [comment]
> , though may require some backend changes to return information about the session's other errors to find relevant feedback. you'll likely need to spin up the stack locally to test this

Can you help me with this? I already do start infra, run frontend and run backend. anything else I need to do?

**Comment by rishi-raj-jain** [comment]
> here's an example session with an error boundary error. you can see the [feedback in the comments panel](https://app.highlight.io/1/sessions/hUnCGx783Ko4ri7j9UyhIPA5SfNY?page=1&query=and%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-22T20%3A58%3A13.368Z_2023-09-21T20%3A58%3A13.368Z&ts=15.92&commentId=15063) of the session

Okay yeah I see that, but how do I create one locally, I made some faulty code and it brought up that view in my dev environment and when I submitted it failed to show the same error in /1/sessions page with the filter of has errors: true.

**Comment by rishi-raj-jain** [comment]
@Vadman97

**Comment by rishi-raj-jain** [comment]
@Vadman97 I'd love to work on this. Can you guide me on the above?

**Comment by rishi-raj-jain** [comment]
@Vadman97 I'd love to work on this. Can you guide me on the above?

**Comment by rishi-raj-jain** [comment]
@Vadman97 I'd love to work on this. Can you guide me on the above?

**Comment by rishi-raj-jain** [comment]
@Vadman97 I'd love to work on this. Can you guide me on the above?

**Comment by rishi-raj-jain** [comment]
> here's an example session with an error boundary error. you can see the [feedback in the comments panel](https://app.highlight.io/1/sessions/hUnCGx783Ko4ri7j9UyhIPA5SfNY?page=1&query=and%7C%7Ccustom_created_at%2Cbetween_date%2C2023-08-22T20%3A58%3A13.368Z_2023-09-21T20%3A58%3A13.368Z&ts=15.92&commentId=15063) of the session

Okay yeah I see that, but how do I create one locally, I made some faulty code and it brought up that view in my dev environment and when I submitted it failed to show the same error in /1/sessions page with the filter of has errors: true.

**Comment by Vadman97** [comment]
@rishi-raj-jain does the error show on the `/1/errors` page?

**Comment by jemiluv8** [comment]
@rishi-raj-jain, is it ok if I attempt this.

**Comment by rishi-raj-jain** [comment]
Hey @jemiluv8, I'm still on this.

**Comment by jemiluv8** [comment]
Gotcha.
