### ISSUE TITLE
Add Empty-state for Alerts Onboarding when people already created Alerts

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#6657]
We need to create a screen for the Alerts Onboarding when people already created an Alert from the Alerts page before going to Alerts Onboarding. 

It should say something like 'You've already successfully created an alert' + a CTA that leads the user to the alerts page.

**Comment by julian-highlight** [comment]
Created a design for this usecase. Figma: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11718-697765&mode=design&t=fad58Y3Js4m8N56x-11

@Vadman97 

cc @jay-khatri

**Comment by jay-khatri** [comment]
Here's the doc that we discussed in our last chat @Vadman97 @julian-highlight : https://www.notion.so/runhighlight/alerts-learnings-b0bffee3ebbf456c9c0d6d59e68c5ba1?pvs=4
