### ISSUE TITLE
Update 'Create Project/Workspace' Designs

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#6670]
The old modal view need to be updated with the new design system styles. 

Designs are ready to be implemented here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11718-717530&mode=design&t=fad58Y3Js4m8N56x-11

Placement of the modal + scrim color are defined!

**Comment by jay-khatri** [comment]
related to #6671

**Comment by rishi-raj-jain** [comment]
@jay-khatri @julian-highlight 

I'm nearly done with the code, I have two questions:

# In case of `workspace`:

## The design I've implemented in the screenshot below:
<img width="1512" alt="Screenshot 2023-09-21 at 12 59 36 PM" src="https://github.com/highlight/highlight/assets/46300090/f1c7f5c9-a71f-4f9d-ba3e-853b4c12144a">

-  I see `Use a promo code`, `Enable Auto Join`, and `Suggested Promo Codes` apart from the design you've linked in the issue, can the design be updated to help me know how these shall look, or I shall remove these items from the modal? 
- Also, I don't see `Enter existing workspace` in the design, shall I remove this from the modal or the design will be updated for this?
- Currently, creating workspace always takes me to a new page with the modal, do we want to change this behavior to show modal:
-- in the center of the screen if a new workspace is being created (by default this happens)
-- as a modal on the screen if another workspace is being created when someone already has a workspace set up

# In case of `project`:

## The design I've implemented in the screenshot below:
<img width="1512" alt="Screenshot 2023-09-21 at 1 02 07 PM" src="https://github.com/highlight/highlight/assets/46300090/273e8d97-ef0f-4667-a33b-b70cd2de22de">

- Currently, clicking on create new project always takes me to a new page with the modal, do we want to change this behavior to show modal:
-- in the center of the screen if the first project in a new workspace is being created (by default this happens)
-- as a modal on the screen if another project is being created in a workspace that exists

**Comment by rishi-raj-jain** [comment]
Also, given the questions above, I request you to please extend the deadline to 3 days further (as new design/changes will be there based on my questions above apart from what's mentioned in the issue when created).

**Comment by julian-highlight** [comment]
Hey @rishi-raj-jain ! 
Answering your questions chronologically. 

**Workspace creation**
- Good call to add auto-join. From my perspective this is the only feature I'd add here, as the others are not important for this step. We're using an updated design for auto-join that is a simple checkbox. Updated the designs accordingly. 
- Existing workspace button was added just now. I've simplified the copy to fit the space.
- Yes both modals should be placed on top of a scrim background inside the app, like presented in the designs.

**Project creation**
- Yes, same applies to the project creation. From now on modals will appear inside the app on top of a scrim background.

Thanks for the quick work on this! Looking forward to see the final results 👍

**Comment by rishi-raj-jain** [comment]
@julian-highlight

- Appreciate the detailed response, I've left two comments on Figma. Let me know if you don't see them.
- By scrim background, you mean a placeholder background (that's like layout of what they'll see once they are in a workspace), correct?

**Comment by julian-highlight** [comment]
@rishi-raj-jain no the scrim background is the grey layer that adds a tint. The app in the background should not change! 

Answered the comments in figma as well! 👍

**Comment by rishi-raj-jain** [comment]
Hey @julian-highlight,

> with a checkbox, like in the onboarding flow

Can you share a screenshot of this / figma wireframe with me? Don't want there to be any confusion.

**Comment by rishi-raj-jain** [comment]
> no the scrim background is the grey layer that adds a tint. The app in the background should not change!

Awesome, thanks I just wanted to make sure that I understand the expectation clearly.

**Comment by julian-highlight** [comment]
> Hey @julian-highlight,
> 
> > with a checkbox, like in the onboarding flow
> 
> Can you share a screenshot of this / figma wireframe with me? Don't want there to be any confusion.

Sure! It's this little modal here: 
![image](https://github.com/highlight/highlight/assets/114743131/e5c210a7-90c0-44c5-8c54-4d53509f5ce0)

**Comment by rishi-raj-jain** [comment]
> The app in the background should not change!

There is no elements in the background (in code) currently when someone navigates to create a new workspace/project.

**Comment by julian-highlight** [comment]
> > The app in the background should not change!
> 
> There is no elements in the background (in code) currently when someone navigates to create a new workspace/project.

Saw you found your way around it! Sorry for not seeing your message earlier.

**Comment by rishi-raj-jain** [comment]
> > > The app in the background should not change!
> > 
> > 
> > There is no elements in the background (in code) currently when someone navigates to create a new workspace/project.
> 
> Saw you found your way around it! Sorry for not seeing your message earlier.

Yeah no worries, I have just created intercepting routes so that if there's something in the background, it'll stay.
