### ISSUE TITLE
Update 'Switch Workspace' Flow & Designs

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#6671]
Instead of using the old modal view, we want to use a menu approach, similar to switching projects. 

Designs are ready here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=11718-717005&mode=design&t=fad58Y3Js4m8N56x-11

**Comment by ayusham001** [comment]
Hi @julian-highlight, could you please grant me access to the design?

**Comment by julian-highlight** [comment]
> Hi @julian-highlight, could you please grant me access to the design?

Yo @ayusham001, you should have access now! Sorry that this might take some time sometimes, due to timezones etc. 

Let me know when you need more help on this issue!

**Comment by Vadman97** [comment]
hi @akashsiddamshetty - please reach out on discord at https://community.highlight.io/ in the #contributing channel

docs for self-hosting can be found here: https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide

**Comment by rishi-raj-jain** [comment]
@Vadman97 I'm nearly done adding it to my existing PR

**Comment by rishi-raj-jain** [comment]
Somehow algora /claim #6671 is not working but I've mentioned that in my PR

**Comment by rishi-raj-jain** [comment]
https://github.com/highlight/highlight/pull/6682 is what I'm referring to
