### ISSUE TITLE
Nextjs: No way to call "consumeError"

### ISSUE THREAD

**Issue by Negan1911** [highlight/highlight#6692]
**Describe the bug**
I'm following the guide and trying to use the app router with `serverActions`, but looks like by default, our Server actions errors are not being tracked.

We also can't use `consumeError` to catch the errors since `@highlight-run/next/server` doesn't include it and `@highlight-run/node` fails when being imported on NextJs (because of `ansi-color` using Octal escape characters)

**Comment by farhan787** [comment]
@Negan1911 the octal escape character issue is happening because ansi-color is using old invalid octal character `\033` 
but highlight is using its [local fork ](https://github.com/highlight/highlight/tree/main/forks/ansi-color) and they've locally replaced it with valid escape character `\x1B` (you can see in local fork). 

Some dependency in your next project might still be using ansi-color package and to fix it temporarily you can change the character there in path `node_modules/ansi-color/lib/ansi-color.js`. A [fix PR](https://github.com/loopj/commonjs-ansi-color/issues/15) has been opened here in the original repo as well.

**Comment by perkinsjr** [comment]
Just to add some context. If you create a new app router project, this error occurs. 

Steps to repo:

1. `npx-create-app@latest` 
2. `npm install @highlight-run/next`
3. Add the required highlight features and add a route handler for example

```tsx
import { AppRouterHighlight } from '@highlight-run/next/server'


export const withAppRouterHighlight = AppRouterHighlight({
	projectID: "project_id",
})
```

```tsx
import { NextRequest } from 'next/server'
import { withAppRouterHighlight } from '../../utils/app-router-highlight.config'

export const GET = withAppRouterHighlight(async function GET(request: NextRequest) {
	console.info('Highlighting route')

	if (Math.random() < 0.8) {
		return new Response('Success')
	} else {
		throw new Error('Error')
	}
})

```

5. Error occurs. 

The PR is almost 4 years old, so it unlikely that it will ever be merged at this point.

**Comment by farhan787** [comment]
@perkinsjr I totally missed the PR date, my bad! Thanks for calling out.

**Comment by vhmartinezm** [comment]
Same error

**Comment by deltaepsilon** [comment]
> @Negan1911 the octal escape character issue is happening because ansi-color is using old invalid octal character `\033` but highlight is using its [local fork ](https://github.com/highlight/highlight/tree/main/forks/ansi-color) and they've locally replaced it with valid escape character `\x1B` (you can see in local fork).
> 
> Some dependency in your next project might still be using ansi-color package and to fix it temporarily you can change the character there in path `node_modules/ansi-color/lib/ansi-color.js`. A [fix PR](https://github.com/loopj/commonjs-ansi-color/issues/15) has been opened in the original repo as well.

I figured out how to bundle the `ansi-color` patch into the bundle. It should just work now... if I can ever get these `yarn publish` bugs sorted out 😞

**Comment by deltaepsilon** [comment]
I love OTEL, I really do. But I've had to patching OTEL and Protobuf a fair bit to get Vercel support rolling.
