### ISSUE TITLE
Support Rust among our SDKs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6756]
The SDK should implement the following:

* a way to H.recordException following the otel exception reporting spec.
* a way to instrument Rust logging libraries. if the Rust sdk supports logs natively, it would be great to route them to as LogRecords on v1/logs, but if not, fine to support them as trace events.
as part of the exception implementation, if rust http libraries follow a common format for tracing HTTP request handlers, it would be great to wrap those as native otel traces.

We should build the SDK based on the [opentelemetry sdk](https://opentelemetry.io/docs/instrumentation/rust/). There is a [guide](https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/traceresponse) for rust http specifically, so we should follow best practices here in terms of collecting the available data.

Requirements:

* a init method that sets up the Rust instrumentation to collect console logs automatically.
* a recordException method that allows capturing errors manually (see [java sdk](https://www.highlight.io/docs/sdk/java) as an example).
* Rust HTTP instrumentation that will hook into the framework to collect errors / logs automatically, without the need for a user to manually report errors.

Some getting started pointers on our [docs](https://www.highlight.io/docs/general/company/open-source/contributing/adding-an-sdk)! Please let us know if you have feedback, I'm happy to [add to them](https://github.com/highlight/highlight.io/blob/main/docs-content/general/3_company/open-source/contributing/adding-an-sdk.md).

**Comment by Min2who** [comment]
Hey @jay-khatri is this issue closed ?

**Comment by ishqDehlvi** [comment]
@jay-khatri Is this issue closed??

**Comment by mogery** [comment]
/attempt

Going to target actix and hyper at first for HTTP instrumentation.

**Comment by Rutik7066** [comment]
Hi @jay-khatri, May i work on this issue ?
