### ISSUE TITLE
Next sdk test project build failing

### ISSUE THREAD

**Issue by farhan787** [highlight/highlight#6758]
**Describe the bug**
I was trying to go through the testing process for SDK code changes as [explained here](https://github.com/highlight/highlight/pull/6755#issuecomment-1740024209) and `yarn build:sdk` was successful but `yarn e2e:nextjs` was throwing `'The "use client" directive must be placed before other expressions'` error as `sdk/highlight-next/dist/next-client.js` file contains it twice.

**To Reproduce**

1. Run `yarn build:sdk`
2. Run `yarn e2e:nextjs`
3. Visit `localhost:3005` and check terminal and browser.

**Expected behavior**
Should have shown the error simulator webpage for testing. 

**Screenshots**
![Screenshot 2023-09-29 at 4 25 42 AM](https://github.com/highlight/highlight/assets/38656082/b7ff8303-3e75-4836-a18b-42bc79f1d137)

**Potential Solution**
Passing `minify: true` to `defineConfig` method in `sdk/highlight-next/tsup.config.ts` seems to fix the issue.

![Screenshot 2023-09-29 at 4 31 20 AM](https://github.com/highlight/highlight/assets/38656082/948e3a07-ae9e-42dc-a1c8-55f29f7194a6)

**Comment by deltaepsilon** [comment]
Try pulling main again. I should have this fixed.

You might be getting an error from bin/clean-dist.sh

I used sed to clean up the compiled file, but I've had problems with BSD sed in the past. I use Ubuntu, so it's hard for me to validate it on BSD/MacOS.
