### ISSUE TITLE
Highlight for Startups Page

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#6774]
Creating this one to keep track of feedback etc.

Designs here: https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?type=design&node-id=6365-50308&mode=design&t=M6nUyNKE4NwbaLAa-11

cc @jay-khatri

**Comment by Abhishek-More** [comment]
Completed (almost) all the sections [here](https://highlight-landing-h819p7ewu-highlight-run.vercel.app/startups). Just waiting for updated copy and the image assets @julian-highlight @jay-khatri

**Comment by julian-highlight** [comment]
All pictures done now! @Abhishek-More https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?type=design&node-id=6358-39804&mode=design&t=oe0OoQVqea5jncK3-11
