### ISSUE TITLE
Add note when enhancement did not enhance any files

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#6778]

**Comment by julian-highlight** [comment]
Loom: https://www.loom.com/share/fdd24f641d314e64bc8b68dc2d882178
Figma: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=12153-31850&mode=design&t=b89NvlC8vjf5OSBi-11

Important note: 
The 'external link' buttons should be disabled whenever we can't enhance something. This will also be some sort of an indicator of when enhancement works.

**Comment by SpennyNDaJets** [comment]
![Screenshot 2023-10-04 at 11 33 21 AM](https://github.com/highlight/highlight/assets/17744174/4be99bf9-415e-4cb8-9f4f-454a5fd3c709)

**Comment by julian-highlight** [comment]
Updated the design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=12153-31850&mode=design&t=qRn85LZxOxKkvlQ7-11

Agree that a little callout is much more helpful here. Maybe we can even give a bit of context? @SpennyNDaJets
