### ISSUE TITLE
Types don't work with ESM

### ISSUE THREAD

**Issue by gustavopch** [highlight/highlight#6798]
# Describe the bug
The types are incompatible with ESM because the imports in the `.d.ts` files aren't written in a way that ESM understands.

# To Reproduce

1. Create a Remix project (`npx create-remix@latest`).
2. Ensure `package.json` has `"type": "module"`.
3. Ensure `tsconfig.json` has `"moduleResolution": "nodenext"` (which will make it resolve the types the ES Modules way).
4. Follow the installation instructions of highlight.io for Remix.
5. See the type errors (as showed in the screenshot).

# Expected behavior
All relative paths in the `.d.ts` generated by highlight.io should have the `.js` extension (yes, it must be `.js`, not `.ts`) and never point to a folder.

In other words, this is compatible with ESM:
✅ import foo from './some-file.js
✅ import foo from './some-folder/index.js

And this is incompatible:
❌ import foo from './some-file'
❌ import foo from './some-folder'

# Screenshots
<img width="568" alt="image" src="https://github.com/highlight/highlight/assets/10941958/b4065f6f-df05-42e4-adc6-29d807357833">

<img width="751" alt="image" src="https://github.com/highlight/highlight/assets/10941958/268e8601-9ebc-4f7c-9e11-0d2d3c82c0a9">

The imports above should be changed to:
```diff
-import type { HighlightOptions, HighlightPublicInterface } from '../../client/src/types/types';
-import { HighlightSegmentMiddleware } from './integrations/segment';
-import configureElectronHighlight from './environments/electron';
+import type { HighlightOptions, HighlightPublicInterface } from '../../client/src/types/types.js';
+import { HighlightSegmentMiddleware } from './integrations/segment.js';
+import configureElectronHighlight from './environments/electron.js';
```

# Additional context
It's the same as what was happening in https://github.com/rtivital/mantine-v7/issues/13. Also read https://www.typescriptlang.org/docs/handbook/esm-node.html.

**Comment by deltaepsilon** [comment]
@gustavopch I took a crack at resolving this. Thanks for the detailed notes.

I need to confirm that this doesn't break anything else, because the edited files are core to our product.
