### ISSUE TITLE
Add traces to the landing page product slider

### ISSUE THREAD

**Issue by julian-highlight** [highlight/highlight#6800]
We need to find a way to show Traces in this view and possibly make room for further products: 
![image](https://github.com/highlight/highlight/assets/114743131/2c81a1f9-e8ec-4d24-90bf-bf0763c6ff98)

**Comment by jay-khatri** [comment]
in terms of positioning, get rid of "open source" and replace it with "tracing".

**Comment by jay-khatri** [comment]
swap the "open source" image in place of the self hosting image.

**Comment by jay-khatri** [comment]
should add a "private beta" pill on top of the "traces" text
<img width="426" alt="image" src="https://github.com/highlight/highlight/assets/20292680/12fc0437-a0c0-4ea9-9682-a94936e2c7a2">
