### ISSUE TITLE
polish for @highlight-run/remix SDK

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6834]
The Remix getting started (https://www.highlight.io/docs/getting-started/fullstack-frameworks/remix) seems to be incomplete, for example there's a shellRendered variable that's never changed, but it should (as in https://github.com/highlight/highlight/blob/main/e2e/remix/app/entry.server.tsx).

```[tasklist]
### Tasks
- [ ] unchanged shellRendered
```

**Comment by deltaepsilon** [comment]
@Vadman97 I'm confused. We have `shellRendered` in the docs.

Are there other things missing? Could you link me to the original bug report?

![image](https://github.com/highlight/highlight/assets/878947/4d4a1306-5edf-4e1b-84e7-bb6d5cc8ede3)

**Comment by Vadman97** [comment]
Thanks @deltaepsilon , could you check with https://discord.com/channels/1026884757667188757/1052834249868324895/1159142302753763418 about the request?
