### ISSUE TITLE
Microsoft Teams Integration

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6858]
Add a microsoft teams integration for issue creation.

https://github.com/infracloudio/msbotbuilder-go

Like our other notification integrations (Slack / Discord), we want to be able to:
- all behavior should match with the other integrations (e.g. slack, discord) for comment notification, alert notifications, alert creation, etc.
- we should allow saving the bot configuration on each alert type or other notification destination. follow the code where other discord / slack configuration is defined.
- for local testing, you can create your own Microsoft Teams Bot (https://learn.microsoft.com/en-us/microsoftteams/platform//sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode#register-your-web-service-with-the-bot-framework) and use your own client id / secret; before we deploy this integration in production, you can share your integration's settings with us and we will create a Highlight Oauth app with matching settings

Bounty: $200
cc @jemiluv8

**Comment by jay-khatri** [comment]
similar to #5787

**Comment by jemiluv8** [comment]
I've started work on this. Will send an update as soon as I make significant progress.

**Comment by jemiluv8** [comment]
@Vadman97, I've made some progress and have recorded two demo videos below.

**Summary of Demo**
The teams integration is currently done in two steps
1. Use frontend teams integration to give "admin consent" to intereact with a user's tenant - we acquire and store the tenantId on the workspace here.
2. Bot installation. Our bot will be available on the microsoft teams store once published. But for local testing, I use another option to "upload" custom application. This essentially contains assets and a metadata about the bot. Once the bot has been successfully installed we send the message below
<img width="618" alt="Screenshot 2023-12-12 at 12 43 23 AM" src="https://github.com/highlight/highlight/assets/119384208/a7764d99-0678-4ffa-bcee-ee326ee498f9">

### Links to Videos
[STEP 1 - Frontend Integration to set TenantID](https://drive.google.com/file/d/1t4ATczCfW5oo0mzEHG7Fd0J2N0papDfn/view?usp=sharing)
[STEP 3 - Bot Installation and final confirmation](https://drive.google.com/file/d/1fQO9XQutz7Gpz-pVbfxo9AK03ixyS9to/view?usp=sharing)


I've been looking into various ways to make this a one-step process. Ultimately I believe that our best option is to initiate the bot installation once the integration is complete on the frontend. This will just take the user to their teams app and they will choose which team to "add" the bot to.

#### PS: I'll send another update on friday.

**Comment by Vadman97** [comment]
thanks @jemiluv8 , very cool!

**Comment by jemiluv8** [comment]
### Friday Update

I've implemented sending log alerts to teams channels (pending tests). There a still more alert "types" to implement and test. I've been following the design of messages sent by the discord bot. As can be seen from the screenshot below.

<img width="608" alt="Screenshot 2023-12-15 at 10 48 39 PM" src="https://github.com/highlight/highlight/assets/119384208/838dcb69-226c-4370-a727-7a86164dbba5">

### Design of Cards
Not sure if @julian-highlight might have some design suggestions regarding messages sent via the ms teams bot.
Teams bots can send messages using [adaptive cards](https://www.adaptivecards.io). Julian can use the [adaptive cards designer](https://www.adaptivecards.io) to come up with designs for session alerts, error alerts e.t.c.

### Next Steps
I will give more frequent updates going forward

**Comment by julian-highlight** [comment]
@jemiluv8 thank you! Will take a look, unsure about the prio of this though. @Vadman97 any idea?

**Comment by jemiluv8** [comment]
@Vadman97, the PR is finally ready for review.
@julian-highlight, here are some samples of the messages
the teams bot sends. I'm not sure if design input is required 
here.

### Sample Messages
<img width="941" alt="Screenshot 2024-01-03 at 6 00 02 PM" src="https://github.com/highlight/highlight/assets/119384208/c546879e-db0b-42b3-93c5-1d7b0337213f">
<img width="925" alt="Screenshot 2024-01-03 at 6 00 24 PM" src="https://github.com/highlight/highlight/assets/119384208/03c538f0-f6da-45c1-9bb8-7865aacf21b7">
<img width="489" alt="Screenshot 2024-01-03 at 6 00 38 PM" src="https://github.com/highlight/highlight/assets/119384208/4ae9d7dd-1b4c-4d6c-b46c-98e31ffd4906">
<img width="952" alt="Screenshot 2024-01-03 at 6 00 45 PM" src="https://github.com/highlight/highlight/assets/119384208/fc035f94-40bc-4ccb-b873-4a5cef8fcc87">
<img width="919" alt="Screenshot 2024-01-03 at 6 01 05 PM" src="https://github.com/highlight/highlight/assets/119384208/983a03a3-b7ab-4fb8-8c53-f7d5bddb1b8c">
