### ISSUE TITLE
Unable to find or import withHighlightConfig

### ISSUE THREAD

**Issue by albertilagan** [highlight/highlight#6903]
```
import { withHighlightConfig } from "@highlight-run/next/config";
```

**Error**
`Module '"@highlight-run/next/config"' has no exported member 'withHighlightConfig'.`

**Version**
```
"@highlight-run/next": "7.0.0",
```

**Screenshot**
<img width="1450" alt="image" src="https://github.com/highlight/highlight/assets/22500561/697c3b43-4b2f-4774-8fe8-f518be5c93a8">

**Comment by 7iomka** [comment]
Hi. When you plan to publish this change?
I have this error when I tried to use with next.js
