### ISSUE TITLE
How to set environment from Golang code

### ISSUE THREAD

**Issue by mauleyzaola** [highlight/highlight#6938]
**Is your feature request related to a problem? Please describe.**
Neither, most likely a gap in the documentation.

**Describe the solution you'd like**
I've read about `Environmens` here: https://www.highlight.io/docs/general/product-features/general-features/environments but this is for the Frontend. How can I set this value in the Backend (Go)?

**Describe alternatives you've considered**
Went through the highlight sdk for Go, but didn't find anything related to this.

**Additional context**
N/A

**Comment by Vadman97** [comment]
Hi @mauleyzaola - here is the doc https://www.highlight.io/docs/sdk/go#highlightStart
If you'd like, please open a PR [to edit the file you mention](https://github.com/highlight/highlight/blob/main/docs-content/general/6_product-features/3_general-features/environments.md) to add language-specific examples.
