### ISSUE TITLE
withHighlightConfig not uploading sourcemaps

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#6939]
a customer reported that `withHighlightConfig` is not sending sourcemaps when `productionBrowserSourceMaps: false` is set (https://app.highlight.io/17249/settings/errors). Could we validate that the next sdk correctly uses the @highlight-run/sourcemap-uploader? Perhaps this could be an automated test.

**Comment by deltaepsilon** [comment]
I'm having trouble reproducing.

![image](https://github.com/highlight/highlight/assets/878947/21f9a6a4-931a-4d16-8017-4ddfb73f20dd)


Can you confirm with the client that they have the following conditions met?

1. `HIGHLIGHT_SOURCEMAP_UPLOAD_API_KEY` in the environment or pass in `apiKey` to the second argument of `withHighlightConfig`.
2. Make sure that they're passing in `uploadSourceMaps`.
3. `NODE_ENV` must be `production`.
4. `nextConfig.productionBrowserSourceMaps` must be `false`

Example with `apiKey` passed in: `withHighlightConfig(nextConfig, { apiKey: 'asdf', uploadSourceMaps: true })`

Live example in e2e sandbox:

Note that `HIGHLIGHT_SOURCEMAP_UPLOAD_API_KEY` must be injected into environment variables. Also `NODE_ENV=production`.

```javascript
// next.config.mjs
import { withHighlightConfig } from '@highlight-run/next/config'

const nextConfig = {
	experimental: {
		appDir: true,
		instrumentationHook: false,
	},
	productionBrowserSourceMaps: false,
	images: { domains: ['i.travelapi.com'] },
}

export default withHighlightConfig(nextConfig, {
	uploadSourceMaps: true,
})

```
