### ISSUE TITLE
SSR error catch not working in nextjs (old pages not appDir)

### ISSUE THREAD

**Issue by lveillard** [highlight/highlight#7010]
**Describe the bug**
Hello! I'm following the instructions to catch SSR errors but for some reason they don't seem to work, at least in development

**To Reproduce**
- Custom _error page:
```
import NextError from 'next/error';
import type { HighlightErrorProps } from '@highlight-run/next/client';
import { H, getHighlightErrorInitialProps } from '@highlight-run/next/client';

export default function CustomError({ errorMessage, statusCode }: HighlightErrorProps) {
	/// needs to be init again because this is SSR
	H.init(process.env.NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID);
	H.consumeError(new Error(errorMessage));

	return <NextError statusCode={statusCode} />; // Render default Next error page
}

CustomError.getInitialProps = getHighlightErrorInitialProps;
```
Then throw an error in getServerSideProps
```
export const getInitialProps = async (context) => {
	throw new Error('Forced SSR Error');
};

export default MyPage;
```
**versions**
- "@highlight-run/next": "^7.0.0",
- "next": "13.5.4",

**Expected**
- The error should be catched (the other errors do)

**Documentation**
I find there are 2 key things missing in the nextjs documentaiton
- how to test this particular SSR error catch
- how to build sourcemaps specifically for nextjs (or even having a tool like sentry to automatically generate and send them)

**Comment by Vadman97** [comment]
Hey @lveillard , can you confirm that you experience this issue with "@highlight-run/next": "7.0.2"? "7.0.1" introduced some important bugfixes to the server-side capture

**Comment by lveillard** [comment]
> Hey @lveillard , can you confirm that you experience this issue with "@highlight-run/next": "7.0.2"? "7.0.1" introduced some important bugfixes to the server-side capture

Not getting any errors with 7.0.2 neither but maybe getServerSide props is not supposed to be catched like this?

Also, not sure if related but with 7.0.2 as well, creating my page-router-highlight-config.ts i get another error

Unable to resolve path to module '@highlight-run/next/server'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.29.0/docs/rules/no-unresolved.md)
module "C:/Users/{stuff}/node_modules/.pnpm/@highlight-run+next@7.0.2_@opentelemetry+api@1.6.0_next@13.5.4_react-dom@18.2.0_react@18.2.0_typescript@5.2.2/node_modules/@highlight-run/next/server"

Added `// eslint-disable-next-line import/no-unresolved` to silence it because contrary to the getServerSideProps stuff, this is actually logging the api routes properly

**Comment by deltaepsilon** [comment]
There's a gotcha that I'm working to document better.

Try running `npm run build && npm run start` instead of `npm run dev`.

React will catch the SSR errors on its own in dev, so you'll never get to the `_error.tsx` page.

@lveillard, can you confirm that this is (or isn't) the issue?

**Comment by lveillard** [comment]
It works. I'm catching it. As long as it works in production it's fine thanks

What about this:
```
Unable to resolve path to module '@highlight-run/next/server'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.29.0/docs/rules/no-unresolved.md)
module "C:/Users/{stuff}/node_modules/.pnpm/@highlight-run+next@[7.0.2_@opentelemetry](mailto:7.0.2_@opentelemetry)+api@1.6.0_next@13.5.4_react-dom@18.2.0_react@18.2.0_typescript@5.2.2/node_modules/@highlight-run/next/server"
```

Thank you!

**Comment by lveillard** [comment]
Seems to finally be working with 7.2.2!
