### ISSUE TITLE
Add numeric "greater than" and "less than" functionality to search

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#7023]
Allow users to input a numerical value and a computation type (i.e. less than, greater than, equal, not equal?), to return respective logs/traces

**Comment by jay-khatri** [comment]
![image](https://github.com/highlight/highlight/assets/20292680/ef9aa119-6eb9-4542-993d-4cbbaf60cda0)

 https://highlightcorp.slack.com/archives/C059NFA87EG/p1701161237858459?thread_ts=1700350800.847559&cid=C059NFA87EG

**Comment by Vadman97** [comment]
When we get to this, I think we also need the ability to search with custom units. For example, for `duration` or other time keys, it would be useful to search by shorthand time syntax such as `m` or `h`. We should also double check that all structured attributes are searchable on traces.

**Comment by jay-khatri** [comment]
will this work for both logs and traces?
