### ISSUE TITLE
Improve support for relative times across searches

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#7027]
Refreshing the page will change the "Last 24 hours" label to a fixed time range. Update to support keeping relative time ranges fixed when refreshing page or linking to search

Something to investigate: “See more” resets the selected date to the default.

> We should also look at disabling the polling queries when a fixed date range is selected. Thinking this will be easier after this is implemented because we can't tell when someone selects a specific time range vs selecting a relative time frame.

Possibly related:
Traces bug - Dragging on time does not change time label

**Comment by jay-khatri** [comment]
From a customer

```
The date picker is very finicky
It allows me to select a day that is before the first day that I select in the range. Example: selecting November 27th first shouldn’t allow me to select any days before November 27th.
If I select a day, I can’t select the same day again. I want to be able to do this so that I can look at the logs for a single day (12:00 AM - 11:59 PM). I also want to be able to select a single day for the start & end so that I can further customize the time range after I select it.
```

https://highlightcorp.slack.com/archives/C059NFA87EG/p1701161237858459?thread_ts=1700350800.847559&cid=C059NFA87EG

**Comment by ccschmitz** [comment]
We should also look at disabling the polling queries when a fixed date range is selected. Thinking this will be easier after this is implemented because we can't tell when someone selects a specific time range vs selecting a relative time frame.
