### ISSUE TITLE
Support saved search segments for logs

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#7030]

**Comment by willmclellarn** [comment]
following!

**Comment by willmclellarn** [comment]
I would also say the very worst (sorry!) part of the logging interface is you can't change the time interval, after inputting a search. The UI goes completely haywire....smh

**Comment by willmclellarn** [comment]
Yo, sick boys! So cool to see this happen real time.

**Comment by willmclellarn** [comment]
<img width="715" alt="Screenshot 2024-01-03 at 9 07 48 PM" src="https://github.com/highlight/highlight/assets/9322548/e0ff2efa-738e-4cb2-99e6-56dd467c03fe">

was trying this out, but keep getting 422 error.

logged out, lggged back in....no dice

**Comment by Vadman97** [comment]
@willmclellarn this should not be resolved. please give this another try!

**Comment by Vadman97** [comment]
> I would also say the very worst (sorry!) part of the logging interface is you can't change the time interval, after inputting a search. The UI goes completely haywire....smh

@willmclellarn do you mind sharing a loom video of what you mean? we support changing the time range via the picker on the right

**Comment by willmclellarn** [comment]
Ok, this seems to be working well now…if I see it again, I'll make a loom.

Segments are working too, great!
