### ISSUE TITLE
Python Tracing SDKs

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#7060]
- [x] Django
- [x] FastAPI
- [x] Flask
- [x] Celery
- [x] requests
- [x] boto3
- [x] Redis
- [x] SqlAlchemy

**Comment by SpennyNDaJets** [comment]
Did some pairing with @Vadman97 - we want to be able to pass in the session id and trace_id through different services (of the same project?) if it matches a url set in the `CROSS_ORIGINS_URLS` (name wip)
