### ISSUE TITLE
Module '"@highlight-run/next/ssr"' has no exported member 'pageRouterCustomErrorHandler'.ts(2305)

### ISSUE THREAD

**Issue by lveillard** [highlight/highlight#7084]
Hello! First of all after some days using highlight i'm really happy with it, keep the good work!

I'm facing this issue when updating from @highlight-run/next 7.0.2 to 7.1.1 

`Module '"@highlight-run/next/ssr"' has no exported member 'pageRouterCustomErrorHandler'.ts(2305)`

Indeed checking the dist folder things, it seem not coherent. Or documentation is not updated. I'm importing it like this

`import { pageRouterCustomErrorHandler } from '@highlight-run/next/ssr';`

While this is a little change, is a breaking change, it would be amazing if the packages follow the Semver standard (FAIL.FEAT.FIX) 

The jump from 7.0.1 to 7.1.0 has some breaking changes which means the previous design was a FAIL.  React hooks arrived on React 16.8.0 , big features only bump the first number if they break things. 

Adopting semvar and some type of documentation auto update (https://sweep.dev/ for instance) to remove all reference to old functions and explain the new changes would be great.

Thanks!

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
@lveillard apologies for the spam messages. We're working on a small bot to make issue triaging easier and it went a bit rogue 😅.

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by 7iomka** [comment]
The same issue.
I'm extremely surprised that the minor version completely updated the example in the documentation without making it fully working. How can you fix it?

**Comment by lveillard** [comment]
For more context, the new import targets to this declaration file
![image](https://github.com/highlight/highlight/assets/29461076/5857c05a-f57e-408e-877a-07efd0a0607b)

Which is targetting nothing (can't follow /dist/ssr)

**Comment by 7iomka** [comment]
Any news on this?

**Comment by twalker1998** [comment]
Version 7.2.0 appears to have /dist/ssr. Was trying to import `appRouterSsrErrorHandler` and `AppRouterErrorProps`,  and got a similar error. Updating to 7.2.0 was the only thing that fixed it for me.

**Comment by lveillard** [comment]
Closing because this is "fixed". 
7.2.1 + nextjs 14.0.2 introduces a new error tho:
https://github.com/highlight/highlight/issues/7118
