### ISSUE TITLE
[Feature Request] Logs - Custom levels

### ISSUE THREAD

**Issue by lveillard** [highlight/highlight#7097]
Hello!
Currenly all the levels in winston (probably also in other libs) seem to be mapped to "info" when unknown. 

It would be great to be able to customize the levels somehow, maybe a V0 which actually prints the name of the level would do.

Or a lttle configuration place where we can assign a string to each level's number + a color code. That would be the best.

Thanks!

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment]
@Vadman97 do we support customization in any of our SDKs atm? I guess this should be some sort of requirement when adding new SDKs. I.e. if a logging lib has a notion of level, we should use that (rather than any customization)? Would that solve your case @lveillard?

**Comment by lveillard** [comment]
I see, it's ok thanks. For the logs we might use a different provider while it gets more developped in highlight.io.

Thanks!
