### ISSUE TITLE
Add zoom/pan slider on flame graph

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#7102]
Adding explicit controls to the flame graph to zoom in/out/left/right (e.g. +/-/->/<-)

Conversation needed with design

**Comment by ccschmitz** [comment]
One thing I think would be useful is adding the ability to click and drag to select an area to zoom into zoom on the flame graph, similar to what we have on dashboards. I think we could also permanently show the scrollbar (will require some custom styling of the scrollbar in Chrome) and add some helper text letting people know they can hold control + scroll up/down to change the zoom.

**Comment by ccschmitz** [comment]
I ended up adding the scrollbar styles to match what we have in other areas of the app in #7182. I think this moves us in a good direction, but should still work to improve the zoom controls.

**Comment by julian-highlight** [comment]
Yo @ccschmitz ! Thanks for your work here so far. I've created a little loom to shine light on my perspective on this: https://www.loom.com/share/92c791fd0eff4caebb59c1446cd693b3

Feel free to click around the design here: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=13237-592817&mode=design&t=bKfleQLZ2KbrIGnb-11

**Comment by ccschmitz** [comment]
Nice - thanks for sharing, @julian-highlight! Left a thought in Figma, but was also curious what you think about the click + drag to select an area to zoom into 🤔

**Comment by julian-highlight** [comment]
> Nice - thanks for sharing, @julian-highlight! Left a thought in Figma, but was also curious what you think about the click + drag to select an area to zoom into 🤔

Not a huge fan of that kind of functionality, as it has a high risk of accidental use. I always feel like functionality like this is feeling super unclean, as it could interfere with other clicking actions. Would rather have precise and clear options for zooming here, like buttons or handles, that have a defined space for interaction! @ccschmitz
