### ISSUE TITLE
7.2.0 nextjs in page mode (not app dir) throws error at build "Dynamic require of "react" not supported" (new 7.2.1 error)

### ISSUE THREAD

**Issue by lveillard** [highlight/highlight#7118]
Hello

The last version of the nexjs packages solved some of the issues but added a new one, adding this piece of code

```
export async function register() {
	const { registerHighlight } = await import('@highlight-run/next/server')

	registerHighlight({
		projectID: CONSTANTS.NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID,
		serviceName: 'my-nextjs-backend',
	})
}
```

or this one if you like the arrow style
```
export const register = async () => {
	const { registerHighlight } = await import('@highlight-run/next/server');

	registerHighlight({
		projectID: 'jd4xw9xg',
		serviceName: 'builder-api',
	});
};
```

Causes this error on build time :

```
Dynamic require of "react" is not supported
builder:build:     at file:///C:/Users/{...}/node_modules/.pnpm/@highlight-run+next@7.2.0_@opentelemetry+api@1.6.0_postcss@8.4.31_react-dom@18.2.0_react@18.2.0_typescript@5.2.2/node_modules/@highlight-run/next/dist/chunk-PEPCKAAO.js:1:744
```

**Comment by jay-khatri** [comment]
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by lveillard** [comment]
Also the page router pages talks about the app router here: which is confusing:

![image](https://github.com/highlight/highlight/assets/29461076/7915431e-59b5-4761-949c-8dd7c07faed1)

**Comment by lveillard** [comment]
Sorry i was wrong, this is the code that triggers that issue, is the _error page

![image](https://github.com/highlight/highlight/assets/29461076/5f06ffdb-22aa-4e46-8907-35795800d6d9)

**Comment by lveillard** [comment]
In case it helps, this is the way Sentry solved this side:

```
const MyError = ({ statusCode /*,hasGetInitialPropsRun, err */ }: AppErrorProps) => {
	return <NextErrorComponent statusCode={statusCode} />;
};

MyError.getInitialProps = async (context: any) => {
	const errorInitialProps = (await NextErrorComponent.getInitialProps(context)) as AppErrorProps;
	errorInitialProps.hasGetInitialPropsRun = true;
	
  if (res?.statusCode === 404) {
    return errorInitialProps;
  }


  if (err) {
    Sentry.captureException(err);
    await Sentry.flush(2000);
    return errorInitialProps;
  }

	return errorInitialProps;
};

export default MyError;
```

**Comment by lveillard** [comment]
Updating to 7.2.1 throws a different error instead:

unhandledRejection Error [ERR_MODULE_NOT_FOUND]: Cannot find module 

'C:\Users\...\node_modules\.pnpm\node_modules\next\error'
imported from 

C:\Users\....\node_modules\.pnpm\@highlight-run+next@7.2.1_@opentelemetry+api@1.6.0_postcss@8.4.31_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules\@highlight-run\next\dist\ssr.js    

Did you mean to import 
next@14.0.2_@babel+core@7.23.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/error.js?

**Comment by ritvij14** [comment]
> Updating to 7.2.1 throws a different error instead:
> 
> unhandledRejection Error [ERR_MODULE_NOT_FOUND]: Cannot find module
> 
> 'C:\Users...\node_modules.pnpm\node_modules\next\error' imported from
> 
> C:\Users....\node_modules.pnpm@highlight-run+next@[7.2.1_@opentelemetry](mailto:7.2.1_@opentelemetry)+api@1.6.0_postcss@8.4.31_react-dom@18.2.0_react@18.2.0_typescript@5.2.2\node_modules@highlight-run\next\dist\ssr.js
> 
> Did you mean to import next@[14.0.2_@babel](mailto:14.0.2_@babel)+core@[7.23.3_@opentelemetry](mailto:7.23.3_@opentelemetry)+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/error.js?

@lveillard I am facing the same issue in my project:

```bash
Collecting page data  .Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/ritvij14/Desktop/Projects/example-web/node_modules/next/error' imported from /Users/ritvij14/Desktop/Projects/example-web/node_modules/@highlight-run/next/dist/ssr.js
Did you mean to import next/error.js?
    at finalizeResolution (node:internal/modules/esm/resolve:255:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/ritvij14/Desktop/Projects/example-web/node_modules/next/error'
}
unhandledRejection Error: Failed to collect page data for /_error
    at /Users/ritvij14/Desktop/Projects/example-web/node_modules/next/dist/build/utils.js:1171:15 {
  type: 'Error'
}
   Collecting page data  .%                                                                                                                                                 
```

Did you find a resolution for this error?

**Comment by lveillard** [comment]
Nope, i just commented it until getting a fix :S

**Comment by lveillard** [comment]
@ritvij14 7.2.2 does fix it for me. Does it for you? if yes I will close the issue :)

**Comment by ritvij14** [comment]
@lveillard I will check it and get back to you in some time

**Comment by ritvij14** [comment]
@lveillard just checked my branch, I am actually already using 7.2.2 and still facing the issue

**Comment by jay-khatri** [comment]
Thanks all. We'll take a look this upcoming week and get back!

**Comment by Vadman97** [comment]
Hey @lveillard , could you try with [7.2.3](https://www.npmjs.com/package/@highlight-run/next/v/7.2.3)? We've ensured `react` is externally referenced which should fix the issue.

**Comment by lveillard** [comment]
Same. The development environment throws no error but i get the same error on Build

```
unhandledRejection Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/node_modules/.pnpm/node_modules/next/error' imported from /app/node_modules/.pnpm/@highlight-run+next@7.2.3_@opentelemetry+api@1.6.0_postcss@8.4.31_react-dom@18.2.0_react@18.2.0_typescript@5.3.2/node_modules/@highlight-run/next/dist/ssr.js
```

**Comment by Vadman97** [comment]
hey @lveillard @qu8n what version of next.js are you guys on?

**Comment by lveillard** [comment]
> hey @lveillard @qu8n what version of next.js are you guys on?

"next": "14.0.3", 
But it happened also before updating to 14, and also in 14.0.1

**Comment by deltaepsilon** [comment]
@lveillard I wish I could see your filesystem!

Let's write this out and see if we can discover what's going wrong.

As best as I can understand, `@highlight-run/next/ssr` is attempting to resolve `import NextError from 'next/error'`, so it'll keep going up the folder tree until it finds a `node_modules` that has a `node_modules/next/error` export.

So I'm betting that you're in a monorepo or something similar, and there's no `/app/node_modules/next` folder. You can try adding a `.npmrc` to the root of your monorepo and adding `node-linker=hoisted` as [documented by pnpm](https://pnpm.io/npmrc#node-linker).

We may need to add `next` as a peer dependency. That might help `pnpm` link it better???

I'll experiment with adding the `next` peer dependency and push it with the next release if it makes sense.

Let me know how it goes!

**Comment by lveillard** [comment]
Happy to test it once is there. Also I'm ok sharing my screen and debugging it together if you're not able to reproduce it.

**Comment by deltaepsilon** [comment]
@lveillard I added `next` as a `peerDependency` of `@highlight-run/next`, which I'm hoping will resolve your issue.

Can you give it another look?

**Comment by Vadman97** [comment]
Hey @lveillard - this should be fixed with the latest version of the SDK. Let us know if you still have issues.

**Comment by lveillard** [comment]
Hello, thanks! Just tried to update it to 7.3.1

I got errors in vscode
```
Module '"@highlight-run/next/ssr"' has no exported member 'PageRouterErrorProps'.ts(2305)
```

With this code:
```
import type { PageRouterErrorProps } from '@highlight-run/next/ssr';
import { pageRouterCustomErrorHandler } from '@highlight-run/next/ssr';
import NextError from 'next/error';

export default pageRouterCustomErrorHandler(
	{
		projectId: '...',
		serviceName: 'Builder',
		// ...otherHighlightOptions
	},
	(props: PageRouterErrorProps) => <NextError {...props} />,
);
```

And I get this error on build:
```
 unhandledRejection Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\.......\node_modules\.pnpm\@highlight-run+next@7.3.1_@opentelemetry+api@1.6.0_next@14.0.3_postcss@8.4.31_react-dom@18.2._2aevp5zyxtafsgeqzkmp6ttnsu\node_modules\next\error' imported from C:\Users\lveil\Desktop\Proyectos\blitz\node_modules\.pnpm\@highlight-run+next@7.3.1_@opentelemetry+api@1.6.0_next@14.0.3_postcss@8.4.31_react-dom@18.2._2aevp5zyxtafsgeqzkmp6ttnsu\node_modules\@highlight-run\next\dist\ssr.js
 ```

**Comment by MJSPollard** [comment]
I am also getting a similar issue so it seems there are some issues with highlight and pnpm as a whole not being able to resolve imports on build. The related issue is #7280 . Has anyone been able to get this package to fully work with pnpm before?

**Comment by lveillard** [comment]
@deltaepsilon @Vadman97 
This is still an issue for those using pnpm, how can I help? I would be happy to share my screen or more context if needed.
