### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by alexanderadam** [highlight/highlight#7146]
**Is your feature request related to a problem? Please describe.**

Pretty much the same way like [the GitHub integration](https://www.highlight.io/docs/general/integrations/github-integration) but for GitLab.
Many companies use own instances for privacy reasons and I guess it's the most popular FOSS solution with most features and integrations anyway and numbers from 2021 show that

> [GitLab has an estimated 30 million registered users, with 1 million being active licensed users](https://en.wikipedia.org/wiki/GitLab).

So I'd guess that there might be some that would be interested in using highlight.io too. 😉 

**Describe the solution you'd like**

The [same integration as for GitHub](https://www.highlight.io/docs/general/integrations/github-integration). The [API is well documented](https://docs.gitlab.com/ee/api/) but there are probably also a bunch of libraries out there if you prefer that.

**Describe alternatives you've considered**

I'm not sure what I'm supposed to write here. 🤷🏻‍♂️

**Comment by jay-khatri** [comment]
Thanks @alexanderadam, will keep you updated on this issue as we prioritize!

**Comment by jay-khatri** [comment]
@mayberryzane perhaps something to prioritize next month?

**Comment by mayberryzane** [comment]
Similar to the other issue tracker integrations, e.g. #5787 , we want to add the ability to create issues in GitLab from sessions and errors.

Like our other issue tracker integrations, we want to be able to:
- add, configure, and remove the GitLab integration from our integrations page https://github.com/highlight/highlight/blob/main/highlight.io/pages/integrations.tsx#L1 ; adding the integration will save an authorization token at the workspace level that can be used to make requests to the GitLab API for creating issues
<img width="703" alt="Screen Shot 2023-09-18 at 9 46 04 AM" src="https://github.com/highlight/highlight/assets/86132398/4f655b0f-7b40-4b9b-848e-8cd3c4e88492">

- create a GitLab issue from a session comment (a new comment on the session player or an existing comment in the right panel)
<img width="465" alt="Screen Shot 2023-09-18 at 9 45 00 AM" src="https://github.com/highlight/highlight/assets/86132398/8e9218fc-12e2-4e25-9bfc-28d9d61c5dd4">
<img width="302" alt="Screen Shot 2023-09-18 at 9 50 00 AM" src="https://github.com/highlight/highlight/assets/86132398/79041ede-b343-48b4-9859-c5dee2d46da9">

- create a GitLab issue from an error
<img width="353" alt="Screen Shot 2023-09-18 at 9 45 21 AM" src="https://github.com/highlight/highlight/assets/86132398/fe434ef3-5cf4-45e2-bfd4-8784934916fd">

- all behavior should match with the other integrations (e.g. clickup, height, github) for linking out to issues from Highlight, removing issues, etc

**Comment by Min2who** [comment]
can i work on it?

**Comment by Min2who** [comment]
As the issue will require considerable amount of work it will be nice if its assigned to someone

**Comment by rajdip-b** [comment]
@jay-khatri hey there! I have had quite some experience in hosting and managing a self-hosted version of GitLab at my organization. That might give me the extra edge! Might I give this a shot?

**Comment by ezhil56x** [comment]
@adelinaenache 

Have you made any progress or still working on this?

**Comment by subh-cs** [comment]
Hi, I'm working on this
/attempt #7146

**Comment by kritarth2121** [comment]
Hi, I'm working on this
/attempt https://github.com/highlight/highlight/issues/7146

**Comment by mayberryzane** [comment]
Hi @adelinaenache - just checking in, how is progress going on this issue? Anything I can assist with?

**Comment by adelinaenache** [comment]
Hi @mayberryzane! Still working on it, had some trouble with running the dev setup but I am good now. Might take 1-2 days more

**Comment by adelinaenache** [comment]
@ezhil56x yes

**Comment by subh-cs** [comment]
Hi @adelinaenache, if you don't mind, can you give an update on this one? Is there any issue you're facing or something else?

**Comment by Rutik7066** [comment]
/attempt #7146
half of the work is done.

**Comment by alexanderadam** [comment]
Nice, I hope that someone considers implementing [the OIDC issue](https://github.com/highlight/highlight/issues/7145), too.
Thank you for your work @jemiluv8 :raised_hands:
