### ISSUE TITLE
Jira integration bug

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [highlight/highlight#7258]
**Describe the bug**
The Jira integration is not working. It outputs this error message in console:

> Error: error creating Jira task: Jira API responded with error; status_code=400 Bad Request; body={"errorMessages":[],"errors":{"issuetype":"The issue type selected is invalid."}}

**To Reproduce**

1. Go to 'Create issue'
2. Click on 'jira issue'
3. Click submit

**Expected behavior**
It should send the ticiket to Jira.

I think there is a misconfiguration or your end, about the issueId.

**Comment by Vadman97** [comment]
Hey @AndreaPontrandolfo , thanks for the report - we'll take a look at this soon. Do you mind providing the full POST payload of the pri.highlight.io network request where you see that error? ie. 
![Screenshot from 2023-12-04 10-12-33](https://github.com/highlight/highlight/assets/1351531/b79696ad-7e36-4214-a7b2-3e1ecab5e052)

**Comment by AndreaPontrandolfo** [comment]
Sure

{
    "operationName": "CreateErrorComment",
    "variables": {
        "project_id": "15684",
        "error_group_secure_id": "ocnUqriUSNCfaLXaY3nrxkFAJsVQ",
        "text": "Open in Highlight",
        "text_for_email": "Test",
        "error_url": "https://app.highlight.io/15684/errors/ocnUqriUSNCfaLXaY3nrxkFAJsVQ",
        "tagged_admins": [],
        "tagged_slack_users": [],
        "author_name": "Andrea Pontrandolfo",
        "integrations": [
            "Jira"
        ],
        "issue_title": "No currency found!",
        "issue_team_id": "10003",
        "issue_description": ""
    },
    "query": "mutation CreateErrorComment($project_id: ID!, $error_group_secure_id: String!, $text: String!, $text_for_email: String!, $tagged_admins: [SanitizedAdminInput]!, $tagged_slack_users: [SanitizedSlackChannelInput]!, $error_url: String!, $author_name: String!, $integrations: [IntegrationType]!, $issue_title: String, $issue_team_id: String, $issue_description: String) {\n  createErrorComment(\n    project_id: $project_id\n    error_group_secure_id: $error_group_secure_id\n    text: $text\n    text_for_email: $text_for_email\n    tagged_admins: $tagged_admins\n    tagged_slack_users: $tagged_slack_users\n    error_url: $error_url\n    author_name: $author_name\n    integrations: $integrations\n    issue_title: $issue_title\n    issue_team_id: $issue_team_id\n    issue_description: $issue_description\n  ) {\n    id\n    created_at\n    updated_at\n    author {\n      id\n      name\n      email\n      __typename\n    }\n    text\n    __typename\n  }\n}\n"
}
