### ISSUE TITLE
GetLogKeyValues fails with too many keys

### ISSUE THREAD

**Issue by SpennyNDaJets** [highlight/highlight#7262]
For Highlight project, there are a lot of logs keys that are causing issues with the response.

Response error
```
code: 158, message: Limit for rows (controlled by 'max_rows_to_read' setting) exceeded, max rows: 1.00 million, current rows: 6.29 million
```

We currently only fetch the keys once and use the frontend to filter out. We should update to allow the search component to pass in text to refetch when the user types.

**Comment by ccschmitz** [comment]
We also need figure out why keys aren't being returned in some cases. See typeahead results on https://app.highlight.io/20427/logs.
