### ISSUE TITLE
How Can I Login?

### ISSUE THREAD

**Issue by pouyaazi** [highlight/highlight#7291]
Hi
i dockerd highlight on my vps but when i want login i have no email to login i just have password
ADMIN_PASSWORD=I_AM_GROOT

what is admin email?

**Comment by iMac7** [comment]
[](https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide
)
any valid email should work. see step 5

**Comment by ayewo** [comment]
> any valid email should work. see step 5

For anyone else like me who's confused by the tribal-knowledge assumed in "see step 5", it can be found in the [docs](https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide) and "step 5" states:

> Visit https://localhost:3000/ to view the dashboard and go through the login flow; use the password set in docker/.env variable ADMIN_PASSWORD with any valid email address.

**Comment by iMac7** [comment]
sorry about that I had the docs open and way too much coffee at the time of writing this XD
