### ISSUE TITLE
create an enterprise feature comparison 

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#7321]
we should have a page in the workspace settings for self-hosted deploys comparing enterprise features
we should also use the same feature set in our higlight.io pricing comparison
![Screenshot from 2023-12-12 12-17-51](https://github.com/highlight/highlight/assets/1351531/87ab6796-b9ba-46a8-ba24-66f1c4979874)

**Comment by DesignMike** [comment]
I was just thinking of this right now. 

So the question is, is the Self-Hosted version limited in any way? Does it include all features compared to the cloud version?
