### ISSUE TITLE
Sourcemap upload fail stops build process

### ISSUE THREAD

**Issue by lveillard** [highlight/highlight#7334]
**Describe the bug**
- When using nextjs and the sourcemap imports, sometimes the connection fails and this throws an error that stops the build process. 

**To Reproduce**
- I guess an easy way is to just disconnect from internet in the middle of the sourcemap upload proces

**Expected behavior**
Not a critical error, the error should be catched and the build should keep going
![image](https://github.com/highlight/highlight/assets/29461076/8501ff05-972a-4dd7-9492-e9a560c78ad2)

**Comment by Vadman97** [comment]
Now released in @highlight-run/next@7.3.5
