### ISSUE TITLE
Seeing unrelated error in my project

### ISSUE THREAD

**Issue by progremir** [highlight/highlight#7647]
**Describe the bug**
My project uses NextJS and Django, but I'm seeing NestJS errors in my dashboard.

**To Reproduce**

1. Go to Errors
2. Click on the error
3. Scroll down to stacktrace
4. See the source of it

**Expected behavior**
not seeing stuff that's not related to my org. This kinda makes me worried if other people are seeing my errors/logs now.

**Screenshots**
<img width="968" alt="image" src="https://github.com/highlight/highlight/assets/17231674/1c5a065a-e588-49ac-a0fd-ca3b8581f287">

**Additional context**

**Comment by Vadman97** [comment]
Hey @progremir , appreciate the report. I can confirm that your errors / logs cannot be seen by other accounts. We had some of our end-to-end tests unintentionally pollute a handful of projects, which has since been fixed.
