### ISSUE TITLE
setup CI for the php SDK

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#7691]
* PRs should run php sdk unit tests in the [sdk repo](https://github.com/highlight/highlight-php) 
 see https://github.com/highlight/highlight/pull/7683#issuecomment-1931613351 and https://github.com/highlight/highlight/pull/7152#issuecomment-1868233107

**Comment by Vadman97** [comment]
/bounty 40
cc @ayewo

**Comment by ayewo** [comment]
Thanks @Vadman97 🙏.

I’m trying to finish another PR but I’ll kick off my /attempt #7691

**Comment by Vadman97** [comment]
sounds good @ayewo - no rush

**Comment by ayewo** [comment]
@Vadman97 you may have to do a `/tip @ayewo 40` as it seems the Algora bot is asleep at the wheel.

**Comment by zcesur** [comment]
@ayewo @Vadman97 I'm guessing the bot wasn't installed in the other repo, we just triggered the bounty payout

**Comment by ayewo** [comment]
@zcesur oh I see. On top of things as always👌.
