### ISSUE TITLE
Vercel build failure due to HIGHLIGHT_SOURCEMAP_KEY unbound variable

### ISSUE THREAD

**Issue by jgentes** [highlight/highlight#7810]
**Describe the bug**
Vercel doesn't recognize the use of the variable in the `package.json` file and produces this error on deploy:
![image](https://github.com/highlight/highlight/assets/1149470/984e7f43-5a4a-4482-ae8a-4b1a509796c4)

**To Reproduce**
Use this as your build script: `"build": "remix build --sourcemap && npx --yes @highlight-run/sourcemap-uploader upload --apiKey $HIGHLIGHT_SOURCEMAP_KEY --path ./build && find build -name '*.js.map' -type f -delete",`

Feel free to test @ https://github.com/jgentes/mixpoint

**Comment by jgentes** [comment]
Sorry this was due to the variable only being added to the production environment - I created a secondary Highlight config for development builds and will use a different key for previews.

**Comment by Vadman97** [comment]
no worries; thanks for the update @jgentes
