### ISSUE TITLE
Next.js build is failing due to js-cookie being bundled as a dependency

### ISSUE THREAD

**Issue by acalinica** [highlight/highlight#7938]
**Describe the bug**
Next.js fails to compile a build due to `js-cookie` module.

```sh
./node_modules/@highlight-run/next/dist/next-client.js
Module not found: Can't resolve 'js-cookie'
```

**To Reproduce**

1. install in a next.js app `@highlight-run/next@latest` (I use yarn)
2. run `next build`
3. See error

```sh
Failed to compile.

./node_modules/@highlight-run/next/dist/next-client.js
Module not found: Can't resolve 'js-cookie'

https://nextjs.org/docs/messages/module-not-found


> Build failed because of webpack errors
error Command failed with exit code 1.
```

**Expected behavior**
Next build should pass without having to install `js-cookie` as a direct dependency to my project.

**Additional context**
I can see `js-cookie` being a devDependency in `@highlight-run/next` yet it's being bundled in the `dist/next-client.js` which actually means that it should be moved in the dependency section or it should be made a peerDependency (not ideal).

`dist/next-client.js`

```js
"use client";
"use strict";var e=require("react"),r=require("highlight.run"),t=require("js-cookie")...
//# sourceMappingURL=next-client.cjs.map
```

**Comment by acalinica** [comment]
Adding `js-cookie` as a devDependency to your project will make this problem go away as a temporary fix.

**Comment by Vadman97** [comment]
Thanks for the report @acalinica . Working on a fix now!

**Comment by Vadman97** [comment]
Looks like this issue was introduced via the new dependency from https://github.com/highlight/highlight/pull/7816
Assigning to @deltaepsilon to take a look.

**Comment by deltaepsilon** [comment]
I am officially a dingus. Thank you @acalinica!
