### ISSUE TITLE
Structured Logging

### ISSUE THREAD

**Issue by rodion-m** [highlight/highlight#8365]
At first, thanks a lot for a great product! From the project description I didn't get, is Structured Logging logging supported in the highlight?

It's a great feature that allows to log whole object and then filter logs by specific field(s) from the object. Here a simple example:

```ts
// Log an object with structured data
logger.info('User login attempt', { userId: 12345, status: 'successful', timestamp: new Date().toISOString() });

// This will output a JSON log like:
// {
//   "level": "info",
//   "message": "User login attempt",
//   "userId": 12345,
//   "status": "successful",
//   "timestamp": "2021-05-06T12:34:56.789Z"
// }
```

[Seq](https://datalust.co/seq) supports structured logging very well, but it's a little bit huge and doesn't support many cool features that highlight does.

**Comment by Vadman97** [comment]
yes, supported as with the `console.log('User login attempt', { userId: 12345, status: 'successful', timestamp: new Date().toISOString() });` example
