### ISSUE TITLE
Self Host have until time?

### ISSUE THREAD

**Issue by 729993031** [highlight/highlight#8370]
**Describe the bug**
When I use the [guide](https://www.highlight.io/docs/getting-started/self-host/dev-deployment-guide) to create a  Local Dev .

The notification talk me , sessions until at 05/12/24. 

**To Reproduce**
![image](https://github.com/highlight/highlight/assets/13050361/81977a4c-2eae-4bbd-96d8-1fbda1d23f2a)

Are they is true?

**Comment by Vadman97** [comment]
Hi @729993031 , this is no longer the case but rather a UI issue that we show that banner (self hosted still starts on 'unlimited free trial' but will switch to the subscribed tier so there will be no limits).
