### ISSUE TITLE
dashboard should show default title based on metric being graphed

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#8579]
The default title of the chart should be updated to the graphed value once one is picked.

<img src="https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/d6d7aeda-81ff-4780-b1b7-58f2ae4d3582/f455af81-1e09-4499-a9ed-3e316b00b346?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS9kNmQ3YWVkYS04MWZmLTQ3ODAtYjFiNy01OGYyYWU0ZDM1ODIvZjQ1NWFmODEtMWUwOS00NDk5LWE5ZWQtM2UzMTZiMDBiMzQ2IiwiaWF0IjoxNzE1ODE0MTQ5LCJleHAiOjMzMjg2Mzc0MTQ5fQ.RAHH6CExyLkTrUgSO4tbIEPgc028aBzapRc0HWqXg7g " alt="Screenshot from 2024-05-15 16-02-04.png"  />

ie. in this case, the `metric view title` should be set to `CountDistinct(Identifier)`

**Comment by neo773** [comment]
@Vadman97 
What should be the default title?

**Comment by Vadman97** [comment]
@neo773 updated the description, thanks

**Comment by ezhil56x** [comment]
@Vadman97 

I would like to work on this.
Currently for all Metrics the title is `Dashboard`. But the goal is to update the title with the Metrics name.
For example if the Metrics name is Insights then the title should be `Dashboard - Insights`.
Is this what you're expecting?

**Comment by Vadman97** [comment]
@ezhil56x please see the description. the default is currently `Untitled metric view` but should update based on the function / metric that are being graphed. In the description image example, the title should update to `CountDistinct(Identifier)`

**Comment by ezhil56x** [comment]
I would like to work on this
Can I get assigned?

**Comment by Vadman97** [comment]
@ezhil56x  see https://github.com/highlight/highlight/issues/8579#issuecomment-2113614355 for instructions to get started - feel free to work on this issue.
