### ISSUE TITLE
setup page broken link

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#8651]
[https://app.highlight.io/16425/setup/client/js/other](https://app.highlight.io/16425/setup/client/js/other) -> clicking `Back to Project` in the top left corner navigates to broken link `/sessions`

**Comment by rajeshj11** [comment]
@Vadman97 can I get view-only access to your linear workspace? Tried to open the below link,  Not able to view the issue. https://linear.app/highlight/issue/HIG-4694/setup-page-broken-link
