### ISSUE TITLE
unable to login due to "Failed to fetch"

### ISSUE THREAD

**Issue by MoaMoa90** [highlight/highlight#8677]
hello friends!
i have successfully installed highlight hobby on my raspberry pi 5 ubuntu server (arm64)
it runs under my home network so i tweaked some port forwordings

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/79aa267b-3e0b-4560-a50e-f0a478aee529/51f5bba7-de90-4d2d-b65e-8e48524657a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS83OWFhMjY3Yi0zZTBiLTQ1NjAtYTUwZS1mMGE0NzhhZWU1MjkvNTFmNWJiYTctZGU5MC00ZDJkLWI2NWUtOGU0ODUyNDY1N2EwIiwiaWF0IjoxNzE3MDA1NTEyLCJleHAiOjMzMjg3NTY1NTEyfQ.A668sScyQ7X8CwM0PtFYUCj2rwwnAYO1FW1zJuErBRI)

and all the containers on my rasp server is working well

but when i try to login with dummy email address and ADMIN_PASSWORD, it respond with "failed to fetch" message

1. connect to my internal network which is rasp server is addressed ([http://192.168.219.107:3000/sign_in](http://192.168.219.107:3000/sign_in))
2. try to login and failed

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/26b42b40-ea24-467b-8aff-4a1fdd25f200/618b8d4e-40f4-41cc-8429-f50d0b48803e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS8yNmI0MmI0MC1lYTI0LTQ2N2ItOGFmZi00YTFmZGQyNWYyMDAvNjE4YjhkNGUtNDBmNC00MWNjLTg0MjktZjUwZDBiNDg4MDNlIiwiaWF0IjoxNzE3MDA1NTEyLCJleHAiOjMzMjg3NTY1NTEyfQ.cl2RVwpdriPmVFlllk1UIwT9UaY-x409r6wHuW-2ovg)

unfortunately there no relevant logs, apart from these logs...

can anyone help me?

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/4111cca9-0317-492f-a928-036bd8dc2a4e/69c2e74e-5ebf-4e22-a969-295b91f48b48?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS80MTExY2NhOS0wMzE3LTQ5MmYtYTkyOC0wMzZiZDhkYzJhNGUvNjljMmU3NGUtNWViZi00ZTIyLWE5NjktMjk1YjkxZjQ4YjQ4IiwiaWF0IjoxNzE3MDA1NTEyLCJleHAiOjMzMjg3NTY1NTEyfQ.NHB4PpS0qGHm3aeaDWmQdA-Cj1UsEnXzXDLUzY6QbWQ)

**Comment by MoaMoa90** [comment]
in addition, i set my env variables like this

export REACT_APP_PRIVATE_GRAPH_URI=http://192.168.219.107:8082/private 
export REACT_APP_PUBLIC_GRAPH_URI=http://192.168.219.107:8082/public 
export REACT_APP_FRONTEND_URI=http://192.168.219.107
ADMIN_PASSWORD = somepass

**Comment by Vadman97** [comment]
@moamoa90 could you please try this with the latest version of the docker images? we've made a number of improvements here

**Comment by neurekadev** [comment]
I'm having the same issue despite everything being setup correctly as per the docs.

Not sure if related to #5245 but it seems this is a common occurrence.
