### ISSUE TITLE
Django errors not processed by highlight

### ISSUE THREAD

**Issue by progremir** [highlight/highlight#8684]
**Describe the bug**
I noticed that some errors are not showing up in highlight and found [this line](https://github.com/highlight/highlight/blob/d630e9132c3df7e292baa08132bbf379dafd47e2/sdk/highlight-py/highlight_io/integrations/django.py#L46), which seems to limit error handling to wsgi workers. We recently switched to asgi, so I think this is the cause of the problem.

**To Reproduce**

1. Set up a django project and run it with asgi server
2. Make a request that raises an exception
3. Go to highlight and no error there

**Expected behavior**
Error being handled any way

**Screenshots**

**Additional context**

**Comment by hategekimanahirwaarnold** [comment]
Hi @Vadman97,

Thank you for setting up this bounty!

I've reproduced the error in Django and logged it on highlight.io. Please refer to the attached screenshots for details.

- 
<img width="1440" alt="Screen Shot 2024-10-19 at 18 23 33" src="https://github.com/user-attachments/assets/bf3ac954-0a24-4618-9d49-404f822cd214">
<img width="1440" alt="Screen Shot 2024-10-19 at 18 23 54" src="https://github.com/user-attachments/assets/c0c78f97-1b69-4c86-a4d0-da7c93a1c12d">
<img width="1440" alt="Screen Shot 2024-10-19 at 18 23 17" src="https://github.com/user-attachments/assets/dda23ef4-4ac7-4440-bdf3-56cca2512b2a">
In the first screenshot, I triggered a division by zero on a 555, which caused an error.
- The second screenshot shows the error as it appeared in my browser.
- The third screenshot confirms the error was successfully logged in my highlight.io account.

Could we close the issue, or is there anything else that needs attention?

**Comment by Vadman97** [comment]
thank you! sounds good to me to close.
