### ISSUE TITLE
add a history of recent searches

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#8785]
[https://www.loom.com/share/3635973fd10840f0a24743080f79a6ec](https://www.loom.com/share/3635973fd10840f0a24743080f79a6ec)

**Comment by govindplal** [comment]
Can I work on this?

**Comment by Vadman97** [comment]
final design from @julian-highlight https://www.figma.com/design/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=14709-163080&m=dev&t=Wjl8HasmiufkPJmX-1
