### ISSUE TITLE
Unable to start "hobby" instance. 

### ISSUE THREAD

**Issue by 729993031** [highlight/highlight#8791]
**Describe the bug**
cant login

"**To Reproduce**

1. referred to [hobby](https://www.highlight.io/docs/getting-started/self-host/self-hosted-hobby-guide)for deployment.
2. change docker/.env
   Update the following values to my backend IP

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/ececb648-50a6-4dbf-b8f5-e7e0e2d024a1/4b28ac72-a417-46b2-ab2d-9161fdd48332?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS9lY2VjYjY0OC01MGE2LTRkYmYtYjhmNS1lN2UwZTJkMDI0YTEvNGIyOGFjNzItYTQxNy00NmIyLWFiMmQtOTE2MWZkZDQ4MzMyIiwiaWF0IjoxNzE4ODA0Nzc2LCJleHAiOjMzMjg5MzY0Nzc2fQ.TeSle96x8IybzwYkSS8331dDBj0VkZ63Be0JKjtI6Vo)

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/1f3109df-a16a-4b31-b24e-751fadf8460e/e2a02f63-eac8-4c3f-95a6-97dcf2a85984?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS8xZjMxMDlkZi1hMTZhLTRiMzEtYjI0ZS03NTFmYWRmODQ2MGUvZTJhMDJmNjMtZWFjOC00YzNmLTk1YTYtOTdkY2YyYTg1OTg0IiwiaWF0IjoxNzE4ODA0Nzc2LCJleHAiOjMzMjg5MzY0Nzc2fQ.esDRQsFsuCeXmclrWfk7OL9vIObB-5dN4E0UCCRzax8)

cant login

**Expected behavior**
want to login
**Screenshots**

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/5cc9d659-c579-4bf2-8853-612b6432b5ee/21c4a2b3-17f3-48c9-b5fe-be35bb62bf65?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS81Y2M5ZDY1OS1jNTc5LTRiZjItODg1My02MTJiNjQzMmI1ZWUvMjFjNGEyYjMtMTdmMy00OGM5LWI1ZmUtYmUzNWJiNjJiZjY1IiwiaWF0IjoxNzE4ODA0Nzc2LCJleHAiOjMzMjg5MzY0Nzc2fQ.w09oGXlxKF49gs-IFa598DsKGWYR9932K1Vj9KJRmmY)

![image](https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/87d84b2c-a781-4b62-9b10-a8b8d12ff716/cf3129a8-a733-46fe-ba0a-288ee220f2d4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS84N2Q4NGIyYy1hNzgxLTRiNjItOWIxMC1hOGI4ZDEyZmY3MTYvY2YzMTI5YTgtYTczMy00NmZlLWJhMGEtMjg4ZWUyMjBmMmQ0IiwiaWF0IjoxNzE4ODA0Nzc2LCJleHAiOjMzMjg5MzY0Nzc2fQ.7qpdztJjYqj9xvfh5tJidnCiYys8DNkzdHOKrCpSXgs)

**Comment by Vadman97** [comment]
@729993031 looks like you have a fatal log line from a clickhouse migration failure (dirty version). if you are trying to upgrade from an old version, do you have some data that is failing to migrate? 

you can remove all clickhouse data by running `docker rm -f clickhouse` and running `docker volume rm highlight_clickhouse-data`, or all data by running `docker compose down --remove-orphans --volumes`, and then restarting the hobby stack.

**Comment by 729993031** [comment]
when I use centos7 to start  , the clickhouse say me " Dirty database version 42. Fix and force version. when use the newly system ". something about unbuntu 22.04.3 not have error
