### ISSUE TITLE
Logging doesn't work inside FastAPI background tasks

### ISSUE THREAD

**Issue by sgondala** [highlight/highlight#8827]
**Describe the bug**
Logs inside background tasks of fastapi are not getting captured.

**To Reproduce**
```
import logging

import highlight_io
from fastapi import BackgroundTasks, FastAPI, Request
from highlight_io.integrations.fastapi import FastAPIMiddleware

H = highlight_io.H(
    "<>",
    instrument_logging=True,
    service_name="my-app",
    service_version="git-sha",
    environment="production",
)

app = FastAPI()
app.add_middleware(FastAPIMiddleware)


def test_fn():
    logging.error("Logging inside background task")


@app.get("/")
async def root(request: Request, background_tasks: BackgroundTasks):
    logging.info("Before adding background task")
    background_tasks.add_task(test_fn)
    logging.info("After adding background task")
```

**Expected behavior**
Expected to see "Logging inside background task" but I don't see that. I only see the logs in the root function

**Screenshots**

**Additional context**
I suspect it's due to the custom middleware. If I remove the middleware line `app.add_middleware(FastAPIMiddleware)`, I can see the logs.

However, I can't remove it because I want to capture any unforseen exceptions etc to be visible in `Errors` section, and this happens only when I add the middleware instrumentation

**Comment by sgondala** [comment]
That doesn't work either.

And it also doesn't seem like a good pattern - passing a new parameter to every function just to do logging from that function.

**Comment by Vadman97** [comment]
@sgondala when you say
> If I remove the middleware line app.add_middleware(FastAPIMiddleware), I can see the logs.
do you mean that then the logs are showing up in highlight? very strange that this is the case

**Comment by sgondala** [comment]
> do you mean that then the logs are showing up in highlight? very strange that this is the case

Yeah, that's correct. When I don't add the middleware line - logs inside background tasks also show up in highlight.


> do you know if the FastAPI BackgroundTasks use a custom logging interface normally

Not sure about this. I just use the default logging library and it works fine from anywhere.

**Comment by sgondala** [comment]
Hey @Vadman97 

Please let me know if you faced this before or have a workaround for now.

**Comment by Vadman97** [comment]
hey @sgondala, apologies for the delay. adding @zane to take a look later this week!

**Comment by sgondala** [comment]
Thank you.

**Comment by sgondala** [comment]
I found a hack.  

You middleware implementation doesn't work with background tasks.

I defined a custom middleware where I define background tasks and pass that to the main API call. This works. 

```
@app.middleware("http")
async def my_longrunning_background_function_middleware(request: Request, call_next):
    background_tasks = BackgroundTasks()
    request.state.background_tasks = background_tasks
    response = await call_next(request)
    response.background = background_tasks
    return response
```

How I use it in the main function 

```
@app.get("/")
async def root(request: Request, background_tasks: BackgroundTasks):
    logging.info("Before adding background task")
    request.state.background_tasks.add_task(test_fn)
    logging.info("After adding background task")
```

Does this look correct? If yes, can you help me integrate this with your middleware so that everything plays well?

**Comment by mayberryzane** [comment]
@sgondala thanks for looking into the workaround here - taking a look right now to figure out the best change for our middleware that will handle this

**Comment by mayberryzane** [comment]
hi @sgondala - 
we released a version of our python package (highlight-io 0.8.4) which includes a fix for this - please let us know if you have any other issues! Thanks

**Comment by sgondala** [comment]
It works now. Thanks for fixing it ! :D
