### ISSUE TITLE
hide empty groups by default

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#8846]
dashboard metrics should hide empty group values by default

**Comment by gowreesh369** [comment]
Is this issue open? Can i take it?

**Comment by Vadman97** [comment]
yes, i believe this issue is referring to hiding values in the legend with 0 values

<img src="https://uploads.linear.app/56bcb1e5-92b5-4fad-b2c1-bb6738442711/503b551b-71a7-4e3b-b57b-5ae272e36637/a4614d9f-7512-4c2f-a1f8-62a76c86fd2b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzU2YmNiMWU1LTkyYjUtNGZhZC1iMmMxLWJiNjczODQ0MjcxMS81MDNiNTUxYi03MWE3LTRlM2ItYjU3Yi01YWUyNzJlMzY2MzcvYTQ2MTRkOWYtNzUxMi00YzJmLWExZjgtNjJhNzZjODZmZDJiIiwiaWF0IjoxNzIwMDI1NDYyLCJleHAiOjMzMjkwNTg1NDYyfQ.fsMhN3GjJwZ9DBBTxzopakAcQSrvGo2GGIh-yIwhPEg " alt="Screenshot 2024-07-03 at 09.50.35.png" width="319" height="358" />
