### ISSUE TITLE
How can stop the session replay ?

### ISSUE THREAD

**Issue by 729993031** [highlight/highlight#8902]
**Is your feature request related to a problem? Please describe.**
when i watch the [document](https://www.highlight.io/docs/general/product-features/session-replay/overview)，I not found how to close the session play，only use Error Monitoring to the frontEnd.

**Describe the solution you'd like**
Can close the session play，only use Error Monitoring to the frontEnd.

**Describe alternatives you've considered**
Provider [Configurations ](https://docs.sentry.io/platforms/javascript/session-replay/#lazy-loading-replay) to close the session play

**Comment by Vadman97** [comment]
hi @729993031 , you can use the client sdk without session replay as per [our docs here](https://www.highlight.io/docs/general/product-features/session-replay/filtering-sessions#disable-all-session-recording). you can stop a session on demand [via our sdk H.stop method](https://www.highlight.io/docs/general/product-features/session-replay/filtering-sessions#filtering-sessions-using-custom-logic).
