### ISSUE TITLE
nextjs rewrites overwritten

### ISSUE THREAD

**Issue by ryanleecode** [highlight/highlight#8963]
**Describe the bug**
my nextjs rewrites are being overwritten

**To Reproduce**

1. wrap your next.js config with `withHighlightConfig`
2. set your next.js config rewrite to `async () => [{ source: '/blah', destination: 'https://www.google.com' }]`

**Expected behavior**
Rewrite should be preserved

**Additional context**
Highlight assumes all the rewrites use the `beforeFiles/afterFiles/fallback` syntax:

https://github.com/highlight/highlight/blob/ca0bc803631e09cd345d19f3d2e1b3025f055b6e/sdk/highlight-next/src/util/with-highlight-config.ts#L114

**Comment by ryanleecode** [comment]
Existing rewrites should be dumped into the fallback array

**Comment by Vadman97** [comment]
thanks for the report @ryanleecode - we will have this fixed by next week!
