### ISSUE TITLE
api key for OTEL

### ISSUE THREAD

**Issue by ryanleecode** [highlight/highlight#8990]
Is it correct that if somebody has my project id they can just send whatever OTEL metrics they like without my consent? this seems stupid

**Comment by Vadman97** [comment]
hey @ryanleecode, that's correct, since the worst they would do is polute the data in your account. if this is a problem, you can set up filters in highlight to ignore data without a specific environment key (for instance), which you can check to be a secret value that only you know.

**Comment by ryanleecode** [comment]
i dont think that is sufficient because they can take all your session replay hours without your consent

**Comment by ryanleecode** [comment]
Why is this closed?
