### ISSUE TITLE
Change `gpt-3.5-turbo-16k` to `gpt-4o-mini`

### ISSUE THREAD

**Issue by gustavopch** [highlight/highlight#9165]
Just change `gpt-3.5-turbo-16k` to `gpt-4o-mini` here and Harold will be much cheaper and much better.

`gpt-3.5-turbo-16k`:
- $3.00 / 1M input tokens
- $4.00 / 1M output tokens

`gpt-4o-mini`:
- $0.150 / 1M input tokens
- $0.600 / 1M output tokens

https://github.com/highlight/highlight/blob/71ce45d6a113ef26a98d1624f0252251255db767/packages/ai/src/utils.ts#L89C1-L89C30

**Comment by VriaA** [comment]
Hi! Can I take on this issue?

**Comment by Vadman97** [comment]
sure, thanks
