### ISSUE TITLE
ux for switching segments is slow

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#9250]
https://www.loom.com/share/a70487145df548d6988336fd6de65bf7

https://www.figma.com/design/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=14090-444954&node-type=section&t=vlxOU5nW1swgKf97-11

**Comment by anoopw3bdev** [comment]
Hey @Vadman97 is this issue up for grabs? would like to contribute...!

**Comment by anoopw3bdev** [comment]
@Vadman97 possible to assign to me?
