### ISSUE TITLE
problem logging in

### ISSUE THREAD

**Issue by biellil** [highlight/highlight#9254]
I am unable to log into my account
![image](https://github.com/user-attachments/assets/d6ff48dc-cfd3-4835-b597-3f8c374f2990)

**Comment by Vadman97** [comment]
hey @biellil , could you try using incognito / ensuring you do not have any ad blockers active, and trying again?

**Comment by biellil** [comment]
> hey @biellil , could you try using incognito / ensuring you do not have any ad blockers active, and trying again?

I've done this until I cleared the browser cache and used more than one browser

**Comment by biellil** [comment]
> hey @biellil , could you try using incognito / ensuring you do not have any ad blockers active, and trying again?

I've done this until I cleared the browser cache and used more than one browser
